import type { Lang } from "./zodiacData";

/**
 * AI-drafted, evergreen "excitement" lines for the weekly scratch card (not a
 * personalized reading tied to any real event). A large pool (~200 per language)
 * so the cycle — one per ISO week, see ScratchCard.tsx — takes years to repeat,
 * instead of the 8-week loop a small pool would create.
 */
export const SCRATCH_REWARDS: Record<Lang, string[]> = {
  sl: [
    "Nekdo razmišlja o tem, kako bi ti povedal, kaj čuti — daj mu priložnost, da to stori.",
    "Pogovor o čustvih, ki se mu izogibaš, bo lažji, kot pričakuješ.",
    "Tvoje srce že ve, komu zaupa. Poslušaj ga, preden posluša glavo.",
    "Nekdo, ki misli, da si ga že pozabil, te ta teden pogreša bolj, kot si misliš.",
    "Ljubezen, ki jo iščeš zunaj, morda že stoji bliže, kot vidiš.",
    "Star občutek se ta teden vrne — tokrat ga ne odrini, samo opazuj ga.",
    "Iskrenost, ki jo poveš danes, spremeni nekaj, česar zdaj še ne vidiš.",
    "Nekdo te opazuje z več naklonjenosti, kot si upaš verjeti.",
    "Majhna gesta ljubezni, ki jo narediš ta teden, se ti povrne, ko najmanj pričakuješ.",
    "Tvoja ranljivost je tisto, kar nekoga ta teden pritegne bližje, ne odvrne.",
    "Tvoje ime bo ta teden prišlo na misel nekomu, ki se dolgo ni oglasil.",
    "Nekdo iz preteklosti razmišlja, kako bi spet stopil v stik s tabo.",
    "Sporočilo, ki ga ne pričakuješ, prihaja od nekoga, ki te ima res rad.",
    "Nekdo hrani tvojo fotografijo ali besede, ne da bi ti to kdaj povedal.",
    "V mislih nekoga si prisoten pogosteje, kot si predstavljaš.",
    "Nekdo se ta teden spomni trenutka, ki si ga sam že skoraj pozabil.",
    "Prijatelj, ki dolgo ni pisal, razmišlja prav zdaj, kako bi ti sporočil.",
    "Nekdo te brani, ko tebe ni zraven, ne da bi to kdaj izvedel.",
    "Nekje daleč nekdo prižge svečo prav zate, ne da bi vedel zakaj.",
    "Tvoje ime pade v pogovoru, ki ga ne slišiš, a je topel.",
    "Priložnost, ki je videti majhna, ta teden nosi večjo vrednost, kot kaže.",
    "Vrata, ki so bila dolgo zaprta, se ta teden rahlo odprejo.",
    "Nekaj, kar dolgo gradiš, se ta teden premakne za korak naprej.",
    "Denar, ki ga pričakuješ, prihaja počasneje, kot upaš, a prihaja.",
    "Ponudba, ki jo ta teden prejmeš, je vredna več premisleka, kot se zdi na prvi pogled.",
    "Trud, ki ga nihče ne vidi, ta teden dobi prvo tiho priznanje.",
    "Nekaj, kar si dolgo odlašal, ta teden prinese nepričakovano nagrado.",
    "Vprašaj za tisto, kar si vreden — ta teden je odgovor bolj naklonjen, kot misliš.",
    "Majhna investicija vase se ta teden obrestuje bolj, kot pričakuješ.",
    "Nekdo ti ta teden ponudi priložnost, ki je ne smeš prehitro zavrniti.",
    "En stavek, ki ga izrečeš ta teden, si bo nekdo zapomnil dlje, kot misliš.",
    "Pogovor, ki se mu izogibaš, je lažji, kot si ga predstavljaš v glavi.",
    "Klic, ki ga ta teden ne pričakuješ, prinese dobre novice.",
    "Sporočilo, ki ga čakaš, prihaja — samo malo kasneje, kot upaš.",
    "Vprašanje, ki si ga dolgo nosiš v sebi, ta teden dobi odgovor.",
    "Beseda, ki jo dolguješ nekomu, ta teden končno najde svojo pot ven.",
    "Nekdo te ta teden posluša bolj pozorno, kot si vajen.",
    "Pogovor, ki se zdi nepomemben, ta teden obrne nekaj na bolje.",
    "Resnica, ki jo poveš na glas, ta teden olajša več, kot si misliš.",
    "Nekdo čaka, da prvi spregovoriš — pogum je na tvoji strani.",
    "Občutek, ki ga imaš od ponedeljka, ni naključje. Sledi mu.",
    "Tvoja intuicija ta teden govori jasneje kot razum — poslušaj, kaj ti pravi.",
    "Nekaj že veš, še preden dobiš dokaz. Zaupaj temu znanju.",
    "Notranji glas, ki ga utišuješ, ima prav pogosteje, kot priznaš.",
    "Ta teden te bo nekaj presenetilo manj, če prej poslušaš srce.",
    "Sanje, ki se ponavljajo, nosijo sporočilo — zapiši si jih.",
    "Prvo, kar pomisliš, je ta teden pogosteje pravilno kot dvom, ki mu sledi.",
    "Telo ti sporoča, kaj potrebuje, še preden to razume um. Prisluhni mu.",
    "Nekaj v tebi že ve, kako se bo zgodba iztekla. Ne sili odgovora.",
    "Znak, ki ga iščeš, je bil ves teden pred tabo — samo drugačen, kot pričakuješ.",
    "Strah, ki ga nosiš ta teden, je manjši, kot izgleda od blizu.",
    "Korak, ki se ti zdi prevelik, postane lažji, takoj ko ga narediš.",
    "Pogum ni odsotnost strahu — je odločitev, da greš naprej kljub njemu.",
    "Nekaj, česar se izogibaš, ta teden postane veliko lažje soočiti.",
    "Ta teden te en majhen korak pripelje dlje, kot misliš, da zmoreš.",
    "Odločitev, ki jo odlašaš, postane jasnejša, takoj ko jo izrečeš na glas.",
    "Vprašaj se, česa se v resnici bojiš — odgovor te lahko osvobodi.",
    "Tvoja moč se ta teden pokaže prav tam, kjer je najmanj pričakuješ.",
    "Nekaj neznanega, ki te straši, se izkaže za manj tuje, ko se mu približaš.",
    "Prvi korak je edini, ki se zdi težak. Ostali pridejo sami.",
    "Dovoljeno ti je ta teden narediti manj — svet se ne bo sesul.",
    "Počitek, ki si ga odrekaš, ta teden postane nujen, ne luksuz.",
    "Nihče te ne bo ljubil manj, če se ta teden ustaviš.",
    "Ni ti treba dokazovati vrednosti z delom. Že si dovolj.",
    "Ta teden si vzemi eno uro samo zase, brez občutka krivde.",
    "Utrujenost, ki jo skrivaš, si zasluži priznanje, ne ignoriranje.",
    "Dovoli si reči 'ne' ta teden, brez dolge razlage.",
    "Mir, ki ga iščeš zunaj, ta teden najdeš v enem tihem popoldnevu.",
    "Ni nujno, da si vedno na razpolago vsem. Tudi tebi pripada čas.",
    "Ta teden je za počitek prava priložnost, ne šibkost.",
    "Majhno presenečenje te ta teden čaka tam, kjer ga najmanj pričakuješ.",
    "Nekaj nepričakovanega prekine tvojo rutino na prijeten način.",
    "Darilo, ki ga ne pričakuješ, prihaja od nekoga, na katerega redko pomisliš.",
    "Dan, ki se zdi navaden, skriva eno lepo presenečenje.",
    "Nekaj majhnega ta teden razveseli bolj, kot bi pričakoval.",
    "Naključno srečanje ta teden prinese nekaj, česar se boš še dolgo spominjal.",
    "Presenečenje, ki prihaja, ni veliko — a pride ravno takrat, ko ga potrebuješ.",
    "Nekaj, kar si že skoraj pozabil, se ta teden nepričakovano vrne.",
    "En trenutek te ta teden ujame nepripravljenega — na dober način.",
    "Nekaj lepega prihaja od nekoga, ki mu najmanj zaupaš, da bo poskrbel zate.",
    "Ponavljajoča se števila, ki jih opaziš ta teden, niso naključje. Pazi nanje.",
    "Vesolje ta teden govori tiho — v pesmi, ki jo slišiš ob pravem trenutku.",
    "Znak, ki ga potrebuješ, pride v obliki, ki je ne pričakuješ.",
    "Sinhroniciteta ta teden deluje v tvoj prid — opazi majhna naključja.",
    "Nekaj, kar se ti zgodi trikrat v enem tednu, ni slučaj.",
    "Vesolje ti ta teden pošilja potrditev — v obliki miru, ne odgovora.",
    "Ptica, oblak ali pesem, ki te ustavi, nosi sporočilo zate.",
    "Pot, ki se ti odpre brez truda, je pot, po kateri je vredno iti.",
    "Nekaj se ti dogaja prehitro, da bi bilo naključje.",
    "Ta teden opazi, kaj se ponavlja okoli tebe — to je tvoj znak.",
    "Nekaj iz preteklosti se ta teden umiri samo od sebe, brez tvojega truda.",
    "Odpuščanje, ki ga dolguješ sebi, je pomembnejše od tistega, ki ga dolguješ drugim.",
    "Stara rana, ki jo nosiš, ta teden postane lažja za nositi.",
    "Nekdo iz preteklosti ne potrebuje opravičila — samo tvoj mir.",
    "Poglavje, ki si ga zaprl prehitro, se ta teden razjasni.",
    "Nekaj, kar te je nekoč bolelo, ta teden izgubi svojo moč nad tabo.",
    "Sprava s preteklo različico sebe je ta teden bližje, kot misliš.",
    "Star spomin se vrne zato, da ga končno spustiš, ne obudiš.",
    "Nekaj, kar že dolgo nosiš, je ta teden pripravljeno, da ga odložiš.",
    "Preteklost te ta teden ne kliče nazaj — samo pozdravlja, preden odide za vedno.",
    "Prijatelj, ki ga dolgo ne vidiš, ta teden misli nate bolj, kot veš.",
    "Ena beseda hvaležnosti, izrečena prijatelju, ta teden pomeni več, kot misliš.",
    "Novo prijateljstvo se ta teden začne z navadnim pogovorom.",
    "Nekdo, ki te podpira v tišini, si zasluži, da mu to poveš.",
    "Stara vez, ki se je zdela oslabljena, ta teden dobi novo priložnost.",
    "En klic prijatelju ta teden spremeni njegov dan bolj, kot pričakuješ.",
    "Nekdo v tvoji bližini potrebuje samo, da ga vprašaš, kako je res.",
    "Prijateljstvo, ki ga gradiš počasi, se ta teden izkaže za trdnejše, kot misliš.",
    "Nekdo te ta teden brani v pogovoru, za katerega niti ne veš.",
    "Skupni smeh s prijateljem ta teden zdravi več, kot se zdi.",
    "Ideja, ki se ti zdi premajhna, ta teden zasluži prostor na papirju.",
    "Nekaj ustvarjalnega, kar odlašaš, ta teden postane lažje začeti.",
    "Tvoja domišljija ta teden dela hitreje kot dvom — ne ustavljaj je.",
    "Projekt, ki počiva v predalu, si zasluži, da ga ta teden pogledaš znova.",
    "Nekaj, kar ustvariš ta teden, ima dolgo življenjsko dobo pred sabo.",
    "En majhen ustvarjalni korak ta teden odpre vrata večjemu.",
    "Ni ti treba čakati na navdih. Ta teden pride, če začneš brez njega.",
    "Tvoj glas, izražen na kakršenkoli način, ta teden nekoga dotakne.",
    "Nekaj, kar narediš samo zase, ta teden postane nekaj več.",
    "Ustvarjalna blokada, ki jo nosiš, ta teden popusti hitreje, kot pričakuješ.",
    "Telo ti ta teden sporoča, kje potrebuješ nežnost, ne discipline.",
    "Energija, ki jo pogrešaš, se vrne, takoj ko si dovoliš počasnejši tempo.",
    "Majhna sprememba v vsakdanjem ritmu ta teden prinese več miru v telo.",
    "Utrujenost, ki jo nosiš, ni šibkost — je znak, da je čas za premor.",
    "Ta teden nameni pet minut samo dihanju. Telo ti bo hvaležno.",
    "Nekaj, kar telo že dolgo prosi, ta teden končno dobi pozornost.",
    "Sprehod na svežem zraku ta teden razjasni več, kot bi pričakoval.",
    "Spanje, ki ga odlašaš, ta teden postane nujnejše, kot se zdi.",
    "Telo hitreje okreva, kadar mu zaupaš, ne kadar ga siliš.",
    "Majhna nega zase ta teden prinese večji učinek, kot pričakuješ.",
    "Družinski član, na katerega redko pomisliš, se ta teden oglasi.",
    "En pogovor z družino ta teden razčisti nekaj, kar je predolgo tiho ležalo.",
    "Nekdo v družini potrebuje ta teden samo tvojo prisotnost, ne nasvetov.",
    "Stara napetost v družini se ta teden začne umirjati sama od sebe.",
    "Otroški spomin, ki se ta teden vrne, prinese nepričakovano toplino.",
    "Beseda hvaležnosti staršem ali njim podobnim ta teden pomeni več, kot misliš.",
    "Nekaj, kar si dolgo skrival pred družino, ta teden postane lažje deliti.",
    "Družinska vez, ki se zdi oddaljena, ta teden dobi priložnost za bližino.",
    "En majhen gest do doma ta teden prinese veliko toplino nazaj.",
    "Nekdo doma te ta teden pogreša bolj, kot pokaže.",
    "Nekaj se ta teden konča, da lahko nekaj drugega začne.",
    "Sprememba, ki se ji upiraš, je ta teden bližje, kot misliš, da si pripravljen.",
    "Nov začetek ne zahteva popolnega načrta — samo prvi korak.",
    "Nekaj starega ta teden izgubi svoj prijem nate.",
    "Vrata, ki se zapirajo, ta teden odprejo prostor za nekaj boljšega.",
    "Nekaj, kar se zdi kot izguba, se ta teden izkaže za prostor.",
    "Sprememba, ki prihaja, je manjša, kot se zdi od daleč — in lažja.",
    "Ta teden je dober trenutek, da spustiš nekaj, kar te ne služi več.",
    "Novo poglavje se ta teden začne pisati, tudi če tega še ne vidiš.",
    "Nekaj, kar si dolgo odlašal spremeniti, ta teden postane preprosto nujno.",
    "Ena stvar, ki jo ta teden vzameš za samoumevno, si zasluži hvaležnost.",
    "Hvaležnost, izražena na glas, ta teden pritegne še več razlogov zanjo.",
    "Nekaj majhnega, kar ta teden opaziš, spremeni, kako gledaš na cel dan.",
    "Ta teden se ustavi in prešteje tri stvari, ki so ti v veselje.",
    "Hvaležnost do sebe je ta teden pomembnejša od hvaležnosti do drugih.",
    "Nekaj, za kar si ta teden hvaležen, se ti bo obrestovalo.",
    "Majhna radost, ki jo opaziš, ta teden pomeni več, kot velika, ki jo čakaš.",
    "Ta teden nameni minuto tišine za vse, kar že imaš.",
    "Hvaležnost spremeni pogled hitreje kot kakršenkoli nasvet.",
    "Nekaj lepega, kar ta teden spregledaš, si zasluži drugi pogled.",
    "Stvar, ki se ji mudi tebi, se ta teden ne mudi vesolju — in to je v redu.",
    "Nekaj, kar čakaš predolgo, je ta teden bližje, kot si misliš.",
    "Potrpljenje, ki ga vlagaš, ta teden ni izgubljen čas.",
    "Odgovor, ki ga čakaš, prihaja — samo ne na način, ki si ga pričakoval.",
    "Ta teden ni čas za odločitev, ampak za čakanje z odprtimi očmi.",
    "Nekaj se zori v ozadju, tudi ko se zdi, da se nič ne dogaja.",
    "Rezultat, ki ga čakaš, potrebuje še malo časa — a prihaja.",
    "Ta teden ne siliš ničesar. Naj stvari pridejo k tebi same.",
    "Nekaj počasnega ta teden nosi več vrednosti kot nekaj hitrega.",
    "Čakanje, ki se zdi neskončno, ta teden dobi prvi znak konca.",
    "Ta teden zaupaj svoji prvi odločitvi — pogosteje je prava, kot misliš.",
    "Vedeti, kaj hočeš, ni predrznost. Ta teden si to dovoli izraziti.",
    "Mnenje, ki ga imaš, si zasluži, da ga poveš na glas.",
    "Ta teden ne rabiš tuje potrditve za nekaj, kar že veš.",
    "Tvoja vrednost ni odvisna od tega, kaj ta teden dosežeš.",
    "Ne primerjaj svoje poti s tujo. Tvoja gre po svojem tempu.",
    "Nekaj, kar si dolgo skrival, ker se ti je zdelo premalo dobro, je ta teden dovolj dobro.",
    "Ta teden stopi v prostor, kot da že veš, da spadaš vanj.",
    "Nihče ne more definirati tvoje vrednosti razen tebe. Ta teden se tega spomni.",
    "Odločitev, ki se ti zdi tvegana, je ta teden bolj pogumna kot nepremišljena.",
    "Srečanje, ki se ta teden zgodi po naključju, ni čisto naključje.",
    "Nekaj, kar se ti zdi kot slučaj, je ta teden natančno tam, kjer mora biti.",
    "Pot, ki se je odprla brez tvojega načrta, je ta teden vredna zaupanja.",
    "Dve stvari, ki se ta teden prekrižata, sta bili namenjeni druga drugi.",
    "Nekdo, ki ga ta teden srečaš čisto po naključju, ima zate pomembno vlogo.",
    "Trenutek, ki se zdi nepomemben, ta teden postane obrat v zgodbi.",
    "Nič se ne zgodi prezgodaj ali prepozno — ta teden se to izkaže.",
    "Nekaj, kar iščeš že dolgo, te ta teden najde samo od sebe.",
    "Usoda ta teden ne kliče glasno — samo tiho odpre vrata.",
    "Naključje, ki se ti zgodi ta teden, je pravzaprav povabilo.",
    "Sanje, ki jih nosiš že dolgo, ta teden dobijo prvi konkreten korak.",
    "Vizija, ki se ti zdi predaleč, je ta teden bliže, kot misliš.",
    "Nekaj, o čemer sanjaš ponoči, si zasluži prostor tudi podnevi.",
    "Ta teden zapiši eno sanjo na glas — besede ji dajo moč.",
    "Podoba, ki se ti ponavlja v mislih, ta teden postane jasnejša.",
    "Nekaj majhnega ta teden potrdi, da tvoja vizija ni preveč drzna.",
    "Sanje, ki se zdijo tihe, so ta teden glasnejše, kot misliš.",
    "Ta teden si dovoli sanjati brez takojšnjega načrta, kako to doseči.",
    "Nekaj, kar si zamišljaš že leta, se ta teden premakne bliže resničnosti.",
    "Prihodnost, ki si jo želiš, se ta teden začne z eno samo mislijo.",
  ],
  en: [
    "Someone is thinking about how to tell you what they feel — give them the chance to.",
    "The conversation about feelings you've been avoiding will be easier than you expect.",
    "Your heart already knows who it trusts. Listen to it before your head chimes in.",
    "Someone who thinks you've forgotten them misses you more than you realize this week.",
    "The love you're looking for elsewhere might already be standing closer than you think.",
    "An old feeling returns this week — don't push it away, just notice it.",
    "The honesty you speak today changes something you can't see yet.",
    "Someone is watching you with more fondness than you dare believe.",
    "A small act of love you do this week comes back when you least expect it.",
    "Your vulnerability is what draws someone closer this week, not what pushes them away.",
    "Your name will cross someone's mind this week — someone you haven't heard from in a while.",
    "Someone from your past is thinking about reaching out again.",
    "An unexpected message is coming from someone who genuinely loves you.",
    "Someone keeps a photo or your words without ever telling you.",
    "You're on someone's mind more often than you imagine.",
    "Someone remembers a moment this week that you'd almost forgotten yourself.",
    "A friend who hasn't written in a while is thinking right now about reaching out.",
    "Someone defends you when you're not around, without you ever finding out.",
    "Somewhere far away, someone lights a candle just for you, without knowing why.",
    "Your name comes up in a conversation you'll never hear — and it's a warm one.",
    "An opportunity that looks small carries more weight this week than it seems to.",
    "A door that's been closed for a while opens just slightly this week.",
    "Something you've been building for a long time moves one step forward this week.",
    "The money you're expecting arrives slower than you'd like, but it arrives.",
    "An offer you receive this week deserves more thought than it seems to at first.",
    "Effort no one sees gets its first quiet recognition this week.",
    "Something you've put off for a long time brings an unexpected reward this week.",
    "Ask for what you're worth — the answer is kinder than you think this week.",
    "A small investment in yourself pays off more than you expect this week.",
    "Someone offers you an opportunity this week you shouldn't turn down too quickly.",
    "One sentence you say this week will be remembered longer than you think.",
    "The conversation you're avoiding is easier than the one playing out in your head.",
    "A call you don't expect this week brings good news.",
    "The message you're waiting for is coming — just a little later than you'd like.",
    "A question you've carried for a long time gets an answer this week.",
    "A word you owe someone finally finds its way out this week.",
    "Someone listens to you more closely than you're used to this week.",
    "A conversation that seems unimportant turns something for the better this week.",
    "The truth you speak out loud eases more than you think this week.",
    "Someone is waiting for you to speak first — courage is on your side.",
    "The feeling you've had since Monday isn't a coincidence. Follow it.",
    "Your intuition speaks louder than reason this week — listen to what it's telling you.",
    "You already know something before you have proof. Trust that knowing.",
    "The inner voice you keep quieting is right more often than you admit.",
    "You'll be surprised less this week if you listen to your heart first.",
    "A recurring dream carries a message — write it down.",
    "Your first instinct is right more often this week than the doubt that follows it.",
    "Your body is telling you what it needs before your mind understands it. Listen.",
    "Something in you already knows how the story ends. Don't force the answer.",
    "The sign you're looking for has been in front of you all week — just different than you expected.",
    "The fear you're carrying this week is smaller up close than it looks from afar.",
    "A step that feels too big gets easier the moment you take it.",
    "Courage isn't the absence of fear — it's deciding to move forward anyway.",
    "Something you've been avoiding becomes much easier to face this week.",
    "One small step this week takes you further than you think you're capable of.",
    "A decision you keep delaying becomes clearer the moment you say it out loud.",
    "Ask yourself what you're really afraid of — the answer might set you free.",
    "Your strength shows up this week exactly where you didn't expect to find it.",
    "Something unfamiliar that scares you turns out less foreign once you get closer.",
    "The first step is the only one that feels hard. The rest follow on their own.",
    "You're allowed to do less this week — the world won't fall apart.",
    "The rest you keep denying yourself becomes necessary this week, not a luxury.",
    "No one will love you less if you stop and slow down this week.",
    "You don't need to earn your worth through work. You're already enough.",
    "Take one hour just for yourself this week, without any guilt.",
    "The tiredness you're hiding deserves to be acknowledged, not ignored.",
    "Let yourself say no this week, without a long explanation.",
    "The peace you're looking for outside is found in one quiet afternoon this week.",
    "You don't have to be available to everyone all the time. Your time matters too.",
    "This week is a good time for rest, not a weakness.",
    "A small surprise is waiting for you this week, right where you'd least expect it.",
    "Something unexpected interrupts your routine in a pleasant way.",
    "A gift you didn't expect comes from someone you hadn't thought of.",
    "An ordinary-seeming day hides one lovely surprise.",
    "Something small brings more joy this week than you'd expect.",
    "A chance encounter this week brings something you'll remember for a long time.",
    "The surprise coming isn't big — but it arrives exactly when you need it.",
    "Something you'd nearly forgotten makes an unexpected return this week.",
    "One moment catches you off guard this week — in a good way.",
    "Something lovely comes from someone you least expect to take care of you.",
    "The repeating numbers you notice this week aren't a coincidence. Pay attention.",
    "The universe speaks quietly this week — in a song that reaches you at just the right moment.",
    "The sign you need arrives in a form you didn't expect.",
    "Synchronicity works in your favor this week — notice the small coincidences.",
    "Something that happens to you three times in one week is not chance.",
    "The universe sends you confirmation this week — in the form of peace, not answers.",
    "A bird, a cloud, or a song that stops you carries a message meant for you.",
    "A path that opens without effort is one worth walking.",
    "Something is happening too fast for it to be a coincidence.",
    "Notice this week what keeps repeating around you — that's your sign.",
    "Something from the past settles this week without you having to do anything.",
    "The forgiveness you owe yourself matters more than the one you owe others.",
    "An old wound becomes lighter to carry this week.",
    "Someone from your past doesn't need an apology — just your own peace.",
    "A chapter you closed too quickly becomes clearer this week.",
    "Something that once hurt loses its grip on you this week.",
    "Making peace with an old version of yourself is closer than you think this week.",
    "An old memory returns so you can finally let it go, not relive it.",
    "Something you've carried too long is ready to be set down this week.",
    "The past isn't calling you back this week — it's just saying goodbye before it leaves for good.",
    "A friend you haven't seen in a while is thinking of you more than you know this week.",
    "One word of thanks to a friend means more this week than you think.",
    "A new friendship starts this week with an ordinary conversation.",
    "Someone who supports you quietly deserves to hear you say so.",
    "An old bond that seemed weaker gets a fresh chance this week.",
    "One call to a friend changes their day more than you expect this week.",
    "Someone close to you just needs you to ask how they really are.",
    "A friendship you're building slowly turns out sturdier than you think this week.",
    "Someone defends you in a conversation you don't even know about this week.",
    "Shared laughter with a friend heals more than it seems this week.",
    "An idea that feels too small deserves space on paper this week.",
    "A creative project you keep putting off becomes easier to start this week.",
    "Your imagination works faster than your doubt this week — don't stop it.",
    "A project resting in a drawer deserves a second look this week.",
    "Something you create this week has a long life ahead of it.",
    "One small creative step this week opens the door to something bigger.",
    "You don't have to wait for inspiration. It shows up this week if you start without it.",
    "Your voice, expressed in whatever way, reaches someone this week.",
    "Something you make just for yourself becomes something more this week.",
    "The creative block you've been carrying eases faster than you expect this week.",
    "Your body is telling you this week where it needs gentleness, not discipline.",
    "The energy you've been missing returns the moment you allow a slower pace.",
    "A small change to your daily rhythm brings more peace to your body this week.",
    "The tiredness you carry isn't weakness — it's a sign it's time to pause.",
    "Give five minutes this week just to breathing. Your body will thank you.",
    "Something your body has been asking for finally gets attention this week.",
    "A walk in fresh air clears more than you'd expect this week.",
    "The sleep you keep postponing becomes more urgent than it seems this week.",
    "Your body heals faster when you trust it, not when you push it.",
    "A little self-care this week has a bigger effect than you'd expect.",
    "A family member you haven't thought of in a while reaches out this week.",
    "One conversation with family this week clears up something left unspoken too long.",
    "Someone in your family just needs your presence this week, not advice.",
    "Old tension in the family starts to ease on its own this week.",
    "A childhood memory returning this week brings unexpected warmth.",
    "A word of thanks to a parent, or someone like one, means more than you think this week.",
    "Something you've long hidden from family becomes easier to share this week.",
    "A family tie that feels distant gets a chance for closeness this week.",
    "One small gesture toward home brings a lot of warmth back this week.",
    "Someone at home misses you more than they show this week.",
    "Something ends this week so something else can begin.",
    "The change you're resisting is closer than you feel ready for this week.",
    "A new beginning doesn't need a perfect plan — just a first step.",
    "Something old loses its grip on you this week.",
    "A door closing opens room for something better this week.",
    "Something that looks like a loss turns out to be space this week.",
    "The change that's coming is smaller than it looks from a distance — and easier.",
    "This week is a good moment to let go of something that no longer serves you.",
    "A new chapter starts writing itself this week, even if you can't see it yet.",
    "Something you've delayed changing for too long simply becomes necessary this week.",
    "One thing you take for granted this week deserves gratitude.",
    "Gratitude spoken out loud draws even more reasons for it this week.",
    "One small thing you notice this week changes how you see the whole day.",
    "Stop this week and count three things that bring you joy.",
    "Gratitude toward yourself matters more this week than gratitude toward others.",
    "Something you're grateful for this week pays you back.",
    "A small joy you notice this week means more than the big one you're waiting for.",
    "Give this week one minute of silence for everything you already have.",
    "Gratitude shifts your view faster than any advice.",
    "Something lovely you overlook this week deserves a second look.",
    "The thing you're rushing isn't in a hurry for the universe — and that's alright.",
    "Something you've waited too long for is closer than you think this week.",
    "The patience you're investing isn't wasted time.",
    "The answer you're waiting for is coming — just not the way you expected.",
    "This week isn't for deciding, it's for waiting with your eyes open.",
    "Something is ripening in the background, even when nothing seems to be happening.",
    "The result you're waiting for needs a little more time — but it's coming.",
    "Don't force anything this week. Let things come to you.",
    "Something slow carries more value this week than something fast.",
    "A wait that feels endless gets its first sign of an end this week.",
    "Trust your first decision this week — it's right more often than you think.",
    "Knowing what you want isn't audacity. Let yourself express it this week.",
    "The opinion you hold deserves to be said out loud.",
    "You don't need anyone else's approval this week for something you already know.",
    "Your worth doesn't depend on what you achieve this week.",
    "Don't compare your path to someone else's. Yours moves at its own pace.",
    "Something you've hidden because it felt not good enough is good enough this week.",
    "Walk into a room this week as if you already know you belong there.",
    "No one gets to define your worth but you. Remember that this week.",
    "A decision that feels risky is braver than reckless this week.",
    "A meeting that happens by chance this week isn't quite chance.",
    "Something that feels like coincidence is exactly where it needs to be this week.",
    "A path that opened without your planning is worth trusting this week.",
    "Two things crossing paths this week were meant for each other.",
    "Someone you meet purely by chance this week plays an important role for you.",
    "A moment that seems unimportant turns into a turning point this week.",
    "Nothing happens too early or too late — this week proves it.",
    "Something you've been searching for finds you on its own this week.",
    "Fate doesn't call loudly this week — it just quietly opens a door.",
    "The coincidence that happens to you this week is really an invitation.",
    "A dream you've carried for a long time takes its first concrete step this week.",
    "A vision that feels too far away is closer than you think this week.",
    "Something you dream about at night deserves room in the daylight too.",
    "Write down one dream out loud this week — words give it power.",
    "An image that keeps repeating in your mind becomes clearer this week.",
    "Something small this week confirms your vision isn't too bold.",
    "A dream that feels quiet is louder than you think this week.",
    "Let yourself dream this week without an immediate plan for how to get there.",
    "Something you imagined years ago moves closer to reality this week.",
    "The future you want starts this week with a single thought.",
  ],
};
