import type { Lang } from "./tarotData";

/**
 * AI-drafted, evergreen "excitement" lines for the weekly scratch card (not a
 * personalized reading tied to any real event). Around 200 lines in Slovenian and English,
 * 60 in the other three; the index mixes in the year (see ScratchCard.tsx), so even the
 * shorter pools land on a different line each year rather than repeating the calendar.
 */
export const SCRATCH_REWARDS: Record<Lang, string[]> = {
  sl: [
    "Nekdo razmišlja o tem, kako bi ti povedal, kaj čuti — daj mu priložnost, da to stori.",
    "Pogovor o čustvih, ki se mu izogibaš, bo lažji, kot pričakuješ.",
    "Tvoje srce že ve, komu zaupa. Poslušaj ga, preden posluša glavo.",
    "Nekdo, ki misli, da si ga že pozabil, te ta teden pogreša bolj, kot si misliš.",
    "Ljubezen, ki jo iščeš zunaj, morda že stoji bliže, kot vidiš.",
    "Star občutek se ta teden vrne — tokrat ga ne odrini, samo opazuj ga.",
    "Iskrenost, ki jo poveš danes, spremeni nekaj, česar zdaj še ne vidiš.",
    "Nekdo te opazuje z več naklonjenosti, kot si upaš verjeti.",
    "Majhna gesta ljubezni, ki jo narediš ta teden, se ti povrne, ko najmanj pričakuješ.",
    "Tvoja ranljivost je tisto, kar nekoga ta teden pritegne bližje, ne odvrne.",
    "Tvoje ime bo ta teden prišlo na misel nekomu, ki se dolgo ni oglasil.",
    "Nekdo iz preteklosti razmišlja, kako bi spet stopil v stik s tabo.",
    "Sporočilo, ki ga ne pričakuješ, prihaja od nekoga, ki te ima res rad.",
    "Nekdo hrani tvojo fotografijo ali besede, ne da bi ti to kdaj povedal.",
    "V mislih nekoga si prisoten pogosteje, kot si predstavljaš.",
    "Nekdo se ta teden spomni trenutka, ki si ga sam že skoraj pozabil.",
    "Prijatelj, ki dolgo ni pisal, razmišlja prav zdaj, kako bi ti sporočil.",
    "Nekdo te brani, ko tebe ni zraven, ne da bi to kdaj izvedel.",
    "Nekje daleč nekdo prižge svečo prav zate, ne da bi vedel zakaj.",
    "Tvoje ime pade v pogovoru, ki ga ne slišiš, a je topel.",
    "Priložnost, ki je videti majhna, ta teden nosi večjo vrednost, kot kaže.",
    "Vrata, ki so bila dolgo zaprta, se ta teden rahlo odprejo.",
    "Nekaj, kar dolgo gradiš, se ta teden premakne za korak naprej.",
    "Denar, ki ga pričakuješ, prihaja počasneje, kot upaš, a prihaja.",
    "Ponudba, ki jo ta teden prejmeš, je vredna več premisleka, kot se zdi na prvi pogled.",
    "Trud, ki ga nihče ne vidi, ta teden dobi prvo tiho priznanje.",
    "Nekaj, kar si dolgo odlašal, ta teden prinese nepričakovano nagrado.",
    "Vprašaj za tisto, kar si vreden — ta teden je odgovor bolj naklonjen, kot misliš.",
    "Majhna investicija vase se ta teden obrestuje bolj, kot pričakuješ.",
    "Nekdo ti ta teden ponudi priložnost, ki je ne smeš prehitro zavrniti.",
    "En stavek, ki ga izrečeš ta teden, si bo nekdo zapomnil dlje, kot misliš.",
    "Pogovor, ki se mu izogibaš, je lažji, kot si ga predstavljaš v glavi.",
    "Klic, ki ga ta teden ne pričakuješ, prinese dobre novice.",
    "Sporočilo, ki ga čakaš, prihaja — samo malo kasneje, kot upaš.",
    "Vprašanje, ki si ga dolgo nosiš v sebi, ta teden dobi odgovor.",
    "Beseda, ki jo dolguješ nekomu, ta teden končno najde svojo pot ven.",
    "Nekdo te ta teden posluša bolj pozorno, kot si vajen.",
    "Pogovor, ki se zdi nepomemben, ta teden obrne nekaj na bolje.",
    "Resnica, ki jo poveš na glas, ta teden olajša več, kot si misliš.",
    "Nekdo čaka, da prvi spregovoriš — pogum je na tvoji strani.",
    "Občutek, ki ga imaš od ponedeljka, ni naključje. Sledi mu.",
    "Tvoja intuicija ta teden govori jasneje kot razum — poslušaj, kaj ti pravi.",
    "Nekaj že veš, še preden dobiš dokaz. Zaupaj temu znanju.",
    "Notranji glas, ki ga utišuješ, ima prav pogosteje, kot priznaš.",
    "Ta teden te bo nekaj presenetilo manj, če prej poslušaš srce.",
    "Sanje, ki se ponavljajo, nosijo sporočilo — zapiši si jih.",
    "Prvo, kar pomisliš, je ta teden pogosteje pravilno kot dvom, ki mu sledi.",
    "Telo ti sporoča, kaj potrebuje, še preden to razume um. Prisluhni mu.",
    "Nekaj v tebi že ve, kako se bo zgodba iztekla. Ne sili odgovora.",
    "Znak, ki ga iščeš, je bil ves teden pred tabo — samo drugačen, kot pričakuješ.",
    "Strah, ki ga nosiš ta teden, je manjši, kot izgleda od blizu.",
    "Korak, ki se ti zdi prevelik, postane lažji, takoj ko ga narediš.",
    "Pogum ni odsotnost strahu — je odločitev, da greš naprej kljub njemu.",
    "Nekaj, česar se izogibaš, ta teden postane veliko lažje soočiti.",
    "Ta teden te en majhen korak pripelje dlje, kot misliš, da zmoreš.",
    "Odločitev, ki jo odlašaš, postane jasnejša, takoj ko jo izrečeš na glas.",
    "Vprašaj se, česa se v resnici bojiš — odgovor te lahko osvobodi.",
    "Tvoja moč se ta teden pokaže prav tam, kjer je najmanj pričakuješ.",
    "Nekaj neznanega, ki te straši, se izkaže za manj tuje, ko se mu približaš.",
    "Prvi korak je edini, ki se zdi težak. Ostali pridejo sami.",
    "Dovoljeno ti je ta teden narediti manj — svet se ne bo sesul.",
    "Počitek, ki si ga odrekaš, ta teden postane nujen, ne luksuz.",
    "Nihče te ne bo ljubil manj, če se ta teden ustaviš.",
    "Ni ti treba dokazovati vrednosti z delom. Že si dovolj.",
    "Ta teden si vzemi eno uro samo zase, brez občutka krivde.",
    "Utrujenost, ki jo skrivaš, si zasluži priznanje, ne ignoriranje.",
    "Dovoli si reči 'ne' ta teden, brez dolge razlage.",
    "Mir, ki ga iščeš zunaj, ta teden najdeš v enem tihem popoldnevu.",
    "Ni nujno, da si vedno na razpolago vsem. Tudi tebi pripada čas.",
    "Ta teden je za počitek prava priložnost, ne šibkost.",
    "Majhno presenečenje te ta teden čaka tam, kjer ga najmanj pričakuješ.",
    "Nekaj nepričakovanega prekine tvojo rutino na prijeten način.",
    "Darilo, ki ga ne pričakuješ, prihaja od nekoga, na katerega redko pomisliš.",
    "Dan, ki se zdi navaden, skriva eno lepo presenečenje.",
    "Nekaj majhnega ta teden razveseli bolj, kot bi pričakoval.",
    "Naključno srečanje ta teden prinese nekaj, česar se boš še dolgo spominjal.",
    "Presenečenje, ki prihaja, ni veliko — a pride ravno takrat, ko ga potrebuješ.",
    "Nekaj, kar si že skoraj pozabil, se ta teden nepričakovano vrne.",
    "En trenutek te ta teden ujame nepripravljenega — na dober način.",
    "Nekaj lepega prihaja od nekoga, ki mu najmanj zaupaš, da bo poskrbel zate.",
    "Ponavljajoča se števila, ki jih opaziš ta teden, niso naključje. Pazi nanje.",
    "Vesolje ta teden govori tiho — v pesmi, ki jo slišiš ob pravem trenutku.",
    "Znak, ki ga potrebuješ, pride v obliki, ki je ne pričakuješ.",
    "Sinhroniciteta ta teden deluje v tvoj prid — opazi majhna naključja.",
    "Nekaj, kar se ti zgodi trikrat v enem tednu, ni slučaj.",
    "Vesolje ti ta teden pošilja potrditev — v obliki miru, ne odgovora.",
    "Ptica, oblak ali pesem, ki te ustavi, nosi sporočilo zate.",
    "Pot, ki se ti odpre brez truda, je pot, po kateri je vredno iti.",
    "Nekaj se ti dogaja prehitro, da bi bilo naključje.",
    "Ta teden opazi, kaj se ponavlja okoli tebe — to je tvoj znak.",
    "Nekaj iz preteklosti se ta teden umiri samo od sebe, brez tvojega truda.",
    "Odpuščanje, ki ga dolguješ sebi, je pomembnejše od tistega, ki ga dolguješ drugim.",
    "Stara rana, ki jo nosiš, ta teden postane lažja za nositi.",
    "Nekdo iz preteklosti ne potrebuje opravičila — samo tvoj mir.",
    "Poglavje, ki si ga zaprl prehitro, se ta teden razjasni.",
    "Nekaj, kar te je nekoč bolelo, ta teden izgubi svojo moč nad tabo.",
    "Sprava s preteklo različico sebe je ta teden bližje, kot misliš.",
    "Star spomin se vrne zato, da ga končno spustiš, ne obudiš.",
    "Nekaj, kar že dolgo nosiš, je ta teden pripravljeno, da ga odložiš.",
    "Preteklost te ta teden ne kliče nazaj — samo pozdravlja, preden odide za vedno.",
    "Prijatelj, ki ga dolgo ne vidiš, ta teden misli nate bolj, kot veš.",
    "Ena beseda hvaležnosti, izrečena prijatelju, ta teden pomeni več, kot misliš.",
    "Novo prijateljstvo se ta teden začne z navadnim pogovorom.",
    "Nekdo, ki te podpira v tišini, si zasluži, da mu to poveš.",
    "Stara vez, ki se je zdela oslabljena, ta teden dobi novo priložnost.",
    "En klic prijatelju ta teden spremeni njegov dan bolj, kot pričakuješ.",
    "Nekdo v tvoji bližini potrebuje samo, da ga vprašaš, kako je res.",
    "Prijateljstvo, ki ga gradiš počasi, se ta teden izkaže za trdnejše, kot misliš.",
    "Nekdo te ta teden brani v pogovoru, za katerega niti ne veš.",
    "Skupni smeh s prijateljem ta teden zdravi več, kot se zdi.",
    "Ideja, ki se ti zdi premajhna, ta teden zasluži prostor na papirju.",
    "Nekaj ustvarjalnega, kar odlašaš, ta teden postane lažje začeti.",
    "Tvoja domišljija ta teden dela hitreje kot dvom — ne ustavljaj je.",
    "Projekt, ki počiva v predalu, si zasluži, da ga ta teden pogledaš znova.",
    "Nekaj, kar ustvariš ta teden, ima dolgo življenjsko dobo pred sabo.",
    "En majhen ustvarjalni korak ta teden odpre vrata večjemu.",
    "Ni ti treba čakati na navdih. Ta teden pride, če začneš brez njega.",
    "Tvoj glas, izražen na kakršenkoli način, ta teden nekoga dotakne.",
    "Nekaj, kar narediš samo zase, ta teden postane nekaj več.",
    "Ustvarjalna blokada, ki jo nosiš, ta teden popusti hitreje, kot pričakuješ.",
    "Telo ti ta teden sporoča, kje potrebuješ nežnost, ne discipline.",
    "Energija, ki jo pogrešaš, se vrne, takoj ko si dovoliš počasnejši tempo.",
    "Majhna sprememba v vsakdanjem ritmu ta teden prinese več miru v telo.",
    "Utrujenost, ki jo nosiš, ni šibkost — je znak, da je čas za premor.",
    "Ta teden nameni pet minut samo dihanju. Telo ti bo hvaležno.",
    "Nekaj, kar telo že dolgo prosi, ta teden končno dobi pozornost.",
    "Sprehod na svežem zraku ta teden razjasni več, kot bi pričakoval.",
    "Spanje, ki ga odlašaš, ta teden postane nujnejše, kot se zdi.",
    "Telo hitreje okreva, kadar mu zaupaš, ne kadar ga siliš.",
    "Majhna nega zase ta teden prinese večji učinek, kot pričakuješ.",
    "Družinski član, na katerega redko pomisliš, se ta teden oglasi.",
    "En pogovor z družino ta teden razčisti nekaj, kar je predolgo tiho ležalo.",
    "Nekdo v družini potrebuje ta teden samo tvojo prisotnost, ne nasvetov.",
    "Stara napetost v družini se ta teden začne umirjati sama od sebe.",
    "Otroški spomin, ki se ta teden vrne, prinese nepričakovano toplino.",
    "Beseda hvaležnosti staršem ali njim podobnim ta teden pomeni več, kot misliš.",
    "Nekaj, kar si dolgo skrival pred družino, ta teden postane lažje deliti.",
    "Družinska vez, ki se zdi oddaljena, ta teden dobi priložnost za bližino.",
    "En majhen gest do doma ta teden prinese veliko toplino nazaj.",
    "Nekdo doma te ta teden pogreša bolj, kot pokaže.",
    "Nekaj se ta teden konča, da lahko nekaj drugega začne.",
    "Sprememba, ki se ji upiraš, je ta teden bližje, kot misliš, da si pripravljen.",
    "Nov začetek ne zahteva popolnega načrta — samo prvi korak.",
    "Nekaj starega ta teden izgubi svoj prijem nate.",
    "Vrata, ki se zapirajo, ta teden odprejo prostor za nekaj boljšega.",
    "Nekaj, kar se zdi kot izguba, se ta teden izkaže za prostor.",
    "Sprememba, ki prihaja, je manjša, kot se zdi od daleč — in lažja.",
    "Ta teden je dober trenutek, da spustiš nekaj, kar te ne služi več.",
    "Novo poglavje se ta teden začne pisati, tudi če tega še ne vidiš.",
    "Nekaj, kar si dolgo odlašal spremeniti, ta teden postane preprosto nujno.",
    "Ena stvar, ki jo ta teden vzameš za samoumevno, si zasluži hvaležnost.",
    "Hvaležnost, izražena na glas, ta teden pritegne še več razlogov zanjo.",
    "Nekaj majhnega, kar ta teden opaziš, spremeni, kako gledaš na cel dan.",
    "Ta teden se ustavi in prešteje tri stvari, ki so ti v veselje.",
    "Hvaležnost do sebe je ta teden pomembnejša od hvaležnosti do drugih.",
    "Nekaj, za kar si ta teden hvaležen, se ti bo obrestovalo.",
    "Majhna radost, ki jo opaziš, ta teden pomeni več, kot velika, ki jo čakaš.",
    "Ta teden nameni minuto tišine za vse, kar že imaš.",
    "Hvaležnost spremeni pogled hitreje kot kakršenkoli nasvet.",
    "Nekaj lepega, kar ta teden spregledaš, si zasluži drugi pogled.",
    "Stvar, ki se ji mudi tebi, se ta teden ne mudi vesolju — in to je v redu.",
    "Nekaj, kar čakaš predolgo, je ta teden bližje, kot si misliš.",
    "Potrpljenje, ki ga vlagaš, ta teden ni izgubljen čas.",
    "Odgovor, ki ga čakaš, prihaja — samo ne na način, ki si ga pričakoval.",
    "Ta teden ni čas za odločitev, ampak za čakanje z odprtimi očmi.",
    "Nekaj se zori v ozadju, tudi ko se zdi, da se nič ne dogaja.",
    "Rezultat, ki ga čakaš, potrebuje še malo časa — a prihaja.",
    "Ta teden ne siliš ničesar. Naj stvari pridejo k tebi same.",
    "Nekaj počasnega ta teden nosi več vrednosti kot nekaj hitrega.",
    "Čakanje, ki se zdi neskončno, ta teden dobi prvi znak konca.",
    "Ta teden zaupaj svoji prvi odločitvi — pogosteje je prava, kot misliš.",
    "Vedeti, kaj hočeš, ni predrznost. Ta teden si to dovoli izraziti.",
    "Mnenje, ki ga imaš, si zasluži, da ga poveš na glas.",
    "Ta teden ne rabiš tuje potrditve za nekaj, kar že veš.",
    "Tvoja vrednost ni odvisna od tega, kaj ta teden dosežeš.",
    "Ne primerjaj svoje poti s tujo. Tvoja gre po svojem tempu.",
    "Nekaj, kar si dolgo skrival, ker se ti je zdelo premalo dobro, je ta teden dovolj dobro.",
    "Ta teden stopi v prostor, kot da že veš, da spadaš vanj.",
    "Nihče ne more definirati tvoje vrednosti razen tebe. Ta teden se tega spomni.",
    "Odločitev, ki se ti zdi tvegana, je ta teden bolj pogumna kot nepremišljena.",
    "Srečanje, ki se ta teden zgodi po naključju, ni čisto naključje.",
    "Nekaj, kar se ti zdi kot slučaj, je ta teden natančno tam, kjer mora biti.",
    "Pot, ki se je odprla brez tvojega načrta, je ta teden vredna zaupanja.",
    "Dve stvari, ki se ta teden prekrižata, sta bili namenjeni druga drugi.",
    "Nekdo, ki ga ta teden srečaš čisto po naključju, ima zate pomembno vlogo.",
    "Trenutek, ki se zdi nepomemben, ta teden postane obrat v zgodbi.",
    "Nič se ne zgodi prezgodaj ali prepozno — ta teden se to izkaže.",
    "Nekaj, kar iščeš že dolgo, te ta teden najde samo od sebe.",
    "Usoda ta teden ne kliče glasno — samo tiho odpre vrata.",
    "Naključje, ki se ti zgodi ta teden, je pravzaprav povabilo.",
    "Sanje, ki jih nosiš že dolgo, ta teden dobijo prvi konkreten korak.",
    "Vizija, ki se ti zdi predaleč, je ta teden bliže, kot misliš.",
    "Nekaj, o čemer sanjaš ponoči, si zasluži prostor tudi podnevi.",
    "Ta teden zapiši eno sanjo na glas — besede ji dajo moč.",
    "Podoba, ki se ti ponavlja v mislih, ta teden postane jasnejša.",
    "Nekaj majhnega ta teden potrdi, da tvoja vizija ni preveč drzna.",
    "Sanje, ki se zdijo tihe, so ta teden glasnejše, kot misliš.",
    "Ta teden si dovoli sanjati brez takojšnjega načrta, kako to doseči.",
    "Nekaj, kar si zamišljaš že leta, se ta teden premakne bliže resničnosti.",
    "Prihodnost, ki si jo želiš, se ta teden začne z eno samo mislijo.",
  ],
  en: [
    "Someone is thinking about how to tell you what they feel — give them the chance to.",
    "The conversation about feelings you've been avoiding will be easier than you expect.",
    "Your heart already knows who it trusts. Listen to it before your head chimes in.",
    "Someone who thinks you've forgotten them misses you more than you realize this week.",
    "The love you're looking for elsewhere might already be standing closer than you think.",
    "An old feeling returns this week — don't push it away, just notice it.",
    "The honesty you speak today changes something you can't see yet.",
    "Someone is watching you with more fondness than you dare believe.",
    "A small act of love you do this week comes back when you least expect it.",
    "Your vulnerability is what draws someone closer this week, not what pushes them away.",
    "Your name will cross someone's mind this week — someone you haven't heard from in a while.",
    "Someone from your past is thinking about reaching out again.",
    "An unexpected message is coming from someone who genuinely loves you.",
    "Someone keeps a photo or your words without ever telling you.",
    "You're on someone's mind more often than you imagine.",
    "Someone remembers a moment this week that you'd almost forgotten yourself.",
    "A friend who hasn't written in a while is thinking right now about reaching out.",
    "Someone defends you when you're not around, without you ever finding out.",
    "Somewhere far away, someone lights a candle just for you, without knowing why.",
    "Your name comes up in a conversation you'll never hear — and it's a warm one.",
    "An opportunity that looks small carries more weight this week than it seems to.",
    "A door that's been closed for a while opens just slightly this week.",
    "Something you've been building for a long time moves one step forward this week.",
    "The money you're expecting arrives slower than you'd like, but it arrives.",
    "An offer you receive this week deserves more thought than it seems to at first.",
    "Effort no one sees gets its first quiet recognition this week.",
    "Something you've put off for a long time brings an unexpected reward this week.",
    "Ask for what you're worth — the answer is kinder than you think this week.",
    "A small investment in yourself pays off more than you expect this week.",
    "Someone offers you an opportunity this week you shouldn't turn down too quickly.",
    "One sentence you say this week will be remembered longer than you think.",
    "The conversation you're avoiding is easier than the one playing out in your head.",
    "A call you don't expect this week brings good news.",
    "The message you're waiting for is coming — just a little later than you'd like.",
    "A question you've carried for a long time gets an answer this week.",
    "A word you owe someone finally finds its way out this week.",
    "Someone listens to you more closely than you're used to this week.",
    "A conversation that seems unimportant turns something for the better this week.",
    "The truth you speak out loud eases more than you think this week.",
    "Someone is waiting for you to speak first — courage is on your side.",
    "The feeling you've had since Monday isn't a coincidence. Follow it.",
    "Your intuition speaks louder than reason this week — listen to what it's telling you.",
    "You already know something before you have proof. Trust that knowing.",
    "The inner voice you keep quieting is right more often than you admit.",
    "You'll be surprised less this week if you listen to your heart first.",
    "A recurring dream carries a message — write it down.",
    "Your first instinct is right more often this week than the doubt that follows it.",
    "Your body is telling you what it needs before your mind understands it. Listen.",
    "Something in you already knows how the story ends. Don't force the answer.",
    "The sign you're looking for has been in front of you all week — just different than you expected.",
    "The fear you're carrying this week is smaller up close than it looks from afar.",
    "A step that feels too big gets easier the moment you take it.",
    "Courage isn't the absence of fear — it's deciding to move forward anyway.",
    "Something you've been avoiding becomes much easier to face this week.",
    "One small step this week takes you further than you think you're capable of.",
    "A decision you keep delaying becomes clearer the moment you say it out loud.",
    "Ask yourself what you're really afraid of — the answer might set you free.",
    "Your strength shows up this week exactly where you didn't expect to find it.",
    "Something unfamiliar that scares you turns out less foreign once you get closer.",
    "The first step is the only one that feels hard. The rest follow on their own.",
    "You're allowed to do less this week — the world won't fall apart.",
    "The rest you keep denying yourself becomes necessary this week, not a luxury.",
    "No one will love you less if you stop and slow down this week.",
    "You don't need to earn your worth through work. You're already enough.",
    "Take one hour just for yourself this week, without any guilt.",
    "The tiredness you're hiding deserves to be acknowledged, not ignored.",
    "Let yourself say no this week, without a long explanation.",
    "The peace you're looking for outside is found in one quiet afternoon this week.",
    "You don't have to be available to everyone all the time. Your time matters too.",
    "This week is a good time for rest, not a weakness.",
    "A small surprise is waiting for you this week, right where you'd least expect it.",
    "Something unexpected interrupts your routine in a pleasant way.",
    "A gift you didn't expect comes from someone you hadn't thought of.",
    "An ordinary-seeming day hides one lovely surprise.",
    "Something small brings more joy this week than you'd expect.",
    "A chance encounter this week brings something you'll remember for a long time.",
    "The surprise coming isn't big — but it arrives exactly when you need it.",
    "Something you'd nearly forgotten makes an unexpected return this week.",
    "One moment catches you off guard this week — in a good way.",
    "Something lovely comes from someone you least expect to take care of you.",
    "The repeating numbers you notice this week aren't a coincidence. Pay attention.",
    "The universe speaks quietly this week — in a song that reaches you at just the right moment.",
    "The sign you need arrives in a form you didn't expect.",
    "Synchronicity works in your favor this week — notice the small coincidences.",
    "Something that happens to you three times in one week is not chance.",
    "The universe sends you confirmation this week — in the form of peace, not answers.",
    "A bird, a cloud, or a song that stops you carries a message meant for you.",
    "A path that opens without effort is one worth walking.",
    "Something is happening too fast for it to be a coincidence.",
    "Notice this week what keeps repeating around you — that's your sign.",
    "Something from the past settles this week without you having to do anything.",
    "The forgiveness you owe yourself matters more than the one you owe others.",
    "An old wound becomes lighter to carry this week.",
    "Someone from your past doesn't need an apology — just your own peace.",
    "A chapter you closed too quickly becomes clearer this week.",
    "Something that once hurt loses its grip on you this week.",
    "Making peace with an old version of yourself is closer than you think this week.",
    "An old memory returns so you can finally let it go, not relive it.",
    "Something you've carried too long is ready to be set down this week.",
    "The past isn't calling you back this week — it's just saying goodbye before it leaves for good.",
    "A friend you haven't seen in a while is thinking of you more than you know this week.",
    "One word of thanks to a friend means more this week than you think.",
    "A new friendship starts this week with an ordinary conversation.",
    "Someone who supports you quietly deserves to hear you say so.",
    "An old bond that seemed weaker gets a fresh chance this week.",
    "One call to a friend changes their day more than you expect this week.",
    "Someone close to you just needs you to ask how they really are.",
    "A friendship you're building slowly turns out sturdier than you think this week.",
    "Someone defends you in a conversation you don't even know about this week.",
    "Shared laughter with a friend heals more than it seems this week.",
    "An idea that feels too small deserves space on paper this week.",
    "A creative project you keep putting off becomes easier to start this week.",
    "Your imagination works faster than your doubt this week — don't stop it.",
    "A project resting in a drawer deserves a second look this week.",
    "Something you create this week has a long life ahead of it.",
    "One small creative step this week opens the door to something bigger.",
    "You don't have to wait for inspiration. It shows up this week if you start without it.",
    "Your voice, expressed in whatever way, reaches someone this week.",
    "Something you make just for yourself becomes something more this week.",
    "The creative block you've been carrying eases faster than you expect this week.",
    "Your body is telling you this week where it needs gentleness, not discipline.",
    "The energy you've been missing returns the moment you allow a slower pace.",
    "A small change to your daily rhythm brings more peace to your body this week.",
    "The tiredness you carry isn't weakness — it's a sign it's time to pause.",
    "Give five minutes this week just to breathing. Your body will thank you.",
    "Something your body has been asking for finally gets attention this week.",
    "A walk in fresh air clears more than you'd expect this week.",
    "The sleep you keep postponing becomes more urgent than it seems this week.",
    "Your body heals faster when you trust it, not when you push it.",
    "A little self-care this week has a bigger effect than you'd expect.",
    "A family member you haven't thought of in a while reaches out this week.",
    "One conversation with family this week clears up something left unspoken too long.",
    "Someone in your family just needs your presence this week, not advice.",
    "Old tension in the family starts to ease on its own this week.",
    "A childhood memory returning this week brings unexpected warmth.",
    "A word of thanks to a parent, or someone like one, means more than you think this week.",
    "Something you've long hidden from family becomes easier to share this week.",
    "A family tie that feels distant gets a chance for closeness this week.",
    "One small gesture toward home brings a lot of warmth back this week.",
    "Someone at home misses you more than they show this week.",
    "Something ends this week so something else can begin.",
    "The change you're resisting is closer than you feel ready for this week.",
    "A new beginning doesn't need a perfect plan — just a first step.",
    "Something old loses its grip on you this week.",
    "A door closing opens room for something better this week.",
    "Something that looks like a loss turns out to be space this week.",
    "The change that's coming is smaller than it looks from a distance — and easier.",
    "This week is a good moment to let go of something that no longer serves you.",
    "A new chapter starts writing itself this week, even if you can't see it yet.",
    "Something you've delayed changing for too long simply becomes necessary this week.",
    "One thing you take for granted this week deserves gratitude.",
    "Gratitude spoken out loud draws even more reasons for it this week.",
    "One small thing you notice this week changes how you see the whole day.",
    "Stop this week and count three things that bring you joy.",
    "Gratitude toward yourself matters more this week than gratitude toward others.",
    "Something you're grateful for this week pays you back.",
    "A small joy you notice this week means more than the big one you're waiting for.",
    "Give this week one minute of silence for everything you already have.",
    "Gratitude shifts your view faster than any advice.",
    "Something lovely you overlook this week deserves a second look.",
    "The thing you're rushing isn't in a hurry for the universe — and that's alright.",
    "Something you've waited too long for is closer than you think this week.",
    "The patience you're investing isn't wasted time.",
    "The answer you're waiting for is coming — just not the way you expected.",
    "This week isn't for deciding, it's for waiting with your eyes open.",
    "Something is ripening in the background, even when nothing seems to be happening.",
    "The result you're waiting for needs a little more time — but it's coming.",
    "Don't force anything this week. Let things come to you.",
    "Something slow carries more value this week than something fast.",
    "A wait that feels endless gets its first sign of an end this week.",
    "Trust your first decision this week — it's right more often than you think.",
    "Knowing what you want isn't audacity. Let yourself express it this week.",
    "The opinion you hold deserves to be said out loud.",
    "You don't need anyone else's approval this week for something you already know.",
    "Your worth doesn't depend on what you achieve this week.",
    "Don't compare your path to someone else's. Yours moves at its own pace.",
    "Something you've hidden because it felt not good enough is good enough this week.",
    "Walk into a room this week as if you already know you belong there.",
    "No one gets to define your worth but you. Remember that this week.",
    "A decision that feels risky is braver than reckless this week.",
    "A meeting that happens by chance this week isn't quite chance.",
    "Something that feels like coincidence is exactly where it needs to be this week.",
    "A path that opened without your planning is worth trusting this week.",
    "Two things crossing paths this week were meant for each other.",
    "Someone you meet purely by chance this week plays an important role for you.",
    "A moment that seems unimportant turns into a turning point this week.",
    "Nothing happens too early or too late — this week proves it.",
    "Something you've been searching for finds you on its own this week.",
    "Fate doesn't call loudly this week — it just quietly opens a door.",
    "The coincidence that happens to you this week is really an invitation.",
    "A dream you've carried for a long time takes its first concrete step this week.",
    "A vision that feels too far away is closer than you think this week.",
    "Something you dream about at night deserves room in the daylight too.",
    "Write down one dream out loud this week — words give it power.",
    "An image that keeps repeating in your mind becomes clearer this week.",
    "Something small this week confirms your vision isn't too bold.",
    "A dream that feels quiet is louder than you think this week.",
    "Let yourself dream this week without an immediate plan for how to get there.",
    "Something you imagined years ago moves closer to reality this week.",
    "The future you want starts this week with a single thought.",
  ],
  hr: [
    "Netko razmišlja kako bi ti rekao što osjeća — daj mu priliku da to učini.",
    "Razgovor o osjećajima koji izbjegavaš bit će lakši nego što očekuješ.",
    "Tvoje srce već zna kome vjeruje. Poslušaj ga prije nego se javi glava.",
    "Netko tko misli da si ga zaboravio ovog te tjedna želi više nego što slutiš.",
    "Ljubav koju tražiš vani možda stoji bliže nego što vidiš.",
    "Stari se osjećaj ovog tjedna vraća — ovaj put ga nemoj odgurnuti, samo ga promatraj.",
    "Iskrenost koju izgovoriš danas mijenja nešto što još ne vidiš.",
    "Netko te gleda s više naklonosti nego što se usuđuješ vjerovati.",
    "Mala gesta ljubavi koju napraviš ovog tjedna vraća ti se kad najmanje očekuješ.",
    "Tvoja je ranjivost ono što ovog tjedna nekoga privlači bliže, a ne odbija.",
    "Tvoje će ime ovog tjedna pasti na pamet nekome tko se dugo nije javio.",
    "Netko iz prošlosti razmišlja kako bi opet stupio u kontakt s tobom.",
    "Poruka koju ne očekuješ stiže od nekoga tko te stvarno voli.",
    "Netko čuva tvoju fotografiju ili tvoje riječi, a da ti to nikad nije rekao.",
    "U tuđim si mislima češće nego što zamišljaš.",
    "Netko se ovog tjedna sjeti trenutka koji si ti gotovo zaboravio.",
    "Prijatelj koji se dugo nije javio upravo sada smišlja kako da ti piše.",
    "Netko te brani kad te nema, a da to nikad nećeš saznati.",
    "Negdje daleko netko pali svijeću baš za tebe, ne znajući zašto.",
    "Tvoje ime pada u razgovoru koji ne čuješ, ali je topao.",
    "Prilika koja izgleda mala ovog tjedna nosi veću vrijednost nego što se čini.",
    "Vrata koja su dugo bila zatvorena ovog se tjedna lagano otvaraju.",
    "Nešto što dugo gradiš ovog se tjedna pomiče korak naprijed.",
    "Novac koji očekuješ stiže sporije nego što se nadaš, ali stiže.",
    "Ponuda koju ovog tjedna dobiješ vrijedi više promišljanja nego na prvi pogled.",
    "Trud koji nitko ne vidi ovog tjedna dobiva prvo tiho priznanje.",
    "Nešto što si dugo odgađao ovog tjedna donosi neočekivanu nagradu.",
    "Traži ono što vrijediš — ovog je tjedna odgovor blagonakloniji nego što misliš.",
    "Malo ulaganje u sebe ovog se tjedna isplati više nego što očekuješ.",
    "Netko ti ovog tjedna nudi priliku koju ne smiješ prebrzo odbiti.",
    "Jednu rečenicu koju izgovoriš ovog tjedna netko će pamtiti dulje nego što misliš.",
    "Razgovor koji izbjegavaš lakši je nego što ga zamišljaš u glavi.",
    "Poziv koji ovog tjedna ne očekuješ donosi dobre vijesti.",
    "Poruka koju čekaš stiže — samo malo kasnije nego što se nadaš.",
    "Pitanje koje dugo nosiš u sebi ovog tjedna dobiva odgovor.",
    "Riječ koju nekome duguješ ovog tjedna napokon nalazi svoj put van.",
    "Netko te ovog tjedna sluša pažljivije nego što si navikao.",
    "Razgovor koji se čini nevažnim ovog tjedna okreće nešto nabolje.",
    "Istina koju izgovoriš naglas ovog tjedna olakšava više nego što misliš.",
    "Netko čeka da ti progovoriš prvi — hrabrost je na tvojoj strani.",
    "Umor koji nosiš ovog tjedna nije lijenost. To je znak da si dugo davao previše.",
    "Tijelo ti ovog tjedna govori nešto što glava odbija čuti. Poslušaj ga.",
    "Odmor koji si sebi uskraćuješ ovog tjedna vrijedi više od još jednog dovršenog zadatka.",
    "Nešto što si mislio da si prerastao ovog se tjedna vraća po zadnji pozdrav.",
    "Oprost koji ovog tjedna daš sebi otvara više nego bilo koji tuđi.",
    "Granica koju ovog tjedna postaviš nikoga neće izgubiti — samo će stvari razjasniti.",
    "Ovog je tjedna dobro reći ne bez objašnjavanja zašto.",
    "Nešto malo i lijepo ovog tjedna zaslužuje da mu posvetiš cijelu minutu.",
    "Tišina koju si ovog tjedna priuštiš vrijedi više od svakog savjeta.",
    "Ovog tjedna nemoj popravljati ono što samo treba biti primijećeno.",
    "Strah koji nosiš ovog je tjedna manji nego što je bio prošle godine. Provjeri.",
    "Nešto na čemu si odustao vrijedi jednog posljednjeg pokušaja — ali tek sljedeći tjedan.",
    "Slika koja ti se ponavlja u mislima ovog tjedna postaje jasnija.",
    "Nešto malo ovog tjedna potvrđuje da tvoja vizija nije prehrabra.",
    "Snovi koji se čine tihima ovog su tjedna glasniji nego što misliš.",
    "Ovog si tjedna dopusti sanjati bez odmah spremnog plana kako to postići.",
    "Nešto što zamišljaš godinama ovog se tjedna primiče stvarnosti.",
    "Budućnost koju želiš počinje ovog tjedna jednom jedinom mišlju.",
    "Odluka koju odgađaš ovog tjedna postaje lakša nego prošlog mjeseca.",
    "Ono što te ovog tjedna smeta zapravo ti pokazuje što ti je važno.",
  ],
  de: [
    "Jemand überlegt, wie er dir sagen soll, was er fühlt — gib ihm die Gelegenheit.",
    "Das Gespräch über Gefühle, dem du ausweichst, wird leichter, als du denkst.",
    "Dein Herz weiß längst, wem es vertraut. Hör ihm zu, bevor der Kopf sich meldet.",
    "Jemand, der glaubt, du hättest ihn vergessen, vermisst dich diese Woche mehr, als du ahnst.",
    "Die Liebe, die du draußen suchst, steht vielleicht näher, als du siehst.",
    "Ein altes Gefühl kommt diese Woche zurück — schieb es diesmal nicht weg, schau es dir an.",
    "Die Ehrlichkeit, die du heute aussprichst, verändert etwas, das du noch nicht siehst.",
    "Jemand sieht dich mit mehr Zuneigung an, als du zu glauben wagst.",
    "Eine kleine Geste der Liebe diese Woche kommt zurück, wenn du es am wenigsten erwartest.",
    "Deine Verletzlichkeit zieht diese Woche jemanden näher, statt ihn wegzustoßen.",
    "Dein Name fällt diese Woche jemandem ein, der sich lange nicht gemeldet hat.",
    "Jemand aus der Vergangenheit überlegt, wieder Kontakt zu dir aufzunehmen.",
    "Eine Nachricht, die du nicht erwartest, kommt von jemandem, der dich wirklich mag.",
    "Jemand bewahrt ein Foto von dir oder deine Worte auf, ohne es dir je gesagt zu haben.",
    "Du bist in den Gedanken anderer häufiger, als du dir vorstellst.",
    "Jemand erinnert sich diese Woche an einen Moment, den du fast vergessen hast.",
    "Ein Freund, der lange nicht geschrieben hat, überlegt gerade jetzt, wie er dich erreicht.",
    "Jemand verteidigt dich, wenn du nicht dabei bist, und du wirst es nie erfahren.",
    "Irgendwo weit weg zündet jemand eine Kerze für dich an, ohne zu wissen warum.",
    "Dein Name fällt in einem Gespräch, das du nicht hörst, aber es ist ein warmes.",
    "Eine Gelegenheit, die klein aussieht, trägt diese Woche mehr Wert, als sie zeigt.",
    "Eine Tür, die lange zu war, öffnet sich diese Woche einen Spalt.",
    "Etwas, woran du lange baust, rückt diese Woche einen Schritt weiter.",
    "Das Geld, das du erwartest, kommt langsamer, als du hoffst, aber es kommt.",
    "Ein Angebot dieser Woche verdient mehr Überlegung, als es auf den ersten Blick scheint.",
    "Mühe, die niemand sieht, bekommt diese Woche ihre erste stille Anerkennung.",
    "Etwas, das du lange aufgeschoben hast, bringt diese Woche eine unerwartete Belohnung.",
    "Frag nach dem, was du wert bist — diese Woche fällt die Antwort freundlicher aus, als du denkst.",
    "Eine kleine Investition in dich selbst zahlt sich diese Woche mehr aus als erwartet.",
    "Jemand bietet dir diese Woche eine Gelegenheit, die du nicht zu schnell ablehnen solltest.",
    "Einen Satz, den du diese Woche sagst, wird sich jemand länger merken, als du denkst.",
    "Das Gespräch, dem du ausweichst, ist leichter als das, was du dir im Kopf ausmalst.",
    "Ein Anruf, den du diese Woche nicht erwartest, bringt gute Nachrichten.",
    "Die Nachricht, auf die du wartest, kommt — nur etwas später, als du hoffst.",
    "Eine Frage, die du lange mit dir trägst, bekommt diese Woche eine Antwort.",
    "Ein Wort, das du jemandem schuldest, findet diese Woche endlich hinaus.",
    "Jemand hört dir diese Woche aufmerksamer zu, als du es gewohnt bist.",
    "Ein Gespräch, das unwichtig scheint, wendet diese Woche etwas zum Guten.",
    "Eine Wahrheit, die du laut aussprichst, erleichtert diese Woche mehr, als du denkst.",
    "Jemand wartet darauf, dass du zuerst sprichst — der Mut liegt bei dir.",
    "Die Müdigkeit, die du trägst, ist diese Woche keine Faulheit. Sie zeigt, dass du lange zu viel gegeben hast.",
    "Dein Körper sagt dir diese Woche etwas, das dein Kopf nicht hören will. Hör hin.",
    "Die Ruhe, die du dir verweigerst, ist diese Woche mehr wert als eine weitere erledigte Aufgabe.",
    "Etwas, das du überwunden glaubtest, kommt diese Woche für einen letzten Gruß zurück.",
    "Die Vergebung, die du dir diese Woche schenkst, öffnet mehr als jede fremde.",
    "Eine Grenze, die du diese Woche ziehst, verliert dir niemanden — sie schafft nur Klarheit.",
    "Diese Woche darfst du Nein sagen, ohne zu erklären, warum.",
    "Etwas Kleines und Schönes verdient diese Woche eine ganze Minute deiner Aufmerksamkeit.",
    "Die Stille, die du dir diese Woche gönnst, ist mehr wert als jeder Ratschlag.",
    "Reparier diese Woche nicht, was nur bemerkt werden will.",
    "Die Angst, die du trägst, ist diese Woche kleiner als letztes Jahr. Prüf es nach.",
    "Etwas, das du aufgegeben hast, verdient einen letzten Versuch — aber erst nächste Woche.",
    "Ein Bild, das dir immer wieder durch den Kopf geht, wird diese Woche klarer.",
    "Etwas Kleines bestätigt diese Woche, dass deine Vorstellung nicht zu kühn ist.",
    "Träume, die still wirken, sind diese Woche lauter, als du denkst.",
    "Erlaub dir diese Woche zu träumen, ohne gleich einen Plan dafür zu haben.",
    "Etwas, das du dir seit Jahren vorstellst, rückt diese Woche näher an die Wirklichkeit.",
    "Die Zukunft, die du willst, beginnt diese Woche mit einem einzigen Gedanken.",
    "Die Entscheidung, die du aufschiebst, fällt diese Woche leichter als im letzten Monat.",
    "Was dich diese Woche stört, zeigt dir eigentlich, was dir wichtig ist.",
  ],
  it: [
    "Qualcuno sta pensando a come dirti ciò che prova — dagli l'occasione di farlo.",
    "La conversazione sui sentimenti che stai evitando sarà più facile di quanto credi.",
    "Il tuo cuore sa già di chi si fida. Ascoltalo prima che intervenga la testa.",
    "Qualcuno che pensa di essere stato dimenticato questa settimana ti cerca più di quanto immagini.",
    "L'amore che cerchi fuori forse è più vicino di quanto vedi.",
    "Un vecchio sentimento torna questa settimana — stavolta non scacciarlo, guardalo soltanto.",
    "La sincerità che dici oggi cambia qualcosa che ancora non vedi.",
    "Qualcuno ti guarda con più affetto di quanto tu osi credere.",
    "Un piccolo gesto d'amore di questa settimana ti torna quando meno te lo aspetti.",
    "La tua vulnerabilità questa settimana avvicina qualcuno, non lo allontana.",
    "Il tuo nome verrà in mente questa settimana a qualcuno che non si fa sentire da tempo.",
    "Qualcuno dal passato sta pensando a come rimettersi in contatto con te.",
    "Un messaggio che non aspetti arriva da qualcuno che ti vuole davvero bene.",
    "Qualcuno conserva una tua foto o le tue parole senza avertelo mai detto.",
    "Sei nei pensieri di qualcuno più spesso di quanto immagini.",
    "Questa settimana qualcuno ricorda un momento che tu avevi quasi dimenticato.",
    "Un amico che non scrive da tempo sta pensando proprio ora a come raggiungerti.",
    "Qualcuno ti difende quando non ci sei, e non lo saprai mai.",
    "Da qualche parte lontano qualcuno accende una candela proprio per te, senza sapere perché.",
    "Il tuo nome cade in una conversazione che non senti, ma è calda.",
    "Un'occasione che sembra piccola questa settimana vale più di quanto mostri.",
    "Una porta chiusa da tempo questa settimana si socchiude.",
    "Qualcosa che costruisci da tempo questa settimana avanza di un passo.",
    "Il denaro che aspetti arriva più lentamente di quanto speri, ma arriva.",
    "Una proposta di questa settimana merita più riflessione di quanto sembri a prima vista.",
    "Un impegno che nessuno vede riceve questa settimana il suo primo riconoscimento silenzioso.",
    "Qualcosa che rimandi da tempo porta questa settimana una ricompensa inattesa.",
    "Chiedi ciò che vali — questa settimana la risposta è più benevola di quanto pensi.",
    "Un piccolo investimento su di te rende questa settimana più del previsto.",
    "Questa settimana qualcuno ti offre un'occasione da non rifiutare troppo in fretta.",
    "Una frase che dirai questa settimana qualcuno la ricorderà più a lungo di quanto credi.",
    "La conversazione che eviti è più semplice di come te la immagini in testa.",
    "Una telefonata che non aspetti questa settimana porta buone notizie.",
    "Il messaggio che attendi arriva — solo un po' più tardi di quanto speri.",
    "Una domanda che porti dentro da tempo trova risposta questa settimana.",
    "Una parola che devi a qualcuno questa settimana trova finalmente la sua strada.",
    "Questa settimana qualcuno ti ascolta con più attenzione di quanto sei abituato.",
    "Una conversazione che sembra irrilevante questa settimana gira qualcosa in meglio.",
    "Una verità detta ad alta voce questa settimana alleggerisce più di quanto pensi.",
    "Qualcuno aspetta che sia tu a parlare per primo — il coraggio sta dalla tua parte.",
    "La stanchezza che porti questa settimana non è pigrizia. È il segno che hai dato troppo a lungo.",
    "Il corpo questa settimana ti dice qualcosa che la testa non vuole sentire. Ascoltalo.",
    "Il riposo che ti neghi vale questa settimana più di un altro compito finito.",
    "Qualcosa che credevi superato torna questa settimana per un ultimo saluto.",
    "Il perdono che dai a te stesso questa settimana apre più di qualsiasi altro.",
    "Un confine che poni questa settimana non ti farà perdere nessuno — chiarisce soltanto.",
    "Questa settimana va benissimo dire no senza spiegare perché.",
    "Qualcosa di piccolo e bello questa settimana merita un minuto intero della tua attenzione.",
    "Il silenzio che ti concedi questa settimana vale più di qualunque consiglio.",
    "Questa settimana non riparare ciò che chiede solo di essere notato.",
    "La paura che porti questa settimana è più piccola dell'anno scorso. Verificalo.",
    "Qualcosa a cui hai rinunciato merita un ultimo tentativo — ma solo la prossima settimana.",
    "Un'immagine che ti torna in mente questa settimana diventa più nitida.",
    "Qualcosa di piccolo questa settimana conferma che la tua visione non è troppo audace.",
    "I sogni che sembrano silenziosi questa settimana sono più forti di quanto credi.",
    "Questa settimana concediti di sognare senza un piano immediato su come arrivarci.",
    "Qualcosa che immagini da anni questa settimana si avvicina alla realtà.",
    "Il futuro che desideri comincia questa settimana con un solo pensiero.",
    "La decisione che rimandi questa settimana è più leggera del mese scorso.",
    "Ciò che ti infastidisce questa settimana ti sta mostrando cosa ti sta a cuore.",
  ],
};
