import type { CardText } from "./tarotData";

/**
 * Croatian text for the 22 Major Arcana. Same readings as the Slovenian and English in
 * tarotData.ts — same four paragraphs, same images — written out in Croatian rather than
 * transliterated from the Slovenian. Mine, not a translator's.
 */
export const TAROT_HR: Record<string, CardText> = {
  fool: {
    name: "Luda",
    keywords: ["Novi početak", "Povjerenje", "Skok"],
    meaning: "Rub litice nije znak da staneš. Znak je da je vrijeme za prvi korak.",
    profile:
      "Luda stoji na rubu, s malim zavežljajem preko ramena i psom kraj nogu koji vjerno upozorava — no ona gleda gore, ne dolje. Put još ne poznaje, i upravo je to oslobađa. Svaka cesta kojom je itko ikada hodao počela je s nekim tko nije znao kamo vodi. Njezin zavežljaj nosi samo ono najnužnije — sve ostalo spremna je pronaći usput ili naučiti živjeti bez toga.\n\nOva karta ne govori o gluposti, nego o hrabrosti koju ima samo onaj koga iskustvo još nije ranilo. Kad se pojavi, poziva te da zakoračiš u nepoznato bez cijelog plana — da vjeruješ da će se odgovori pokazati na putu. Nije vrijeme za opreznost. Vrijeme je za skok.\n\nSjena Lude je nepromišljenost bez svijesti o posljedicama — skok koji napraviš a da uopće nisi pogledao kamo padaš. Razlika između hrabrosti i lakomislenosti nije u samom činu, nego u tome jesi li spreman prihvatiti ono što dolazi, čak i ako nije ono što si zamišljao. Luda ne obećava siguran doskok. Obećava samo da će te sam put nečemu naučiti.\n\nU odnosima Luda donosi svježinu ondje gdje je sve počelo djelovati poznato — novo poznanstvo, neočekivani početak, spremnost da voliš bez osiguranja od gubitka. Na poslu najavljuje projekt ili ideju koja svima uokolo izgleda riskantno, a tebi se u dubini čini ispravnom. Kad ova karta padne u tvoje čitanje, ne pitaj se jesi li dovoljno spreman. Nitko na rubu litice nikad nije posve spreman. Zakorači.",
  },
  magician: {
    name: "Mag",
    keywords: ["Volja", "Stvaranje", "Imaš sve alate"],
    meaning: "Sve što ti treba već je pred tobom na stolu. Pitanje je hoćeš li posegnuti za tim.",
    profile:
      "Mag stoji za stolom na kojem leže sva četiri alata — pehar, mač, štap, pentagram — osjećaj, misao, djelo, tijelo. Jedna ruka pokazuje prema nebu, druga prema zemlji: povezuje ideju sa stvarnošću. Ništa ovdje ne čeka slučaj. Zna uzeti ono što već ima i od toga napraviti nešto novo. Iznad glave mu lebdi znak beskonačnosti — podsjetnik da izvor iz kojeg stvara nije ograničen, sve dok se zna na njega spojiti.\n\nKad se ova karta pojavi, poručuje da već imaš svaku vještinu koju ovaj zadatak traži — pitanje nije sposobnost, nego namjera. Usmjeri volju na jednu stvar umjesto da je raspršiš na deset. Svijet se neće pomaknuti sam. Ali ti se možeš pomaknuti u njega, upravo sada.\n\nSjena Maga je manipulacija — vještina upotrijebljena da druge uvjeri u nešto što nije istina, umjesto da stvori nešto što stoji samo po sebi. Prava snaga ove karte nije u trikovima, nego u usklađenosti onoga što misliš, govoriš i činiš. Kad se to troje poravna, stvari se pomiču gotovo bez napora. Kad se ne poravna, ostaje samo predstava.\n\nU odnosima Mag znači inicijativu — priliku da kažeš što osjećaš umjesto da čekaš da netko drugi napravi prvi korak. Na poslu najavljuje projekt u kojem zaista možeš iskoristiti sve svoje vještine odjednom, a ne samo jednu. Vjeruj svojoj sposobnosti da od raspršenih komadića složiš nešto cjelovito. Sve što ti treba već je na stolu pred tobom.",
  },
  "high-priestess": {
    name: "Velika svećenica",
    keywords: ["Intuicija", "Tajna", "Unutarnje znanje"],
    meaning: "Odgovor koji tražiš izvana već šapće u tebi. Utihni dovoljno dugo da ga čuješ.",
    profile:
      "Velika svećenica sjedi između dva stupa, jednog crnog i jednog bijelog, sjene i svjetla, i ne bira nijedan — ostaje između, ondje gdje se tajna tek oblikuje. Iza nje visi tanki veo; ne zabranjuje ti pogled, samo traži da budeš spreman vidjeti. Njezino znanje nije u knjigama. U tišini je. U krilu drži svitak na kojem piše samo djelomično vidljiva riječ — podsjetnik da nije svako znanje namijenjeno trenutačnom razumijevanju.\n\nKad se pojavi, ova te karta poziva da vjeruješ onome što još ne možeš objasniti razumom. Nešto već znaš prije nego dobiješ dokaz. Nije ovo vrijeme za glasne odluke ili brzo djelovanje — vrijeme je za slušanje. Snovi, slutnje, tjelesni osjeti: sve je to jezik vrijedan razumijevanja.\n\nSjena ove karte je povlačenje u sebe do te mjere da izgubiš dodir sa svijetom oko sebe — tajna koja postaje samoća umjesto unutarnjeg izvora snage. Velika svećenica ne bježi od svijeta. Samo zna da se neki odgovori ne nalaze u buci, nego u prostoru koji sam sebi izgradiš, podalje od tuđih očekivanja.\n\nU odnosima ova karta govori o nečemu što još nije izrečeno naglas — osjećaju koji naslućuješ, ali ga još ne znaš staviti u riječi, ili tajni koju netko drugi nosi. Na poslu upozorava da ne forsiraš odluku prije nego dobiješ cijelu sliku. Vjeruj tišini prije odgovora više nego pritisku da nešto moraš reći odmah. Prava jasnoća dolazi onome tko je zna pričekati.",
  },
  empress: {
    name: "Carica",
    keywords: ["Obilje", "Kreativnost", "Njega"],
    meaning: "Ono što se njeguje, raste. To vrijedi za polja jednako kao za ljude.",
    profile:
      "Carica sjedi usred bujnog polja, pšenica zrije oko nje, rijeka teče pokraj — sve čega se dotakne raste. Kruna joj je od zvijezda, a njezino kraljevstvo nije osvojeno, nego uzgojeno. Ništa ne forsira. Jednostavno stvara uvjete u kojima život sam pronalazi put prema gore. U jastuke oko nje urezan je Venerin znak — ljepota koja nije ukras, nego sila za sebe.\n\nKad se pojavi, ova karta govori o obilju koje dolazi iz njege, a ne iz truda po svaku cijenu — o kreativnom projektu, odnosu, tijelu kojem treba pažnja, ne pritisak. Poveži se s osjetilnim svijetom: ljepotom, okusom, dodirom. Nešto je u tebi spremno procvjetati ako mu daš prostora i vremena.\n\nSjena Carice je briga otjerana predaleko, koja guši umjesto da njeguje — ljubav koja prelazi u kontrolu, ili kreativnost izlivena u sve druge, a nikad u sebe. Njezino je polje bujno jer zna kada se povući i pustiti stvari da rastu po svome. Nije svaka briga isto što i uplitanje. Prava briga ostavlja prostora da ono što voliš raste na svoj način.\n\nU odnosima Carica donosi toplinu, senzualnost i spremnost da daješ bez brojanja koliko ti je vraćeno. Na poslu najavljuje razdoblje kad projekt, posao ili ideja konačno počinju rađati — vidljivo, opipljivo, nakon tjedana ili mjeseci njege. Pogledaj što u tvom životu već tiho raste, čak i ako to još nisi primijetio. Zaslužuje vodu i svjetlo, ne samo nadzor.",
  },
  emperor: {
    name: "Car",
    keywords: ["Struktura", "Autoritet", "Čvrstoća"],
    meaning: "Sloboda bez oblika se rasprši. Car zna postaviti granicu unutar koje nešto može trajati.",
    profile:
      "Car sjedi na kamenom prijestolju, oklop ispod plašta, pogled čvrst, ruke mirne. Iza njega planine koje nijedna oluja nije pomaknula. Nije ondje slučajno — svoj je autoritet izgradio trudom i disciplinom, i sada ono što je stvorio čuva jasnim pravilima, a ne tiranijom. Na prijestolju su ovnujske glave — podsjetnik da je i on nekoć bio mlad i nestrpljiv, prije nego je naučio vladati.\n\nKad se pojavi, ova karta donosi potrebu za strukturom — u projektu kojem nedostaje okvir, u odnosu kojem trebaju jasne granice, u tebi samom kad si rasut. Preuzmi odgovornost za svoje kraljevstvo, kakvo god bilo. Red nije suprotnost slobodi. On je pozornica na kojoj sloboda uopće može nastupiti.\n\nSjena Cara je krutost koja ne dopušta iznimke ni kad su potrebne — moć koja zaboravi zašto je uopće izgrađena. Pravi vođa ne vlada strahom, nego pouzdanošću. Kad osjetiš potrebu da sve držiš pod kontrolom, pitaj se braniš li nešto vrijedno ili samo vlastiti nemir.\n\nU odnosima Car donosi pouzdanost — partnera koji drži riječ, koji sigurnost stvara dosljednošću, a ne velikim gestama. Na poslu najavljuje vrijeme za preuzimanje vodstva, jasan plan i ustrajanje na njemu. Gradi svoje kraljevstvo polako, kamen po kamen, i ne daj da ga sruši prvi nalet sumnje.",
  },
  hierophant: {
    name: "Svećenik",
    keywords: ["Tradicija", "Učenje", "Zajednica"],
    meaning: "Ne moraš uvijek iznova izmišljati kotač. Neki odgovori već postoje — idi ih pitati.",
    profile:
      "Svećenik sjedi između dva stupa u hramu, dvojica učenika slušaju pred njim. Ruka mu je podignuta u blagoslov, a znanje mu je naslijeđeno — prenosi se s naraštaja na naraštaj, provjereno, trajno. Ne zanima ga originalnost po svaku cijenu. Zanima ga ono što zaista djeluje. Pred njim leže dva prekrižena ključa — za vanjsko i za unutarnje znanje, za ono što se nauči i ono što se probudi.\n\nKad se pojavi, ova karta može govoriti o mentorstvu, formalnom obrazovanju, vjeri ili zajednici koja ti nudi pripadnost. Možda je vrijeme da potražiš vodiča, učitelja ili sustav koji ne moraš graditi od nule. Nije svaki put samotan. Neke je lakše prijeći u redu iza nekoga tko ih je već prešao.\n\nSjena Svećenika je slijepo slijeđenje pravila i kad ona više ne služe — tradicija radi tradicije, a ne zato što još ima smisla. Prava mudrost ove karte nije u pokornosti, nego u prepoznavanju koja je znanja prošlosti vrijedno nositi dalje, a koja je vrijeme spustiti.\n\nU odnosima Svećenik može najaviti formalnu obvezu — brak, zavjet, javno priznanje veze, ili jednostavno odnos sagrađen na zajedničkim vrijednostima. Na poslu govori o strukturiranom učenju, certifikatu, mentoru koji ti može uštedjeti godine samostalnog lutanja. Nemoj se sramiti pitati za pomoć onoga tko je put već prešao. To nije slabost. To je mudrost.",
  },
  lovers: {
    name: "Ljubavnici",
    keywords: ["Izbor", "Sjedinjenje", "Usklađenost"],
    meaning: "Nije svaka odluka laka, ali neke te dovedu kući, k sebi.",
    profile:
      "Dvoje stoje goli, bez srama, anđeo bdije nad njima raširenih ruku poput blagoslova. Iza njih stablo znanja i stablo života — izbor između onoga što je sigurno i onoga što je istinito. Ova karta nije samo o romansi. O svakom je trenutku u kojem moraš odlučiti što je zaista usklađeno s tobom. U pozadini se između njih diže planina — podsjetnik da svaka prava veza traži i uspon, ne samo početnu privlačnost.\n\nKad se pojavi, ova karta govori o važnom izboru — između dva puta, dvoje ljudi, dva dijela sebe. Ne biraj ono što se očekuje. Biraj ono što odjekuje duboko, čak i kad je teže objasniti zašto. Prava veza, s osobom ili sa zvanjem, osjeća se kao prepoznavanje, ne kao kompromis.\n\nSjena Ljubavnika je izbor donesen iz straha od samoće, a ne iz stvarne usklađenosti — ostajanje s nekim ili nečim jer je poznato, a ne jer je ispravno. Prava veza ne traži da se skupiš u sebe kako bi pristajao. Traži da se pokažeš cijel i vjeruješ da je to dovoljno.\n\nU odnosima ova karta često najavljuje duboku, značajnu vezu — ne nužno laku, ali stvarnu. Na poslu može govoriti o partnerstvu, suradnji ili izboru između dva smjera karijere koja te oba istinski zovu. Slušaj koji te izbor ostavlja cjelovitijim, a ne koji je sigurniji. Duša rijetko laže o tome što zaista želi.",
  },
  chariot: {
    name: "Kola",
    keywords: ["Volja", "Pobjeda", "Kontrola"],
    meaning: "Dvije sile vuku u različitim smjerovima. Pobjeđuješ kad ih usmjeriš prema istoj točki.",
    profile:
      "Vozač stoji u kolima koja vuku dvije sfinge, jedna crna, jedna bijela — ne vezane uzdama, nego samo njegovom voljom. Nije ovo pitanje sile, nego smjera. Nad glavom su mu zvijezde, oklop ispod odjeće spremnost. Pobjeda nije slučajnost. Ona je posljedica discipline usmjerene na pravu stranu. Grad iz kojeg je došao ostaje iza njega — ne osvrće se, jer ga zanima samo put naprijed.\n\nKad se pojavi, ova karta donosi snagu da nadvladaš suprotstavljene sile — u sebi ili oko sebe — i kreneš naprijed s jasnom namjerom. Nije vrijeme za sumnju. Vrijeme je da uzmeš uzde u ruke i pokreneš se, čak i ako se dva dijela tebe još uvijek ne slažu do kraja.\n\nSjena Kola je sila bez smjera — energija koja juri naprijed ne znajući kamo. Prava pobjeda ove karte nije u tome da nadjačaš druge, nego da uskladiš suprotstavljene dijelove sebe dovoljno da se mogu kretati u istom smjeru. Kola bez usmjerenog vozača samo su nesreća koja čeka da se dogodi.\n\nU odnosima ova karta donosi odlučnost — vrijeme da preuzmeš inicijativu umjesto da čekaš znak od drugoga. Na poslu najavljuje razdoblje usredotočene ambicije u kojem možeš postići više nego što si mislio, ako ostaneš sabran. Ne pokušavaj kontrolirati sve odjednom. Usmjeri volju u jednom smjeru i sile koje su se činile suprotstavljenima nosit će te naprijed, a ne razdvajati.",
  },
  strength: {
    name: "Snaga",
    keywords: ["Nježnost", "Hrabrost", "Unutarnja moć"],
    meaning: "Prava snaga ne viče. Položi ruku na lavlju glavu i smiri ga nježnošću, ne silom.",
    profile:
      "Žena stoji uz lava, ruka mirno na njegovoj glavi, iznad nje znak beskonačnosti. Ne bori se sa zvijeri. Pripitomljuje je ljubavlju, a ne strahom. Ovo je slika snage kakvu svijet rijetko uči — one kojoj ne treba glasnoća da bi bila stvarna. Držanje joj je opušteno, gotovo nježno — u rukama nema napetosti, jer zna da se ova bitka uopće ne mora dobiti silom.\n\nKad se pojavi, ova karta govori o hrabrosti da se suočiš s vlastitim nagonima, strahovima ili bijesom — ne tako da ih ugušiš, nego tako da ih razumiješ i vodiš. Nježnost nije slabost. Kad nešto u tebi želi pobjeći ili napasti, pokušaj umjesto toga ostati — s mekoćom koja izdrži.\n\nSjena ove karte je potiskivanje — pretvaranje da lav uopće ne postoji, umjesto da ga naučiš razumjeti. Snaga koju skrivaš od sebe prije ili kasnije se izrazi na način koji ne biraš sam. Prava Snaga ne znači da nemaš divlje nagone. Znači da znaš živjeti uz njih, a da te ne vode.\n\nU odnosima ova karta donosi strpljenje prema onome što je kod drugoga teško prihvatiti — sposobnost da ostaneš mekan i onda kad bi bilo lakše oštro reagirati. Na poslu govori o ustrajnosti bez sile, o mirnom nastavljanju i kad okolnosti pozivaju na paniku. Tvoja najveća snaga ovih dana nije u tome koliko možeš podnijeti, nego koliko se nježno možeš suočiti s onim čega se najviše bojiš.",
  },
  hermit: {
    name: "Pustinjak",
    keywords: ["Samoća", "Unutarnje traženje", "Mudrost"],
    meaning: "Svjetiljka koju nosi ne osvjetljava prvo put drugima. Osvjetljava njegov vlastiti.",
    profile:
      "Pustinjak stoji sam na vrhu planine, svjetiljka u ruci, štap za oslonac. Ne bježi od svijeta — povlači se u njega, u tišinu u kojoj glasovi svih ostalih napokon utihnu i ostaje samo njegov. Svjetlo mu je malo, ali dovoljno da vidi sljedeći korak. Ne pokazuje put mnoštvu — pokazuje ga samo onome tko ga je spreman tražiti sam.\n\nKad se pojavi, ova karta poziva na povlačenje — od buke, od tuđih očekivanja, od neprestanog reagiranja. Nije to usamljenost, nego namjerna samoća u kojoj možeš pronaći odgovor koji među ljudima nikad ne bi čuo. Neka se pitanja ne mogu riješiti u društvu. Trebaju tišinu, i tebe, sama sa sobom.\n\nSjena Pustinjaka je izolacija koja traje predugo — povlačenje koje se pretvori u bijeg od same povezanosti, a ne samo od buke. Prava mudrost ove karte nije u tome da ostaneš sam zauvijek. U tome je da se iz tišine vratiš s nečim što možeš podijeliti s drugima, obogaćen, a ne iscrpljen.\n\nU odnosima Pustinjak može značiti razdoblje u kojem ti treba prostor za sebe prije nego budeš sposoban biti uistinu prisutan za nekog drugog. Na poslu govori o istraživanju, učenju, dubokom promišljanju prije sljedećeg poteza. Ne tjeraj se u društvo dok nisi spreman. Tvoje vlastito svjetlo, koliko god malo, pokazat će ti kad je vrijeme za povratak među ljude.",
  },
  "wheel-of-fortune": {
    name: "Kolo sreće",
    keywords: ["Promjena", "Ciklusi", "Sudbina"],
    meaning: "Kolo se okreće bez obzira pokušavaš li ga zaustaviti. Pitanje je kako se okrećeš s njim.",
    profile:
      "Veliko se kolo okreće u zraku, obilježeno simbolima starijima od našeg doba — svaki se ciklus već dogodio, u nekom obliku, nekom drugom prije. Ono što je bilo gore ide dolje; ono što je bilo dolje se diže. Ništa ne ostaje isto zauvijek, i u tome je zapravo olakšanje. Oko kola bdiju četiri bića, svako sa svojom knjigom — podsjetnik da se svaki ciklus negdje zapiše, čak i kad se čini da nestaje bez traga.\n\nKad se pojavi, ova karta najavljuje pomak — nešto na što nisi imao potpuni utjecaj se okreće. Ne grči se za onim što odlazi i ne boj se onoga što dolazi. Ciklusi postoje da bismo kroz njih učili, a ne da im umaknemo. Trenutna sreća ili nesreća nije trajno stanje. To je samo jedan trenutak na kolu.\n\nSjena ove karte je uvjerenje da nemaš nikakav utjecaj na vlastitu sudbinu — pasivnost koja čeka da se kolo okrene samo, umjesto da surađuje s njegovim kretanjem. Kolo sreće doista se okreće samo od sebe. Ali kako se držiš i što usput naučiš i dalje je tvoj izbor.\n\nU odnosima ova karta najavljuje promjenu dinamike — možda kraj razdoblja neizvjesnosti, možda neočekivani obrat koji sve postavlja iznova. Na poslu govori o prilici koja dolazi izvana, ne kao izravna posljedica tvog truda, ali je svejedno vrijedi zgrabiti. Ne pokušavaj kontrolirati kolo. Nauči ploviti s njim i uvijek će postojati sljedeći okret koji te nosi naprijed.",
  },
  justice: {
    name: "Pravda",
    keywords: ["Ravnoteža", "Istina", "Posljedice"],
    meaning: "Vaga ne laže. Ono što posiješ na kraju vidiš s druge strane.",
    profile:
      "Pravda sjedi između dva stupa, u jednoj ruci mač, u drugoj vaga. Mač je podignut ravno, bez naklonosti ijednoj strani. Ne odlučuje po osjećaju. Odlučuje po istini kakva jest, a ne kakvu bi netko želio da bude. Pogled joj je miran, gotovo neumoljiv — ne zato što joj je svejedno, nego zato što zna da istina mora doći prije udobnosti.\n\nKad se pojavi, ova karta poziva na poštenu prosudbu — prema sebi i prema drugima. Možda dolazi odluka, ugovor ili posljedica nečega što si već učinio. Ne izbjegavaj odgovornost i ne očekuj da će nepravda trajati vječno. Ravnoteža se uvijek uspostavi, iako ponekad ne onako ili ne onda kad bi ti izabrao.\n\nSjena ove karte je kruto suđenje bez milosti — pravilo primijenjeno bez razumijevanja okolnosti koje su ga oblikovale. Prava pravda nije samo kazniti pogrešku. Prava pravda je vidjeti cijelu sliku prije nego izrekneš presudu, čak i kad je ta presuda namijenjena tebi samom.\n\nU odnosima Pravda donosi potrebu za iskrenošću — priznanje vlastitog udjela u sukobu, ne samo tuđeg. Na poslu najavljuje ugovor, pravni postupak ili odluku koja se mora donijeti na temelju činjenica, a ne simpatije. Prihvati odgovornost za ono što je tvoje i ne preuzimaj teret koji nije. Svemir vodi precizno knjigovodstvo, i onda kad se tako ne čini.",
  },
  "hanged-man": {
    name: "Obješenik",
    keywords: ["Stanka", "Nova perspektiva", "Predaja"],
    meaning: "Svijet izgleda drukčije naopako. Ponekad je upravo to ono što trebaš vidjeti.",
    profile:
      "Obješenik visi o jednoj nozi sa stabla, lica mirna, gotovo nasmiješena. Nije ovo kazna. Odabrana je predaja — ostajanje u neudobnom položaju dovoljno dugo da se perspektiva preokrene. Oko glave mu svijetli tanak sjaj, znanje koje ne bi stekao stojeći uspravno. Druga mu je noga prekrižena iza prve i tvori gotovo savršenu četvorku — oblik koji se ponavlja kroz cijeli špil kad god je nešto spremno promijeniti oblik.\n\nKad se pojavi, ova karta kaže: ne guraj naprijed. Umjesto toga ostani, pričekaj, pogledaj stvari s druge strane. Nije ovo vrijeme za odluke ili djelovanje — vrijeme je za predaju onome što ne možeš kontrolirati i za povjerenje da stanka nosi vlastitu vrijednost, čak i ako izvana izgleda kao ništa.\n\nSjena ove karte je žrtvovanje bez svrhe — zaglavljivanje u nelagodi bez ikakve dobiti, samo zato što je tako ispalo. Prava predaja ove karte nije pasivna. Ona je aktivna odluka da ostaneš u teškom položaju dok ti ne pokaže ono što inače ne bi vidio.\n\nU odnosima Obješenik može najaviti razdoblje čekanja — na odgovor, na jasnoću, na to da druga osoba dođe do vlastite spoznaje svojim tempom. Na poslu upozorava da ne forsiraš odluku koja još nije sazrela. Nije svaka stanka izgubljeno vrijeme. Neke su stanke jedini način da uopće vidiš što je cijelo vrijeme stajalo naopako.",
  },
  death: {
    name: "Smrt",
    keywords: ["Kraj", "Preobrazba", "Novo poglavlje"],
    meaning: "Nešto mora umrijeti da bi nešto drugo živjelo. To nije tragedija — to je priroda.",
    profile:
      "Smrt jaše bijelog konja, oklop crn, barjak s ružom koja cvate unatoč svemu. Pred njim svi padaju jednako — kralj, dijete, svećenik — nitko nije izuzet od promjene. Ali iza njega izlazi i sunce. Kraj jedne stvari uvijek je početak sljedeće. Rijeka teče prema tom izlazećem suncu — put naprijed postoji, čak i ako ga odavde gdje stojiš još ne vidiš.\n\nKad se pojavi, ova karta rijetko najavljuje doslovnu smrt — govori o kraju razdoblja, odnosa, identiteta koji je odslužio svoju svrhu i sada mora otići da nastane prostor za nešto novo. Ne grči se za onim što je već mrtvo. Promjena koja se doima kao gubitak često je prerušeno rođenje.\n\nSjena ove karte je poricanje — pokušaj da nešto već završeno umjetno održavaš na životu jer se bojiš praznine koja bi ostala. Smrt ne traži dopuštenje. Dolazi kad je vrijeme, a ne kad smo spremni. No upravo je u tome i njezina milost: ne dopušta da stvari trunu dulje nego je potrebno.\n\nU odnosima ova karta može najaviti kraj faze — ne nužno samog odnosa, nego često kraj onoga što je bio dosad, kako bi mogao postati nešto drugo. Na poslu govori o zatvaranju projekta, uloge ili poglavlja karijere. Tuguj ako treba, ali ne ostaj predugo uz grob onoga što je prošlo. Nešto novo već čeka da izađe.",
  },
  temperance: {
    name: "Umjerenost",
    keywords: ["Ravnoteža", "Strpljenje", "Stapanje"],
    meaning: "Ne obje krajnosti odjednom. Negdje između je tekućina koja se ne prolije.",
    profile:
      "Anđeo stoji s jednom nogom u vodi, drugom na kopnu, i prelijeva tekućinu iz jednog pehara u drugi, bez ijedne izgubljene kapi. Nema žurbe. Ne dijeli svijet na crno i bijelo — pronalazi treći prostor u kojem se stvari koje se čine suprotstavljenima mogu sresti. Put iza nje vodi prema planinama i izlazećem suncu — spor, ali jasan smjer, bez potrebe za prečacima.\n\nKad se pojavi, ova karta poziva na strpljenje i umjerenost — u osjećajima koje bi možda htio izraziti odjednom, u odlukama koje se čine kao „sve ili ništa“. Potraži srednji put. Ono što traje rijetko nastaje u žurbi. Miješanje, usklađivanje, polagano prilagođavanje — to je alkemija ove karte.\n\nSjena Umjerenosti je izbjegavanje odluke u ime „ravnoteže“ — nikad se ne obvezati ni na što, iz straha da ne izgubiš nešto drugo. Prava umjerenost ne znači izbjegavati krajnosti po svaku cijenu. Znači znati kada se nečemu posve predati, a kada pričekati da se stvari same slegnu.\n\nU odnosima ova karta donosi ozdravljenje nakon neslaganja — sposobnost da nađeš zajednički jezik i kad se čini da ste ti i partner previše različiti. Na poslu govori o postupnom, ustrajnom napretku, a ne o brzim pobjedama. Ne pokušavaj sve popraviti odjednom. Pomalo, dan za danom, slaže se ono što će na kraju držati oblik.",
  },
  devil: {
    name: "Vrag",
    keywords: ["Vezanost", "Sjena", "Iluzija zarobljenosti"],
    meaning: "Lanci oko vrata para dovoljno su labavi da ih skinu. Ništa ih ondje ne drži osim njih samih.",
    profile:
      "Vrag se nadvija nad parom, oboje okovani, ali labavo — lanci bi skliznuli preko glave kad bi samo pokušali. Nije ovo stvarna zarobljenost. Navika je, strah, ovisnost, uvjerenje da nemaju izbora. Vrag nikoga ne prisiljava. Samo iskorištava ono što oni sami biraju iznova i iznova. Njegova baklja gori prema dolje, a ne prema gore — svjetlo okrenuto od istine umjesto prema njoj.\n\nKad se pojavi, ova karta otkriva obrazac koji te drži zarobljenim — odnos koji ti ne služi, naviku koju ponavljaš, misao koja te uvjerava da si nemoćan. Istina je neugodna, ali oslobađajuća: lanac se skida. Prvi korak prema slobodi je priznati da si ondje ostao vlastitim izborom.\n\nSjena ove karte je sama karta — ali i unutar te sjene postoji dublja: osuđivanje sebe što si uopće ostao zarobljen, umjesto da to jednostavno priznaš i kreneš dalje. Vrag ne traži savršenstvo od onoga tko se oslobađa. Traži samo spremnost da pokušaš podići lanac, čak i bez znanja što dolazi poslije.\n\nU odnosima ova karta može otkriti nezdravu vezanost — strast koja graniči s ovisnošću, ili odnos koji oboje održavaju iz straha od samoće, a ne iz ljubavi. Na poslu upozorava na zamku zlatnih okova — udobnu lošu situaciju iz koje se ne mičeš jer je poznata. Pogledaj dolje. Lanac je doista ondje. Ali tvoja je ruka slobodna da ga podigne preko glave, kad god budeš spreman.",
  },
  tower: {
    name: "Kula",
    keywords: ["Nagli preokret", "Otkrivenje", "Rušenje"],
    meaning: "Munja ne uništava ono što je bilo čvrsto. Otkriva ono što je već bilo šuplje.",
    profile:
      "Munja udara u vrh kule, kruna odlijeće, dvije figure padaju kroz zrak. Građevina za koju se vjerovalo da je trajna ruši se u jednom jedinom trenutku. Ovo je najbolnija karta u špilu — i ujedno jedna od najpotrebnijih. Plamen sukljaju iz prozora koji su nekoć bili siguran dom — dokaz da je nešto iznutra gorjelo dugo prije nego je itko izvana vidio dim.\n\nKad se pojavi, ova karta najavljuje nagli preokret koji nisi izabrao — kraj iluzije, otkrivanje istine koju je bilo lakše ne vidjeti. Nije ovo kazna. Oslobođenje je od strukture sagrađene na krivim temeljima. Ono što pada moralo je pasti, kako bi se na njegovu mjestu moglo izgraditi nešto stvarno.\n\nSjena ove karte nije u samom padu, nego u tome koliko si dugo znao da dolazi i svejedno ga ignorirao. Kula rijetko udari bez upozorenja. Prvo šalje pukotine, tihe znakove koje je bilo lakše previdjeti nego se s njima suočiti. Kad munja udari, to je samo posljednje i najglasnije od svih upozorenja.\n\nU odnosima ova karta može najaviti otkrivenje koje mijenja sve — istinu skrivanu predugo, ili kraj nečega što je izvana izgledalo čvrsto. Na poslu upozorava na nagli obrat, gubitak koji nisi predvidio. Ne pokušavaj obnoviti kulu u istom obliku. Ono što je palo bilo je namijenjeno padu — da na praznom tlu ovaj put izraste nešto sagrađeno na čvršćim temeljima.",
  },
  star: {
    name: "Zvijezda",
    keywords: ["Nada", "Obnova", "Vodeće svjetlo"],
    meaning: "Nakon oluje Kule dolazi tišina, a u tišini jedno jedino svjetlo koje pokazuje put naprijed.",
    profile:
      "Žena kleči uz vodu, gola, bez srama, i izlijeva vodu iz dva vrča — jedan natrag u vodu, drugi na zemlju. Iznad nje sedam manjih zvijezda i jedna velika, vodeća. Nakon svega što je Kula srušila, ova karta dolazi kao dah nakon predugog zadržavanja. Iza nje ptica sjedi na stablu — znak da se život već vratio ondje gdje se činilo da nije ostalo ničega.\n\nKad se pojavi, ova karta donosi nadu koja nije naivna — zaslužena je, nakon nečega što si preživio. Vjeruj da se stvari popravljaju, čak i polako. Nije ovo vrijeme za sumnju u sebe. Negdje daleko gori svjetlo koje te vodi, čak i kad ga ne vidiš posve jasno. Nastavi u njegovu smjeru.\n\nSjena Zvijezde je nada koja prijeđe u pasivno čekanje čuda, umjesto u tihu radnju ponovljenu svaki dan. Žena uz vodu ne sjedi mirno — neprestano izlijeva, njeguje, obnavlja. Njezina je nada djelo, a ne samo osjećaj. Razlika između maštanja i prave nade upravo je u tome što druga traži da nešto činiš dok čekaš.\n\nU odnosima Zvijezda donosi ranjivost koja više nije opasna — sposobnost da se ponovno pokažeš onakav kakav jesi, nakon što te je nešto već ranilo. Na poslu najavljuje razdoblje nakon krize, kad se stvari polako ali sigurno okreću nabolje. Vjeruj da si vrijedan te nade. Zvijezde ne svijetle samo onima koji su već stigli na cilj. Svijetle i, prije svega, onima koji su još na putu.",
  },
  moon: {
    name: "Mjesec",
    keywords: ["Neizvjesnost", "Podsvijest", "Iluzija"],
    meaning: "Put kroz noć je stvaran, čak i ako ne vidiš kamo vodi. Nastavi, korak po korak.",
    profile:
      "Mjesec svijetli nad putom koji vodi između dvije kule, u nepoznato. Pas i vuk zavijaju prema njemu, rak puzi iz vode — sve što je skriveno budi se noću. Ovo je karta sjena, snova i strahova koji po danu nemaju sasvim jasan oblik. Sam Mjesec nosi lice s kojeg kaplju suze svjetlosti — čak je i vodeće svjetlo ove noći nesavršeno, neizvjesno, i samo u procesu mijenjanja.\n\nKad se pojavi, ova karta upozorava da stvari možda nisu onakve kakvima se čine — informacije su nepotpune, osjećaji zamršeni, put nije posve jasan. Ne forsiraj jasnoću koje još nema. Umjesto toga vjeruj intuiciji, koja u mraku vidi bolje od razuma. Neizvjesnost nije znak da si na krivom putu. Samo je dio noći kroz koju moraš proći.\n\nSjena ove karte je gubljenje u vlastitim strahovima — čudovišta koja stvara um postaju stvarnija od stvarne opasnosti. Pas i vuk zapravo zavijaju prema istom mjesecu. Strah i mašta imaju isti izvor. Nauči razlikovati pravo upozorenje od sjene koju je stvorio samo tvoj umor.\n\nU odnosima Mjesec može najaviti zbunjenost — nešto neizrečeno, nesporazum koji dolazi iz nedorečenosti, a ne iz zlobe. Na poslu upozorava da ne potpisuješ i ne odlučuješ ništa važno dok se magla ne razvedri. Neke se istine pokažu tek s jutarnjim svjetlom. Do tada vjeruj koraku po koraku, čak i ako put pred tobom nije posve osvijetljen.",
  },
  sun: {
    name: "Sunce",
    keywords: ["Radost", "Jasnoća", "Uspjeh"],
    meaning: "Nema razloga skrivati se u sjeni kad je nebo ovako vedro.",
    profile:
      "Dijete jaše bijelog konja pod velikim, užarenim suncem, ruku raširenih, suncokreti cvatu iza njega. Ništa skriveno, ništa u sjeni — ovo je najizravnije radosna karta u cijelom špilu. Radost ovdje nije naivnost. Zaslužena je jednostavnost, nakon svega što je bilo prije. Crvena zastava leprša na vjetru, bez straha, bez potrebe da išta brani — ništa se ne skriva jer više nema ničega čega bi se trebalo sramiti.\n\nKad se pojavi, ova karta donosi jasnoću, uspjeh i iskrenu radost — u projektu koji napokon rađa, u odnosu koji je lagan, u tebi samom kad se opet osjećaš cijelim. Dopusti si uživati bez grižnje savjesti, bez čekanja sljedeće brige. Ova je toplina zaslužena. Primi je u cijelosti.\n\nSjena ove karte je rijetka — Sunce u sebi nema puno tame. Ako zamka uopće postoji, to je pretjerano samopouzdanje koje zaboravi na ranjivost drugih jer je samo tako puno svjetla. Dijeli svoju radost, nemoj je razmetati. Sunce koje jednako obasjava sve ljepše je od onoga koje svijetli samo sebi.\n\nU odnosima ova karta donosi lakoću, smijeh, veselje bez komplikacija — razdoblje kad je ljubav jednostavna, a ne zapetljana. Na poslu najavljuje priznanje, uspjeh, vidljiv rezultat truda. Nemoj biti skroman o onome što si postigao. Dijete na konju ne ispričava se za svoju radost. Ne moraš ni ti.",
  },
  judgement: {
    name: "Sud",
    keywords: ["Buđenje", "Oprost", "Poziv"],
    meaning: "Truba ne sudi. Samo zove one koji su spremni ustati.",
    profile:
      "Anđeo trubi nad otvorenim grobovima, i mrtvi ustaju, ruku podignutih, spremni za nešto novo. Nije ovo kazna. Poziv je na buđenje — trenutak u kojem postaje nemoguće i dalje ignorirati istinu o sebi ili svom životu. Svi koji ustaju imaju isti izraz lica — ne strah, nego olakšanje, kao da su napokon čuli nešto što su cijelo vrijeme čekali.\n\nKad se pojavi, ova karta poziva na pošteno suočavanje s prošlošću — ne s osudom, nego s oprostom, i prema sebi i prema drugima. Nešto je u tebi spremno ustati iz onoga što je bilo. Poslušaj poziv, čak i ako stiže u nezgodan čas. Buđenje nije uvijek udobno. Ali se uvijek isplati odazvati.\n\nSjena ove karte je samoosuđivanje prerušeno u „buđenje“ — beskonačno prevrtanje prošlih pogrešaka bez ikakvog stvarnog oprosta. Truba ne zove da te kazni za ono što si bio. Zove te da postaneš ono što si sada sposoban biti.\n\nU odnosima ova karta može najaviti pomirenje — s partnerom, sa samim sobom, s verzijom sebe koju je bilo lakše osuditi nego razumjeti. Na poslu govori o pozivu koji napokon dobiva pravi smisao, ili o priznanju za trud koji je predugo ostajao neprimijećen. Odazovi se pozivu, čak i ako dolazi iz smjera koji nisi očekivao. Nešto je u tebi čekalo upravo ovaj trenutak.",
  },
  world: {
    name: "Svijet",
    keywords: ["Dovršenje", "Cjelovitost", "Novi ciklus"],
    meaning: "Krug se zatvara. I u istom se trenutku već otvara sljedeći.",
    profile:
      "Figura pleše usred lovorovog vijenca, okružena četirima bićima uglova svijeta — bikom, lavom, orlom, čovjekom. Sve je ovdje, sve je povezano, ništa ne nedostaje. Ovo je posljednja karta Velikih arkana, dovršenje dugog putovanja koje je počelo s Ludom na rubu litice. U svakoj ruci drži štap — simbol ravnoteže postignute ne izbjegavanjem krajnosti, nego sjedinjenjem svega što je bilo prije u jedan jedini, cjelovit pokret.\n\nKad se pojavi, ova karta najavljuje dovršenje — ciklus, projekt, poglavlje života koje je došlo do svog prirodnog kraja, uspješno. Proslavi ono što si postigao. Ali znaj i da svaki kraj nosi sjeme sljedećeg početka. Svijet se ne zaustavlja. Samo se okreće dalje, u novi krug, sa svime što si naučio već ugrađenim u tebe.\n\nSjena ove karte rijetko je njezina vlastita — pojavi se kad netko ne prizna dovršenje koje je već tu i grčevito se drži poglavlja koje je već ispisano do kraja. Svijet ne kažnjava onoga tko stane da proslavi. Kažnjava samo onoga tko nikad ne želi reći da je nešto dovršeno.\n\nU odnosima ova karta najavljuje duboko ispunjenje — vezu koja je cjelovita, bez dijelova koji nedostaju. Na poslu govori o dovršenju koje je dokaz tvog rasta od prve karte do ove posljednje. Zastani na trenutak. Pogledaj koliko si daleko stigao. A kad budeš spreman, Luda se opet pojavljuje na obzoru, praznog zavežljaja i spremna za novi put.",
  },
};
