export type Lang = "sl" | "en";

export interface TarotCard {
  key: string;
  number: number;
  name: { sl: string; en: string };
  /** 3-4 word association list shown as tags under the card name. */
  keywords: { sl: string[]; en: string[] };
  /** Short evergreen line shown right under the card image. */
  meaning: { sl: string; en: string };
  /** Longer read (~150-220 words, paragraphs separated by blank lines). Evergreen,
   *  upright-only for now — reversed meanings are a natural next addition. */
  profile: { sl: string; en: string };
}

// The 22 Major Arcana. Traditional, evergreen card meanings (not a personalized reading) —
// same category as zodiacData.ts's sign profiles: generic archetypal characterization, safe
// to show without her review, but she's welcome to rewrite the voice. Deliberately upright-
// only for this first pass; reversed meanings and the Minor Arcana are natural follow-ups.
export const TAROT_CARDS: TarotCard[] = [
  {
    key: "fool",
    number: 0,
    name: { sl: "Norec", en: "The Fool" },
    keywords: { sl: ["Nov začetek", "Zaupanje", "Skok"], en: ["New beginnings", "Trust", "The leap"] },
    meaning: {
      sl: "Rob prepada ni znak, da se ustaviš. Je znak, da je čas za prvi korak.",
      en: "The edge of the cliff isn't a sign to stop. It's a sign it's time for the first step.",
    },
    profile: {
      sl: "Norec stoji na robu, z majhno culo čez ramo in psom ob nogah, ki zvesto opozarja — a on gleda navzgor, ne navzdol. Ne pozna še poti, in prav to ga osvobaja. Vsaka pot, ki jo je kdo kdaj prehodil, se je začela z nekom, ki ni vedel, kam pelje. Njegova cula nosi le najnujnejše — vse drugo je pripravljen najti spotoma, ali pa se naučiti živeti brez tega.\n\nTa karta ne govori o neumnosti, govori o pogumu, ki ga ima samo tisti, ki še ni bil ranjen z izkušnjo. Kadar se pojavi, te vabi, da stopiš v neznano brez celotnega načrta — da zaupaš, da se odgovori pokažejo med potjo. Ni čas za previdnost. Je čas za skok.\n\nSenca Norca je nepremišljenost brez zavedanja posledic — skok, ki ga narediš, ne da bi sploh pogledal, kam padeš. Razlika med pogumom in lahkomiselnostjo ni v dejanju, ampak v tem, ali si pripravljen sprejeti, kar pride, tudi če ni tisto, kar si si predstavljal. Norec ne obljublja varnega pristanka. Obljublja samo, da bo pot sama nekaj naučila.\n\nV odnosih Norec prinaša svežino tja, kjer se je vse skupaj zdelo že znano — novo znanstvo, nepričakovan začetek, pripravljenost, da ljubiš brez zavarovanja pred izgubo. Pri delu naznanja projekt ali idejo, ki se zdi tvegana vsem naokoli, a tebi čutno prava. Kadar ta karta pade v tvoje branje, ne sprašuj se, ali si dovolj pripravljen. Nihče na robu prepada ni nikoli povsem pripravljen. Stopi.",
      en: "The Fool stands at the edge, a small bundle over one shoulder, a dog at his feet loyally warning him — but he's looking up, not down. He doesn't know the path yet, and that's exactly what frees him. Every road anyone has ever walked began with someone who didn't know where it led. His bundle carries only the essentials — everything else, he's willing to find along the way, or learn to live without.\n\nThis card isn't about foolishness — it's about a courage only available to someone who hasn't been wounded by experience yet. When it appears, it invites you to step into the unknown without the whole plan — to trust that the answers will show up along the way. This isn't a time for caution. It's a time to leap.\n\nThe Fool's shadow is recklessness without any awareness of consequence — a leap made without ever looking at where you'll land. The difference between courage and carelessness isn't in the act itself, but in whether you're willing to accept what comes, even if it isn't what you pictured. The Fool makes no promise of a safe landing. It only promises the road itself will teach you something.\n\nIn relationships, the Fool brings freshness where everything had started to feel familiar — a new acquaintance, an unexpected beginning, a willingness to love without insuring yourself against loss. At work, it signals a project or idea that looks risky to everyone around you but feels right to you at a gut level. When this card lands in your reading, don't ask yourself whether you're ready enough. No one standing at the edge of a cliff is ever fully ready. Step forward.",
    },
  },
  {
    key: "magician",
    number: 1,
    name: { sl: "Mag", en: "The Magician" },
    keywords: { sl: ["Volja", "Ustvarjanje", "Vsa orodja imaš"], en: ["Willpower", "Manifestation", "You have the tools"] },
    meaning: {
      sl: "Vse, kar potrebuješ, že imaš pred sabo na mizi. Vprašanje je, ali boš segel po tem.",
      en: "Everything you need is already on the table in front of you. The question is whether you'll reach for it.",
    },
    profile: {
      sl: "Mag stoji za mizo, na kateri ležijo vsa štiri orodja — čaša, meč, palica, pentagram — čustvo, misel, dejanje, telo. Ena roka kaže proti nebu, druga proti zemlji: povezuje idejo z resničnostjo. Nič ne čaka na naključje. Zna vzeti, kar že ima, in iz tega ustvariti nekaj novega. Nad njegovo glavo lebdi znak neskončnosti — opomnik, da vir, iz katerega ustvarja, ni omejen, dokler se nanj zna povezati.\n\nKadar se ta karta pojavi, sporoča, da imaš vse potrebne sposobnosti za nalogo pred sabo — vprašanje ni zmožnost, ampak namera. Osredotoči voljo na eno stvar, namesto da jo razpršiš na deset. Svet se ne bo premaknil sam. A ti se lahko premakneš vanj, natanko zdaj.\n\nSenca Maga je manipulacija — spretnost, uporabljena za to, da prepriča druge o nečem, kar ni res, namesto da bi ustvarila nekaj, kar drži samo po sebi. Prava moč te karte ni v trikih, je v usklajenosti med tem, kar misliš, govoriš in delaš. Kadar so ta trije med seboj poravnani, se stvari premikajo skoraj brez napora. Kadar niso, ostane samo predstava.\n\nV odnosih Mag pomeni pobudo — priložnost, da poveš, kar čutiš, namesto da čakaš, da nekdo drug naredi prvi korak. Pri delu naznanja projekt, v katerem lahko dejansko izkoristiš vse svoje spretnosti hkrati, ne le eno. Zaupaj svoji sposobnosti, da iz razpršenih koščcev sestaviš nekaj celega. Vse, kar potrebuješ, je že na mizi pred tabo.",
      en: "The Magician stands behind a table holding all four tools — cup, sword, wand, pentacle — feeling, thought, action, body. One hand points to the sky, the other to the earth: connecting idea to reality. Nothing here waits for chance. He knows how to take what he already has and make something new from it. Above his head floats the sign of infinity — a reminder that the source he creates from is unlimited, as long as he knows how to connect to it.\n\nWhen this card appears, it says you already have every skill this task needs — the question isn't ability, it's intention. Focus your will on one thing instead of scattering it across ten. The world won't move on its own. But you can move into it, right now.\n\nThe Magician's shadow is manipulation — skill used to convince others of something untrue, instead of creating something that holds up on its own. This card's real power isn't in tricks; it's in the alignment between what you think, say, and do. When those three line up, things move almost without effort. When they don't, all that's left is a performance.\n\nIn relationships, the Magician means initiative — the chance to say what you feel instead of waiting for someone else to take the first step. At work, it signals a project where you can actually use all your skills at once, not just one. Trust your ability to assemble something whole out of scattered pieces. Everything you need is already on the table in front of you.",
    },
  },
  {
    key: "high-priestess",
    number: 2,
    name: { sl: "Vrhovna Duhovnica", en: "The High Priestess" },
    keywords: { sl: ["Intuicija", "Skrivnost", "Notranje vedenje"], en: ["Intuition", "Mystery", "Inner knowing"] },
    meaning: {
      sl: "Odgovor, ki ga iščeš zunaj, že šepeta znotraj tebe. Utihni dovolj dolgo, da ga slišiš.",
      en: "The answer you're searching for outside is already whispering inside you. Grow quiet enough to hear it.",
    },
    profile: {
      sl: "Vrhovna Duhovnica sedi med dvema stebroma, enim črnim in enim belim, senco in svetlobo, in ne izbere nobenega — ostane vmes, kjer se skrivnost šele oblikuje. Za njo je tanka zavesa; ne prepove ti pogleda, samo prosi, da si pripravljen videti. Njeno znanje ni v knjigah. Je v tišini. V naročju drži zvitek, na katerem piše samo delno vidna beseda — opomnik, da ni vsako znanje namenjeno takojšnjemu razumevanju.\n\nKadar se pojavi, te ta karta vabi, da zaupaš tistemu, česar (še) ne moreš razložiti z razumom. Nekaj že veš, še preden dobiš dokaz. To ni čas za glasne odločitve ali hitro delovanje — je čas za poslušanje. Sanje, slutnje, telesni občutki: vse to je jezik, ki ga vredno je razumeti.\n\nSenca te karte je zapiranje vase do te mere, da izgubiš stik s svetom okrog sebe — skrivnost, ki postane samota, namesto notranjega vira moči. Vrhovna Duhovnica ne beži pred svetom. Samo ve, da nekaterih odgovorov ne najdeš v hrupu, ampak v prostoru, ki si ga ustvariš zase, stran od pričakovanj drugih.\n\nV odnosih ta karta govori o nečem, kar še ni izrečeno na glas — čustvu, ki ga čutiš, a še ne znaš ubesediti, ali skrivnosti, ki jo nekdo drug nosi. Pri delu opozarja, naj ne siliš k odločitvi, dokler ne dobiš celotne slike. Zaupaj tišini pred odgovorom bolj kot pritisku, da moraš nekaj reči zdaj. Prava jasnost pride tistemu, ki zna počakati nanjo.",
      en: "The High Priestess sits between two pillars, one black, one white, shadow and light, and chooses neither — she stays in the space between, where the mystery is still forming. Behind her hangs a thin veil; it doesn't forbid you to look, it only asks that you're ready to see. Her knowledge isn't in books. It's in silence. In her lap she holds a scroll bearing a word only partly visible — a reminder that not all knowledge is meant for immediate understanding.\n\nWhen this card appears, it invites you to trust what you can't yet explain with reason. You already know something before you have proof. This isn't a time for loud decisions or fast action — it's a time for listening. Dreams, hunches, the body's own signals: all of it is a language worth understanding.\n\nThis card's shadow is withdrawing so far inward that you lose touch with the world around you — mystery turning into isolation, instead of an inner source of strength. The High Priestess isn't fleeing the world. She simply knows that some answers aren't found in noise, but in a space you build for yourself, away from everyone else's expectations.\n\nIn relationships, this card speaks of something not yet said out loud — a feeling you sense but can't put into words yet, or a secret someone else is carrying. At work, it warns against forcing a decision before you have the full picture. Trust the silence before the answer more than the pressure to say something right now. Real clarity comes to whoever knows how to wait for it.",
    },
  },
  {
    key: "empress",
    number: 3,
    name: { sl: "Cesarica", en: "The Empress" },
    keywords: { sl: ["Obilje", "Ustvarjalnost", "Nega"], en: ["Abundance", "Creativity", "Nurturing"] },
    meaning: {
      sl: "Nekaj, kar goji, raste. To velja za polja in za ljudi enako.",
      en: "What is nurtured, grows. That's as true of fields as it is of people.",
    },
    profile: {
      sl: "Cesarica sedi sredi bujnega polja, pšenica zori okrog nje, reka teče mimo — vse, kar se je dotakne, raste. Njena krona je iz zvezd, njeno kraljestvo pa ni osvojeno, ampak vzgojeno. Ne sili ničesar. Preprosto ustvarja pogoje, v katerih lahko življenje samo najde pot navzgor. Na blazinah okrog nje je vrezan simbol Venere — lepote, ki ni okrasje, ampak sila sama.\n\nKadar se pojavi, ta karta govori o obilju, ki prihaja iz nege, ne iz truda za vsako ceno — ustvarjalnem projektu, odnosu, telesu, ki potrebuje pozornost, ne pritiska. Poveži se s čutnostjo sveta: lepoto, okusom, dotikom. Nekaj v tebi je pripravljeno cveteti, če mu daš prostor in čas.\n\nSenca Cesarice je pretirana skrb, ki zaduši namesto neguje — ljubezen, ki postane nadzor, ali ustvarjalnost, vložena v vse druge, nikoli vase. Njeno polje je bujno, ker ve, kdaj naj se umakne in pusti stvarem rasti po svoje. Ni vsaka nega enaka poseganju. Prava skrb pusti prostor za lastno rast tistega, kar ljubiš.\n\nV odnosih Cesarica prinaša toplino, čutnost in pripravljenost dajati brez štetja, koliko je bilo vrnjenega. Pri delu naznanja obdobje, ko projekt, posel ali ideja končno začne obroditi — vidno, otipljivo, po tednih ali mesecih nege. Poglej, kaj v tvojem življenju že raste v tišini, tudi če tega še nisi opazil. Zasluži si vodo in svetlobo, ne le nadzor.",
      en: "The Empress sits in the middle of a lush field, wheat ripening around her, a river running past — everything she touches grows. Her crown is made of stars, and her kingdom wasn't conquered, it was cultivated. She forces nothing. She simply creates the conditions in which life can find its own way up. Carved into the cushions around her is the symbol of Venus — beauty not as decoration, but as a force in its own right.\n\nWhen this card appears, it speaks of abundance that comes from care, not effort at any cost — a creative project, a relationship, a body that needs attention, not pressure. Reconnect with the sensory world: beauty, taste, touch. Something in you is ready to bloom, if you give it room and time.\n\nThe Empress's shadow is care taken too far, smothering instead of nurturing — love that turns into control, or creativity poured into everyone else and never into yourself. Her field is lush because she knows when to step back and let things grow on their own. Not all care is the same as intervening. Real care leaves room for what you love to grow in its own way.\n\nIn relationships, the Empress brings warmth, sensuality, and a willingness to give without counting what's owed back. At work, it signals a season when a project, business, or idea finally starts bearing fruit — visible, tangible, after weeks or months of tending. Look at what's already growing quietly in your life, even if you haven't noticed it yet. It deserves water and light, not just supervision.",
    },
  },
  {
    key: "emperor",
    number: 4,
    name: { sl: "Cesar", en: "The Emperor" },
    keywords: { sl: ["Struktura", "Avtoriteta", "Trdnost"], en: ["Structure", "Authority", "Stability"] },
    meaning: {
      sl: "Svoboda brez oblike se razblini. Cesar zna postaviti mejo, znotraj katere lahko nekaj traja.",
      en: "Freedom without a shape dissolves. The Emperor knows how to set a boundary within which something can last.",
    },
    profile: {
      sl: "Cesar sedi na kamnitem prestolu, oklopljen pod ogrinjalom, pogled trden, roke mirne. Za njim gore, ki jih ni premaknil noben vihar. Ni tam po naključju — zgradil si je oblast s trudom in disciplino, in zdaj varuje to, kar je ustvaril, z jasnimi pravili, ne s tiranijo. Njegov prestol nosi glave ovnov — spomin na to, da je bil nekoč tudi sam mlad in nepotrpežljiv, preden se je naučil vladati.\n\nKadar se pojavi, ta karta prinaša potrebo po strukturi — v projektu, ki mu manjka okvir, v odnosu, ki potrebuje jasne meje, v tebi samem, kadar si razpršen. Prevzemi odgovornost za svoje kraljestvo, kakršno koli že je. Red ni nasprotje svobode. Je oder, na katerem svoboda sploh lahko nastopi.\n\nSenca Cesarja je togost, ki ne dopušča izjem, tudi kadar bi bile potrebne — moč, ki pozabi, zakaj je bila sploh zgrajena. Pravi voditelj ne vlada s strahom, ampak z zanesljivostjo. Kadar začutiš potrebo, da imaš nadzor nad vsem, se vprašaj, ali braniš nekaj vrednega, ali samo svoj lastni nemir.\n\nV odnosih Cesar prinaša zanesljivost — partnerja, ki drži besedo, ki ustvarja varnost s svojo doslednostjo, ne z velikimi gestami. Pri delu naznanja čas, ko je treba prevzeti vodstvo, postaviti jasen načrt in se ga držati. Zgradi svoje kraljestvo počasi, kamen za kamnom, in ne dovoli, da ga podre prvi veter dvoma.",
      en: "The Emperor sits on a stone throne, armor beneath his robe, gaze steady, hands still. Behind him, mountains no storm has moved. He isn't there by accident — he built his authority through effort and discipline, and now he protects what he's created with clear rules, not tyranny. His throne bears ram's heads — a reminder that he too was once young and impatient, before he learned how to rule.\n\nWhen this card appears, it brings a need for structure — in a project missing a framework, in a relationship that needs clear boundaries, in yourself when you feel scattered. Take responsibility for your own kingdom, whatever shape it takes. Order isn't the opposite of freedom. It's the stage freedom needs in order to perform at all.\n\nThe Emperor's shadow is rigidity that allows no exceptions, even when they're needed — power that forgets why it was built in the first place. A real leader doesn't rule through fear, but through reliability. When you feel the need to control everything, ask yourself whether you're protecting something worth protecting, or just your own restlessness.\n\nIn relationships, the Emperor brings reliability — a partner who keeps their word, who creates safety through consistency rather than grand gestures. At work, it signals a time to take the lead, set a clear plan, and stick to it. Build your kingdom slowly, stone by stone, and don't let the first gust of doubt knock it down.",
    },
  },
  {
    key: "hierophant",
    number: 5,
    name: { sl: "Hierofant", en: "The Hierophant" },
    keywords: { sl: ["Tradicija", "Učenje", "Skupnost"], en: ["Tradition", "Teaching", "Community"] },
    meaning: {
      sl: "Ne rabiš vedno izumiti kolesa na novo. Nekateri odgovori že obstajajo — pojdi jih vprašat.",
      en: "You don't always have to reinvent the wheel. Some answers already exist — go and ask.",
    },
    profile: {
      sl: "Hierofant sedi med dvema stebroma v templju, dva učenca pred njim poslušata. Njegova roka je dvignjena v blagoslov, njegovo znanje pa je podedovano — prehaja iz generacije v generacijo, preizkušeno, obstojno. Ne zanima ga izvirnost za vsako ceno. Zanima ga, kaj resnično deluje. Pred njim ležita prekrižana ključa — do zunanjega znanja in do notranjega, do tistega, kar se nauči, in tistega, kar se prebudi.\n\nKadar se pojavi, ta karta lahko govori o mentorstvu, formalnem izobraževanju, veri ali skupnosti, ki ti ponuja pripadnost. Morda je čas, da poiščeš vodjo, učitelja ali sistem, ki ga ni treba graditi od začetka. Ni vsaka pot samotna. Nekatere se hodijo lažje v vrsti za tistim, ki jo je že prehodil.\n\nSenca Hierofanta je slepo sledenje pravilom, tudi kadar ta ne služijo več — tradicija zaradi tradicije same, ne zato, ker bi še vedno imela smisel. Prava modrost te karte ni v podrejanju, je v prepoznavanju, katera znanja preteklosti so vredna prenašanja naprej, in katera je čas spustiti.\n\nV odnosih Hierofant lahko naznanja formalno zavezo — poroko, zaobljubo, javno priznanje povezave, ali preprosto odnos, zgrajen na skupnih vrednotah. Pri delu govori o strukturiranem učenju, certifikatu, mentorju, ki ti lahko prihrani leta samostojnega tavanja. Ne sramuj se vprašati za pomoč tistega, ki je pot že prehodil. To ni šibkost. Je modrost.",
      en: "The Hierophant sits between two pillars in a temple, two students listening before him. His hand is raised in blessing, and his knowledge is inherited — passed from generation to generation, tested, durable. He isn't interested in originality at any cost. He's interested in what actually works. Before him lie two crossed keys — to outer knowledge, and to inner knowledge, to what is learned and to what is awakened.\n\nWhen this card appears, it can speak of mentorship, formal education, faith, or a community offering you belonging. Maybe it's time to find a guide, a teacher, or a system you don't have to build from scratch. Not every path is walked alone. Some are easier walked in line behind someone who's already made the journey.\n\nThe Hierophant's shadow is blindly following rules even when they no longer serve — tradition for tradition's own sake, not because it still makes sense. This card's real wisdom isn't in submission; it's in recognizing which knowledge from the past is worth carrying forward, and which it's time to set down.\n\nIn relationships, the Hierophant can signal a formal commitment — a marriage, a vow, public recognition of a bond, or simply a relationship built on shared values. At work, it speaks of structured learning, a certification, a mentor who can save you years of wandering alone. Don't be ashamed to ask for help from someone who's already walked the path. That isn't weakness. It's wisdom.",
    },
  },
  {
    key: "lovers",
    number: 6,
    name: { sl: "Ljubimca", en: "The Lovers" },
    keywords: { sl: ["Izbira", "Povezava", "Usklajenost"], en: ["Choice", "Union", "Alignment"] },
    meaning: {
      sl: "Ni vsaka odločitev enostavna, a nekatere te pripeljejo domov, k sebi.",
      en: "Not every decision is easy, but some lead you home, to yourself.",
    },
    profile: {
      sl: "Dva stojita naga, brez sramu, angel bdi nad njima z rokami, razprtimi kot blagoslov. Za njima drevo znanja in drevo življenja — izbira med tem, kar je varno, in tem, kar je resnično. Ta karta ni samo o romantiki. Je o vsakem trenutku, ko se moraš odločiti, kaj je usklajeno s tabo. Gora med njima se dviga v ozadju — opomnik, da vsaka resnična povezava zahteva tudi vzpon, ne le začetno privlačnost.\n\nKadar se pojavi, ta karta govori o pomembni izbiri — med dvema potema, dvema ljudema, dvema deloma sebe. Ne izbiraj tistega, kar je pričakovano. Izberi tisto, kar odmeva globoko, tudi če je težje razložiti zakaj. Prava povezava, s človekom ali s poklicno potjo, se čuti kot prepoznavanje, ne kot kompromis.\n\nSenca Ljubimcev je izbira, narejena iz strahu pred samoto, ne iz resnične usklajenosti — ostajanje z nekom ali nečim, ker je znano, ne ker je pravo. Prava povezava ne zahteva, da se skrčiš vase, da bi ustrezal. Zahteva, da se pokažeš cel, in zaupaš, da je to dovolj.\n\nV odnosih ta karta pogosto naznanja globoko, pomembno vez — ne nujno lahko, a resnično. Pri delu lahko govori o partnerstvu, sodelovanju, ali izbiri med dvema smerema kariere, ki obe kličeta. Poslušaj, katera izbira te pusti bolj celega, ne katera je bolj varna. Duša redko laže, ko gre za to, kaj resnično hoče.",
      en: "Two stand naked, without shame, an angel watching over them, arms spread like a blessing. Behind them, the tree of knowledge and the tree of life — a choice between what's safe and what's true. This card isn't only about romance. It's about every moment you have to decide what's actually aligned with you. A mountain rises between them in the background — a reminder that any real connection also demands a climb, not just an initial spark.\n\nWhen this card appears, it speaks of an important choice — between two paths, two people, two parts of yourself. Don't choose what's expected. Choose what resonates deeply, even if it's harder to explain why. A real connection, with a person or a calling, feels like recognition, not compromise.\n\nThe Lovers' shadow is a choice made out of fear of being alone, not out of real alignment — staying with someone or something because it's familiar, not because it's right. A real connection doesn't require you to shrink yourself to fit. It requires you to show up whole, and trust that's enough.\n\nIn relationships, this card often signals a deep, significant bond — not necessarily easy, but real. At work, it can speak of a partnership, a collaboration, or a choice between two career directions that both genuinely call to you. Listen to which choice leaves you feeling more whole, not which feels safer. The soul rarely lies about what it actually wants.",
    },
  },
  {
    key: "chariot",
    number: 7,
    name: { sl: "Voz", en: "The Chariot" },
    keywords: { sl: ["Volja", "Zmaga", "Nadzor"], en: ["Willpower", "Victory", "Control"] },
    meaning: {
      sl: "Dve sili vlečeta v različne smeri. Zmagaš, ko ju usmeriš k isti točki.",
      en: "Two forces are pulling in different directions. You win when you point them both at the same place.",
    },
    profile: {
      sl: "Voznik stoji v vozu, ki ga vlečeta dve sfingi, ena črna, ena bela — ne povezani z vajetmi, samo z njegovo voljo. Ne gre za silo, gre za usmerjenost. Nad glavo ima zvezde, oklep pod oblačilom pripravljenost. Zmaga ni naključje. Je posledica discipline, uporabljene v pravo smer. Mesto, iz katerega prihaja, ostaja za njim — ne ozira se nazaj, ker ve, da je pot naprej edina, ki ga zanima.\n\nKadar se pojavi, ta karta prinaša moč, da premagaš nasprotujoče si sile — v sebi ali okrog sebe — in stopiš naprej z jasnim namenom. Ni čas za dvom. Je čas, da vzameš vajeti v roke in se premakneš, tudi če se dva dela tebe še vedno ne strinjata popolnoma.\n\nSenca Voza je sila, uporabljena brez smeri — energija, ki hiti naprej, ne da bi vedela, kam. Prava zmaga te karte ni v tem, da premagaš druge, ampak v tem, da uskladiš nasprotujoče si dele sebe dovolj, da se lahko premikajo v isto smer. Voz brez usmerjenega voznika je le nesreča, ki čaka, da se zgodi.\n\nV odnosih ta karta prinaša odločnost — čas, da prevzameš pobudo, namesto da čakaš na znak od drugega. Pri delu naznanja obdobje osredotočene ambicije, v katerem lahko dosežeš več, kot si mislil, če ostaneš zbran. Ne poskušaj nadzorovati vsega naenkrat. Usmeri voljo v eno smer, in sile, ki so se prej zdele nasprotujoče, te bodo peljale naprej, ne narazen.",
      en: "The charioteer stands in a chariot pulled by two sphinxes, one black, one white — not bound by reins, only by his will. This isn't about force, it's about direction. Stars crown his head, armor waits beneath his clothes. Victory isn't chance. It's the result of discipline pointed the right way. The city he came from stays behind him — he doesn't look back, because the only road that interests him is the one ahead.\n\nWhen this card appears, it brings the power to overcome opposing forces — inside you or around you — and move forward with clear intent. This isn't a time for doubt. It's a time to take the reins and move, even if two parts of you still don't fully agree.\n\nThe Chariot's shadow is force without direction — energy rushing forward without knowing where it's headed. This card's real victory isn't about beating others; it's about aligning the opposing parts of yourself enough that they can move in the same direction. A chariot with no one steering is just an accident waiting to happen.\n\nIn relationships, this card brings decisiveness — a time to take the initiative instead of waiting for a sign from the other person. At work, it signals a season of focused ambition, where you can achieve more than you thought possible if you stay collected. Don't try to control everything at once. Point your will in one direction, and the forces that once seemed opposed will carry you forward, not apart.",
    },
  },
  {
    key: "strength",
    number: 8,
    name: { sl: "Moč", en: "Strength" },
    keywords: { sl: ["Nežnost", "Pogum", "Notranja moč"], en: ["Gentleness", "Courage", "Inner power"] },
    meaning: {
      sl: "Prava moč ne kriči. Položi roko na leva glavo in ga umiri z nežnostjo, ne s silo.",
      en: "Real strength doesn't shout. It rests a hand on the lion's head and calms it with gentleness, not force.",
    },
    profile: {
      sl: "Ženska stoji ob levu, roka mirno na njegovi glavi, nad njo znak neskončnosti. Ne bori se z zverjo. Udomačuje jo z ljubeznijo, ne s strahom. To je slika moči, kakršne svet redko uči — tiste, ki ne potrebuje glasnosti, da bi bila resnična. Njena poza je sproščena, skoraj nežna — ni napetosti v njenih rokah, ker ve, da boja sploh ni treba bojevati na silo.\n\nKadar se pojavi, ta karta govori o pogumu, ki se sooča z lastnimi nagoni, strahovi ali jezo — ne tako, da jih zatre, ampak tako, da jih razume in vodi. Nežnost ni šibkost. Kadar te nekaj v tebi želi pobegniti ali napasti, poskusi namesto tega ostati — z mehkobo, ki zdrži.\n\nSenca te karte je potlačevanje — pretvarjanje, da lev sploh ne obstaja, namesto da bi se ga naučil razumeti. Moč, ki jo skrivaš pred sabo, se prej ali slej izrazi na način, ki ga ne izbereš sam. Prava Moč ne pomeni, da nimaš divjih nagonov. Pomeni, da veš, kako živeti z njimi, ne da bi te vodili.\n\nV odnosih ta karta prinaša potrpežljivost s tistim, kar je pri drugem težko sprejeti — sposobnost, da ostaneš mehak, tudi kadar bi bilo lažje reagirati ostro. Pri delu govori o vztrajnosti brez sile, o tem, da nadaljuješ mirno, tudi kadar okoliščine kličejo k paniki. Tvoja največja moč ta teden ni v tem, koliko lahko prenašaš, ampak v tem, kako nežno se lahko soočiš s tem, česar se najbolj bojiš.",
      en: "A woman stands beside a lion, her hand resting calmly on its head, the infinity symbol above her. She doesn't fight the beast. She tames it with love, not fear. This is a picture of strength the world rarely teaches — the kind that doesn't need volume to be real. Her posture is relaxed, almost gentle — there's no tension in her hands, because she knows this isn't a battle that needs to be won by force.\n\nWhen this card appears, it speaks of the courage to face your own instincts, fears, or anger — not by suppressing them, but by understanding and guiding them. Gentleness isn't weakness. When something in you wants to flee or attack, try staying instead — with a softness that holds.\n\nThis card's shadow is suppression — pretending the lion doesn't exist at all, instead of learning to understand it. Strength you hide from yourself eventually expresses itself in ways you don't get to choose. Real Strength doesn't mean you have no wild instincts. It means you know how to live alongside them without being ruled by them.\n\nIn relationships, this card brings patience with what's hard to accept in another person — the ability to stay soft even when it would be easier to react sharply. At work, it speaks of persistence without force, of continuing calmly even when circumstances call for panic. Your greatest strength this season isn't how much you can endure, but how gently you can face what you fear most.",
    },
  },
  {
    key: "hermit",
    number: 9,
    name: { sl: "Puščavnik", en: "The Hermit" },
    keywords: { sl: ["Samota", "Notranje iskanje", "Modrost"], en: ["Solitude", "Inner search", "Wisdom"] },
    meaning: {
      sl: "Svetilka, ki jo nosi, ne razsvetljuje poti drugim. Najprej razsvetli njegovo lastno.",
      en: "The lantern he carries doesn't light the way for others first. It lights his own.",
    },
    profile: {
      sl: "Puščavnik stoji sam na vrhu gore, svetilka v roki, palica za oporo. Ne beži pred svetom — umika se vanj, v tišino, kjer se glasovi vseh drugih naposled utišajo in ostane samo njegov lasten. Njegova luč je majhna, a zadostuje, da vidi naslednji korak. Ne kaže poti množici — kaže jo samo tistemu, ki jo je pripravljen iskati sam.\n\nKadar se pojavi, ta karta vabi k umiku — od hrupa, od pričakovanj drugih, od nenehnega odzivanja. Ni to osamljenost, je namerna samota, v kateri lahko najdeš odgovor, ki ga med ljudmi nikoli ne bi slišal. Nekaterih vprašanj se ne da rešiti v družbi. Rabijo tišino, in tebe, samega s sabo.\n\nSenca Puščavnika je izolacija, ki traja predolgo — umik, ki se spremeni v beg pred povezavo samo, ne le pred hrupom. Prava modrost te karte ni v tem, da ostaneš sam za vedno. Je v tem, da se vrneš iz tišine z nečim, kar lahko deliš z drugimi, obogaten, ne izčrpan.\n\nV odnosih Puščavnik lahko pomeni obdobje, ko potrebuješ prostor zase, preden si sposoben biti resnično prisoten za koga drugega. Pri delu govori o raziskovanju, študiju, globokem premisleku, preden narediš naslednjo potezo. Ne siliš se v družbo, dokler nisi pripravljen. Tvoja lastna luč, kakor koli majhna, ti bo pokazala, kdaj je čas, da se vrneš med ljudi.",
      en: "The Hermit stands alone at the top of a mountain, a lantern in one hand, a staff for support. He isn't fleeing the world — he's withdrawing into it, into a silence where everyone else's voices finally quiet down and only his own remains. His light is small, but enough to see the next step. He doesn't light the way for a crowd — only for the one willing to seek it alone.\n\nWhen this card appears, it invites withdrawal — from noise, from other people's expectations, from constantly reacting. This isn't loneliness, it's deliberate solitude, where you can find an answer you'd never hear among people. Some questions can't be solved in company. They need silence, and you, alone with yourself.\n\nThe Hermit's shadow is isolation that lasts too long — withdrawal that turns into fleeing connection itself, not just the noise. This card's real wisdom isn't in staying alone forever. It's in returning from the silence with something you can share with others, enriched, not depleted.\n\nIn relationships, the Hermit can mean a season when you need space for yourself before you're able to be truly present for someone else. At work, it speaks of research, study, deep reflection before your next move. Don't force yourself into company until you're ready. Your own light, however small, will show you when it's time to return among people.",
    },
  },
  {
    key: "wheel-of-fortune",
    number: 10,
    name: { sl: "Kolo Sreče", en: "Wheel of Fortune" },
    keywords: { sl: ["Sprememba", "Cikli", "Usoda"], en: ["Change", "Cycles", "Fate"] },
    meaning: {
      sl: "Kolo se vrti, ne glede na to, ali ga poskušaš ustaviti. Vprašanje je, kako se vrtiš z njim.",
      en: "The wheel turns whether you try to stop it or not. The question is how you turn with it.",
    },
    profile: {
      sl: "Veliko kolo se vrti v zraku, na njem simboli, ki jih ni izumila naša doba — vsak cikel se je že zgodil, v neki obliki, nekomu drugemu prej. Kar je bilo zgoraj, gre navzdol; kar je bilo spodaj, se dvigne. Nič ne ostane isto za vedno, in v tem je pravzaprav olajšanje. Okrog kolesa bedijo štiri bitja, vsako s svojo knjigo — opomnik, da se vsak cikel nekje zapiše, tudi če se zdi, da izgine brez sledu.\n\nKadar se pojavi, ta karta naznanja premik — nekaj, na kar nisi imel popolnega vpliva, se obrne. Ne oklepaj se tega, kar odhaja, in ne boj se tega, kar prihaja. Cikli obstajajo, da se učimo skozi njih, ne da bi jim ušli. Trenutna sreča ali smola ni trajno stanje. Je samo trenutek na kolesu.\n\nSenca te karte je prepričanje, da nimaš nobenega vpliva na lastno usodo — pasivnost, ki čaka, da se kolo obrne samo, namesto da bi sodelovala z njegovim gibanjem. Kolo Sreče se res vrti samo od sebe. A to, kako se držiš nanj in kaj se naučiš na poti, je še vedno tvoja izbira.\n\nV odnosih ta karta naznanja spremembo dinamike — morda konec obdobja negotovosti, morda nepričakovan preobrat, ki odnos postavi na novo. Pri delu govori o priložnosti, ki pride od zunaj, ne kot posledica tvojega neposrednega truda, a jo je vseeno treba zgrabiti. Ne poskušaj nadzorovati kolesa. Nauči se pluti z njim, in vedno bo obstajal naslednji obrat, ki te bo popeljal naprej.",
      en: "A great wheel turns in the air, marked with symbols older than our age — every cycle has already happened, in some form, to someone else before. What was on top goes down; what was below rises. Nothing stays the same forever, and there's real relief in that. Four creatures keep watch around the wheel, each holding a book — a reminder that every cycle is recorded somewhere, even when it seems to vanish without a trace.\n\nWhen this card appears, it signals a shift — something you didn't have full control over is turning. Don't cling to what's leaving, and don't fear what's arriving. Cycles exist so we can learn through them, not escape them. Current luck or misfortune isn't a permanent state. It's just one moment on the wheel.\n\nThis card's shadow is believing you have no influence over your own fate at all — a passivity that waits for the wheel to turn on its own, instead of working with its motion. The Wheel of Fortune really does turn by itself. But how you hold on, and what you learn along the way, is still your choice.\n\nIn relationships, this card signals a change in dynamic — perhaps the end of a period of uncertainty, perhaps an unexpected turn that resets things. At work, it speaks of an opportunity arriving from outside, not as a direct result of your effort, but still worth seizing. Don't try to control the wheel. Learn to ride it, and there will always be another turn carrying you forward.",
    },
  },
  {
    key: "justice",
    number: 11,
    name: { sl: "Pravičnost", en: "Justice" },
    keywords: { sl: ["Ravnovesje", "Resnica", "Posledice"], en: ["Balance", "Truth", "Consequence"] },
    meaning: {
      sl: "Tehtnica ne laže. Kar poseješ, to na koncu tudi vidiš na drugi strani.",
      en: "The scale doesn't lie. What you sow, you eventually see on the other side.",
    },
    profile: {
      sl: "Pravičnost sedi med dvema stebroma, v eni roki meč, v drugi tehtnico. Meč je dvignjen naravnost, brez naklonjenosti kateri koli strani. Ne odloča po čustvih. Odloča po resnici, kakršna je, ne kakršno bi si kdo želel, da bi bila. Njen pogled je miren, skoraj neizprosen — ne zato, ker bi ji bilo vseeno, ampak zato, ker ve, da mora resnica priti pred udobjem.\n\nKadar se pojavi, ta karta vabi k pošteni presoji — do sebe in do drugih. Morda prihaja odločitev, pogodba, ali posledica dejanja, ki si ga že storil. Ne izogibaj se odgovornosti in ne pričakuj, da bo nepravičnost trajala večno. Ravnovesje se vedno vzpostavi, čeprav včasih ne na način ali v času, ki bi ga izbral sam.\n\nSenca te karte je togo sojenje brez usmiljenja — pravilo, uporabljeno brez razumevanja okoliščin, ki so ga oblikovale. Prava pravičnost ne pomeni le kaznovati napako. Pomeni videti celotno sliko, preden izrečeš sodbo, tudi kadar je ta sodba namenjena tebi samemu.\n\nV odnosih Pravičnost prinaša potrebo po poštenosti — priznanju lastnega deleža v konfliktu, ne le tujega. Pri delu naznanja pogodbo, sodni postopek, ali odločitev, ki mora biti sprejeta na podlagi dejstev, ne simpatije. Sprejmi odgovornost za tisto, kar je tvoje, in ne prevzemaj bremena, ki ni. Vesolje vodi natančno knjigovodstvo, tudi kadar se to ne zdi tako.",
      en: "Justice sits between two pillars, a sword in one hand, a scale in the other. The sword is raised straight, favoring no side. She doesn't decide by feeling. She decides by truth as it is, not as anyone might wish it to be. Her gaze is calm, almost unyielding — not because she doesn't care, but because she knows truth has to come before comfort.\n\nWhen this card appears, it invites a fair judgment — of yourself and of others. A decision, a contract, or the consequence of an action you've already taken may be arriving. Don't avoid responsibility, and don't expect unfairness to last forever. Balance always restores itself, though sometimes not in the way or the timing you'd have chosen.\n\nThis card's shadow is rigid judgment without mercy — a rule applied without understanding the circumstances that shaped it. Real justice isn't just about punishing a wrong. It's about seeing the whole picture before passing sentence, even when that sentence is aimed at yourself.\n\nIn relationships, Justice brings a need for honesty — acknowledging your own share in a conflict, not just the other person's. At work, it signals a contract, a legal matter, or a decision that has to be made on facts, not sympathy. Take responsibility for what's actually yours, and don't carry a burden that isn't. The universe keeps precise books, even when it doesn't look that way.",
    },
  },
  {
    key: "hanged-man",
    number: 12,
    name: { sl: "Obešenec", en: "The Hanged Man" },
    keywords: { sl: ["Premor", "Nova perspektiva", "Predaja"], en: ["Pause", "New perspective", "Surrender"] },
    meaning: {
      sl: "Svet izgleda drugače, ko ga gledaš narobe. Včasih je to prav tisto, kar potrebuješ videti.",
      en: "The world looks different upside down. Sometimes that's exactly what you need to see.",
    },
    profile: {
      sl: "Obešenec visi za eno nogo z drevesa, obraz miren, skoraj nasmejan. Ni to kazen. Je izbrana predaja — obstanek v neudobnem položaju dovolj dolgo, da se perspektiva obrne. Okoli glave mu sveti tanek sij, znanje, ki ga ne bi dobil na noge postavljen. Druga noga mu je prekrižana za drugo, oblikuje skoraj popolno štirico — obliko, ki se pojavlja skozi cel špil, kadar je nekaj pripravljeno spremeniti obliko.\n\nKadar se pojavi, ta karta pravi: ne siliš naprej. Namesto tega obstani, počakaj, glej stvari z druge strani. To ni čas za odločitve ali dejanja — je čas za predajo temu, česar ne moreš nadzorovati, in za zaupanje, da premor sam po sebi nosi svojo vrednost, tudi če se od zunaj zdi kot nič.\n\nSenca te karte je žrtvovanje brez namena — obtičanje v nelagodju, ne da bi iz njega karkoli pridobil, samo zato, ker se je tako zgodilo. Prava predaja te karte ni pasivna. Je aktivna odločitev, da ostaneš v težkem položaju, dokler ti ne pokaže tega, česar sicer ne bi videl.\n\nV odnosih Obešenec lahko naznanja obdobje čakanja — na odgovor, na jasnost, na to, da druga oseba pride do svojega spoznanja v svojem tempu. Pri delu opozarja, naj ne siliš odločitve, ki še ni zrela. Vsak premor ni izguba časa. Nekateri premori so edini način, da sploh vidiš, kaj je bilo ves čas obrnjeno narobe.",
      en: "The Hanged Man hangs by one leg from a tree, his face calm, almost smiling. This isn't punishment. It's a chosen surrender — staying in an uncomfortable position long enough for perspective to flip. A thin glow lights his head, a knowledge he wouldn't have gained standing upright. His other leg crosses behind it, forming an almost perfect four — a shape that recurs through the deck whenever something is ready to change form.\n\nWhen this card appears, it says: don't push forward. Instead, stay, wait, look at things from the other side. This isn't a time for decisions or action — it's a time for surrendering to what you can't control, and trusting that the pause carries its own value, even if from outside it looks like nothing.\n\nThis card's shadow is sacrifice without purpose — staying stuck in discomfort without gaining anything from it, simply because that's how things turned out. This card's real surrender isn't passive. It's an active decision to remain in a difficult position until it shows you what you otherwise wouldn't see.\n\nIn relationships, the Hanged Man can signal a season of waiting — for an answer, for clarity, for the other person to reach their own realization at their own pace. At work, it warns against forcing a decision that isn't ripe yet. Not every pause is wasted time. Some pauses are the only way to see what's been upside down the whole time.",
    },
  },
  {
    key: "death",
    number: 13,
    name: { sl: "Smrt", en: "Death" },
    keywords: { sl: ["Konec", "Preobrazba", "Novo poglavje"], en: ["Ending", "Transformation", "New chapter"] },
    meaning: {
      sl: "Nekaj mora umreti, da lahko nekaj drugo živi. To ni tragedija — je narava.",
      en: "Something has to die so something else can live. That isn't a tragedy — it's nature.",
    },
    profile: {
      sl: "Smrt jaha belega konja, oklep črn, zastava z rožo, ki cveti kljub vsemu. Za njim vsi enako padejo — kralj, otrok, duhovnik — nihče ni izvzet iz spremembe. Toda za njim vzhaja tudi sonce. Konec ene stvari je vedno začetek naslednje. Reka teče proti temu vzhajajočemu soncu — pot naprej obstaja, tudi če je od tu, kjer stojiš, še ne vidiš.\n\nKadar se pojavi, ta karta redko napoveduje dobesedno smrt — govori o koncu obdobja, odnosa, identitete, ki je služila svojemu namenu in zdaj mora oditi, da nastane prostor za nekaj novega. Ne oklepaj se tega, kar je že mrtvo. Sprememba, ki se zdi kot izguba, je pogosto preobleka za rojstvo.\n\nSenca te karte je zanikanje — poskus, da nekaj, kar je že končano, umetno ohranjaš pri življenju, ker se bojiš praznine, ki bi ostala za sabo. Smrt ne prosi za dovoljenje. Prihaja, kadar je čas, ne kadar smo pripravljeni. A prav v tem je tudi njena milost: ne pusti stvarem trohneti dlje, kot je treba.\n\nV odnosih ta karta lahko naznanja konec faze — ne nujno odnosa samega, pogosto pa konec tega, kakšen je bil do zdaj, da lahko postane nekaj drugega. Pri delu govori o zaključku projekta, vloge ali poglavja kariere. Žaluj, če je treba, a ne ostani predolgo ob grobu tega, kar je minilo. Nekaj novega že čaka, da vzhaja.",
      en: "Death rides a white horse, armor black, a flag bearing a rose that blooms regardless. Everyone falls before him equally — king, child, priest — no one is exempt from change. But behind him, the sun is also rising. The end of one thing is always the beginning of the next. A river flows toward that rising sun — a way forward exists, even if you can't see it yet from where you're standing.\n\nWhen this card appears, it rarely predicts literal death — it speaks of the end of a phase, a relationship, an identity that has served its purpose and now has to leave to make room for something new. Don't cling to what's already gone. Change that feels like loss is often a birth in disguise.\n\nThis card's shadow is denial — trying to artificially keep something alive that's already over, because you fear the emptiness it would leave behind. Death doesn't ask permission. It arrives when it's time, not when we're ready. But that's also its mercy: it doesn't let things rot longer than they need to.\n\nIn relationships, this card can signal the end of a phase — not necessarily the relationship itself, but often the end of what it has been until now, so it can become something else. At work, it speaks of the close of a project, a role, or a chapter of your career. Grieve if you need to, but don't linger too long at the grave of what has passed. Something new is already waiting to rise.",
    },
  },
  {
    key: "temperance",
    number: 14,
    name: { sl: "Zmernost", en: "Temperance" },
    keywords: { sl: ["Ravnovesje", "Potrpežljivost", "Zlivanje"], en: ["Balance", "Patience", "Blending"] },
    meaning: {
      sl: "Ne obe skrajnosti naenkrat. Nekje vmes je tekočina, ki se ne razlije.",
      en: "Not both extremes at once. Somewhere in between is the liquid that doesn't spill.",
    },
    profile: {
      sl: "Angel stoji z eno nogo v vodi, eno na kopnem, in preliva tekočino iz ene čaše v drugo, brez da bi izgubil kapljo. Ne hiti. Ne razdvaja sveta na črno in belo — najde tretji prostor, kjer se stvari, ki se zdijo nasprotujoče, lahko srečajo. Pot za njim vodi proti gorovju in vzhajajočemu soncu — počasna, a jasna smer, brez potrebe po bližnjicah.\n\nKadar se pojavi, ta karta vabi k potrpežljivosti in zmernosti — v čustvih, ki jih morda želiš izraziti naenkrat, v odločitvah, ki se zdijo kot 'vse ali nič'. Poišči srednjo pot. Nekaj, kar traja, redko nastane v naglici. Mešanje, usklajevanje, počasno prilagajanje — to je alkimija te karte.\n\nSenca Zmernosti je izogibanje odločitvi v imenu 'ravnovesja' — nikoli se ne zavezati ničemur, iz strahu, da bi izgubil nekaj drugega. Prava zmernost ne pomeni izogibanja skrajnostim za vsako ceno. Pomeni znati, kdaj se popolnoma predati nečemu, in kdaj počakati, da se stvari umirijo same.\n\nV odnosih ta karta prinaša zdravljenje po nesoglasju — sposobnost, da najdeš skupni jezik, tudi ko se zdi, da sta si s partnerjem preveč različna. Pri delu govori o postopnem, vztrajnem napredku, ne o hitrih zmagah. Ne poskušaj popraviti vsega naenkrat. Po malem, dan za dnem, se sestavi tisto, kar bo na koncu držalo obliko.",
      en: "An angel stands with one foot in water, one on land, pouring liquid from one cup to another without losing a drop. There's no rush here. The world isn't split into black and white — she finds the third space where things that seem opposed can meet. The path behind her leads toward the mountains and a rising sun — a slow but clear direction, with no need for shortcuts.\n\nWhen this card appears, it invites patience and moderation — in feelings you might want to express all at once, in decisions that feel like \"all or nothing.\" Look for the middle path. Something built to last is rarely made in a hurry. Blending, balancing, slow adjustment — that's this card's alchemy.\n\nTemperance's shadow is avoiding a decision in the name of \"balance\" — never committing to anything, out of fear of losing something else. Real temperance doesn't mean avoiding extremes at any cost. It means knowing when to give yourself fully to something, and when to wait for things to settle on their own.\n\nIn relationships, this card brings healing after disagreement — the ability to find common ground, even when you and a partner seem too different. At work, it speaks of gradual, steady progress, not quick wins. Don't try to fix everything at once. Bit by bit, day by day, is how something that actually holds its shape gets built.",
    },
  },
  {
    key: "devil",
    number: 15,
    name: { sl: "Vrag", en: "The Devil" },
    keywords: { sl: ["Navezanost", "Senca", "Iluzija ujetosti"], en: ["Attachment", "Shadow", "Illusion of being trapped"] },
    meaning: {
      sl: "Verige okoli vratu para so tako ohlapne, da bi jih lahko sneli. Nihče ju ne drži tam razen njiju samih.",
      en: "The chains around the couple's necks are loose enough to slip off. Nothing holds them there but themselves.",
    },
    profile: {
      sl: "Vrag sedi nad parom, oba priklenjena, a ohlapno — verigi bi lahko zdrsnili čez glavo, če bi le poskusila. Ne gre za resnično ujetost. Gre za navado, strah, odvisnost, prepričanje, da nimata izbire. Vrag ne prisili nikogar. Samo izkorišča to, kar že sama izbereta znova in znova. Njegova bakla gori navzdol, ne navzgor — luč, obrnjena stran od resnice, namesto proti njej.\n\nKadar se pojavi, ta karta razkriva vzorec, ki te drži ujetega — razmerje, ki ti ne služi, navado, ki jo ponavljaš, misel, ki te prepričuje, da si nemočen. Resnica je neprijetna, a osvobajajoča: veriga je snemljiva. Prvi korak k svobodi je priznati, da si tam ostal po lastni izbiri.\n\nSenca te karte je že sama karta — a tudi znotraj sence obstaja senca globlje: obsojanje samega sebe za to, da si sploh ostal ujet, namesto da bi si preprosto priznal in šel naprej. Vrag ne zahteva popolnosti od tistega, ki se osvobaja. Zahteva samo pripravljenost, da poskusiš sneti verigo, tudi če ne veš, kaj pride potem.\n\nV odnosih ta karta lahko razkrije nezdravo navezanost — strast, ki meji na odvisnost, ali razmerje, ki ga oba ohranjata iz strahu pred samoto, ne iz ljubezni. Pri delu opozarja na past zlatih verig — udobno slabo situacijo, iz katere se ne premakneš, ker je poznana. Poglej navzdol. Veriga je res tam. A tvoja roka je prosta, da jo dvigneš čez glavo, kadar boš pripravljen.",
      en: "The Devil looms over a couple, both chained, but loosely — the chains could slip over their heads if they only tried. This isn't real captivity. It's habit, fear, dependency, the belief that they have no choice. The Devil forces no one. He simply exploits what they keep choosing, again and again. His torch burns downward, not upward — a light turned away from the truth, instead of toward it.\n\nWhen this card appears, it reveals a pattern that's keeping you trapped — a relationship that doesn't serve you, a habit you keep repeating, a thought convincing you that you're powerless. The truth is uncomfortable but freeing: the chain slips off. The first step to freedom is admitting you stayed there by choice.\n\nThis card's shadow is the card itself — but even within that shadow there's a deeper one: judging yourself for having stayed trapped at all, instead of simply admitting it and moving on. The Devil doesn't demand perfection from someone freeing themselves. It only demands a willingness to try lifting the chain, even without knowing what comes after.\n\nIn relationships, this card can reveal an unhealthy attachment — a passion bordering on dependency, or a relationship both people maintain out of fear of being alone, not out of love. At work, it warns of the golden-handcuffs trap — a comfortable bad situation you don't leave because it's familiar. Look down. The chain really is there. But your hand is free to lift it over your head, whenever you're ready.",
    },
  },
  {
    key: "tower",
    number: 16,
    name: { sl: "Stolp", en: "The Tower" },
    keywords: { sl: ["Nenaden preobrat", "Razkritje", "Podiranje"], en: ["Sudden upheaval", "Revelation", "Collapse"] },
    meaning: {
      sl: "Strela ne uniči tega, kar je bilo trdno. Razkrije, kar je že bilo votlo.",
      en: "Lightning doesn't destroy what was solid. It reveals what was already hollow.",
    },
    profile: {
      sl: "Strela udari v vrh stolpa, krona odleti, dve figuri padata skozi zrak. Zgradba, za katero so mislili, da bo večna, se podre v enem samem trenutku. To je najbolj boleča karta v špilu — a tudi eno najbolj potrebnih. Plameni švigajo iz oken, ki so bila nekoč varen dom — dokaz, da je bilo nekaj notri že dolgo v plamenih, še preden je kdo videl dim od zunaj.\n\nKadar se pojavi, ta karta napoveduje nenaden preobrat, ki ga nisi izbral — konec iluzije, razkritje resnice, ki jo je bilo lažje ne videti. Ne gre za kaznovanje. Gre za osvoboditev od strukture, ki je bila zgrajena na napačnih temeljih. Kar se poruši, se je moralo podreti, da se lahko zgradi nekaj resničnega na njegovem mestu.\n\nSenca te karte ni v padcu samem, ampak v tem, kako dolgo si vedel, da bo prišel, in ga vseeno ignoriral. Stolp redko udari brez opozorila. Prej pošlje razpoke, tihe znake, ki jih je bilo lažje spregledati kot soočiti se z njimi. Ko strela udari, je to samo zadnji, najglasnejši od vseh opozoril.\n\nV odnosih ta karta lahko naznanja razkritje, ki spremeni vse — resnico, ki je bila predolgo skrita, ali konec nečesa, kar je od zunaj izgledalo trdno. Pri delu opozarja na nenaden preobrat, izgubo, ki je nisi predvidel. Ne poskušaj obnoviti stolpa v isti obliki. Nekaj, kar je padlo, je bilo namenjeno padcu — da lahko na praznem prostoru zraste nekaj, kar bo tokrat zgrajeno na trdnejših temeljih.",
      en: "Lightning strikes the top of a tower, the crown flies off, two figures fall through the air. A structure believed to be permanent collapses in a single moment. This is the most painful card in the deck — and also one of the most necessary. Flames leap from windows that were once a safe home — proof that something inside had been burning for a long time before anyone saw the smoke from outside.\n\nWhen this card appears, it predicts a sudden upheaval you didn't choose — the end of an illusion, the revelation of a truth that was easier not to see. This isn't punishment. It's liberation from a structure built on the wrong foundation. What falls had to fall, so something real could be built in its place.\n\nThis card's shadow isn't in the fall itself, but in how long you knew it was coming and ignored it anyway. The Tower rarely strikes without warning. It sends cracks first, quiet signs that were easier to overlook than to face. When the lightning strikes, it's only the last, loudest of all the warnings.\n\nIn relationships, this card can signal a revelation that changes everything — a truth kept hidden too long, or the end of something that looked solid from outside. At work, it warns of a sudden reversal, a loss you didn't see coming. Don't try to rebuild the tower in the same shape. Something that fell was meant to fall — so that on the empty ground, something built on sturdier foundations can grow this time.",
    },
  },
  {
    key: "star",
    number: 17,
    name: { sl: "Zvezda", en: "The Star" },
    keywords: { sl: ["Upanje", "Obnova", "Vodilna luč"], en: ["Hope", "Renewal", "A guiding light"] },
    meaning: {
      sl: "Po nevihti Stolpa pride tišina, in v tišini ena sama luč, ki kaže pot naprej.",
      en: "After the Tower's storm comes silence, and in the silence, one single light showing the way forward.",
    },
    profile: {
      sl: "Ženska kleči ob vodi, gola, brez sramu, in vlije vodo iz dveh vrčev — enega nazaj v vodo, drugega na zemljo. Nad njo sedem manjših zvezd in ena velika, vodilna. Po vsem, kar je Stolp podrl, prihaja ta karta kot dih po dolgem zadrževanju sape. Za njo ptica sedi na drevesu — znak, da se je življenje že vrnilo tja, kjer se je zdelo, da ni ostalo ničesar.\n\nKadar se pojavi, ta karta prinaša upanje, ki ni naivno — je zasluženo, po nečem, kar si preživel. Zaupaj, da se stvari izboljšujejo, tudi če počasi. Ta ni čas za dvom vase. Nekje daleč gori luč, ki te vodi, tudi kadar je ne vidiš popolnoma jasno. Nadaljuj v njeno smer.\n\nSenca Zvezde je upanje, ki postane pasivno čakanje na čudež, namesto tiho dejanje vsak dan znova. Ženska ob vodi ne sedi pri miru — nenehno vliva, neguje, obnavlja. Njeno upanje je dejanje, ne samo občutek. Razlika med sanjarjenjem in resničnim upanjem je natanko v tem, da drugo zahteva, da nekaj narediš, medtem ko čakaš.\n\nV odnosih Zvezda prinaša ranljivost, ki ni več nevarna — sposobnost, da se znova pokažeš tak, kakršen si, po tem, ko te je nekaj že ranilo. Pri delu naznanja obdobje po krizi, ko se stvari počasi, a zanesljivo obračajo na bolje. Verjemi, da si vreden tega upanja. Zvezde ne svetijo samo za tiste, ki so že prišli do cilja. Svetijo tudi, in predvsem, tistim, ki so še na poti.",
      en: "A woman kneels by the water, naked, without shame, pouring water from two jugs — one back into the water, one onto the earth. Above her, seven small stars and one great, guiding one. After everything the Tower tore down, this card arrives like a breath after holding it too long. Behind her, a bird sits in a tree — a sign that life has already returned to a place that seemed to have nothing left.\n\nWhen this card appears, it brings hope that isn't naive — it's earned, after something survived. Trust that things are getting better, even slowly. This isn't a time to doubt yourself. Somewhere far off a light is guiding you, even when you can't see it perfectly clearly. Keep moving toward it.\n\nThe Star's shadow is hope that turns into passively waiting for a miracle, instead of a quiet action repeated every day. The woman by the water doesn't sit still — she keeps pouring, tending, replenishing. Her hope is an action, not just a feeling. The difference between wishful thinking and real hope is exactly that: real hope requires you to do something while you wait.\n\nIn relationships, the Star brings a vulnerability that's no longer dangerous — the ability to show up as yourself again, after something has already hurt you. At work, it signals a season after a crisis, when things are slowly but surely turning for the better. Believe you're worthy of this hope. The stars don't only shine for those who've already reached the goal. They shine for, and especially for, those still on the way.",
    },
  },
  {
    key: "moon",
    number: 18,
    name: { sl: "Luna", en: "The Moon" },
    keywords: { sl: ["Negotovost", "Podzavest", "Iluzija"], en: ["Uncertainty", "Subconscious", "Illusion"] },
    meaning: {
      sl: "Pot skozi noč je resnična, tudi če ne vidiš, kam pelje. Nadaljuj, korak za korakom.",
      en: "The path through the night is real, even if you can't see where it leads. Keep walking, one step at a time.",
    },
    profile: {
      sl: "Luna sveti nad potjo, ki vodi med dvema stolpoma, v neznano. Pes in volk zavijata vanjo, rak se plazi iz vode — vse, kar je skrito, se ponoči prebudi. To je karta senc, sanj, strahov, ki nimajo popolnoma jasne oblike podnevi. Luna sama nosi obraz, iz katerega kapljajo solze svetlobe — celo vodilna luč te noči je nepopolna, negotova, sama v procesu spreminjanja.\n\nKadar se pojavi, ta karta opozarja, da stvari morda niso takšne, kot se zdijo — informacije so nepopolne, čustva zmedena, pot ni povsem jasna. Ne siliš k jasnosti, ki je še ni. Namesto tega zaupaj intuiciji, ki vidi v temi bolje kot razum. Negotovost ni znak, da si na napačni poti. Je samo del noči, skozi katero moraš iti.\n\nSenca te karte je izguba v lastnih strahovih — pošasti, ki jih ustvari um, postanejo bolj resnične od dejanske nevarnosti. Pes in volk pravzaprav zavijata k isti luni. Strah in domišljija imata isti izvor. Nauči se razlikovati med resničnim opozorilom in senco, ki jo je ustvarila samo tvoja utrujenost.\n\nV odnosih Luna lahko naznanja zmedo — nekaj se ne izreka jasno, nesporazum, ki izvira iz nedorečenosti, ne zlonamernosti. Pri delu opozarja, naj ne podpišeš ali odločiš ničesar pomembnega, dokler se megla ne razkadi. Nekatere resnice se pokažejo šele z jutranjo svetlobo. Do takrat zaupaj koraku za korakom, tudi če pot pred tabo ni v celoti razsvetljena.",
      en: "The Moon shines over a path leading between two towers, into the unknown. A dog and a wolf howl at it, a crab crawls from the water — everything hidden wakes at night. This is the card of shadows, dreams, and fears that don't have a fully clear shape in daylight. The Moon itself wears a face dripping tears of light — even the guiding light of this night is imperfect, uncertain, itself still in the process of changing.\n\nWhen this card appears, it warns that things may not be as they seem — information is incomplete, feelings are tangled, the path isn't fully clear. Don't force a clarity that isn't there yet. Instead, trust the intuition that sees better in the dark than reason does. Uncertainty isn't a sign you're on the wrong path. It's just part of the night you have to walk through.\n\nThis card's shadow is getting lost in your own fears — monsters created by the mind become more real than the actual danger. The dog and the wolf are actually howling at the same moon. Fear and imagination share the same source. Learn to tell the difference between a genuine warning and a shadow created only by your own exhaustion.\n\nIn relationships, the Moon can signal confusion — something left unsaid, a misunderstanding born of vagueness, not malice. At work, it warns against signing or deciding anything important until the fog clears. Some truths only reveal themselves in the morning light. Until then, trust one step at a time, even if the path ahead isn't fully lit.",
    },
  },
  {
    key: "sun",
    number: 19,
    name: { sl: "Sonce", en: "The Sun" },
    keywords: { sl: ["Radost", "Jasnost", "Uspeh"], en: ["Joy", "Clarity", "Success"] },
    meaning: {
      sl: "Ni razloga skrivati se v senci, ko je nebo tako jasno.",
      en: "There's no reason to hide in the shade when the sky is this clear.",
    },
    profile: {
      sl: "Otrok jaha belega konja pod velikim, žarečim soncem, roke razprte, sončnice cvetijo za njim. Nič skritega, nič v senci — to je najbolj neposredno vesela karta v celotnem špilu. Radost tukaj ni naivnost. Je zaslužena preprostost, po vsem, kar je bilo prej. Rdeča zastava plapola v vetru, brez strahu, brez potrebe po obrambi — nič se ne skriva, ker ni ničesar več, česar bi se bilo treba sramovati.\n\nKadar se pojavi, ta karta prinaša jasnost, uspeh, in pristno veselje — v projektu, ki končno obrodi sadove, v odnosu, ki se počuti lahkoten, v tebi samem, ko se počutiš spet cel. Dovoli si uživati brez občutka krivde, brez čakanja na naslednjo skrb. Ta trenutek toplote je zaslužen. Sprejmi ga v celoti.\n\nSenca te karte je redka — Sonce nima veliko teme v sebi. Če sploh obstaja past, je to pretirana samozavest, ki pozabi na ranljivost drugih, ker je sama tako polna svetlobe. Deli svojo radost, ne razkazuj je. Sonce, ki sveti na vse enako, je lepše od tistega, ki sveti samo nase.\n\nV odnosih ta karta prinaša lahkotnost, smeh, veselje brez zapletov — obdobje, ko je ljubezen preprosta, ne zapletena. Pri delu naznanja priznanje, uspeh, viden rezultat truda. Ne bodi skromen glede tega, kar si dosegel. Otrok na konju se ne opravičuje za svojo radost. Tudi ti se ne rabiš.",
      en: "A child rides a white horse under a great, glowing sun, arms open, sunflowers blooming behind. Nothing hidden, nothing in shadow — this is the most directly joyful card in the entire deck. The joy here isn't naive. It's an earned simplicity, after everything that came before. A red flag flutters in the wind, without fear, without needing to defend anything — nothing is hidden, because there's nothing left to be ashamed of.\n\nWhen this card appears, it brings clarity, success, and genuine joy — in a project finally bearing fruit, in a relationship that feels light, in yourself, feeling whole again. Let yourself enjoy it without guilt, without waiting for the next worry. This warmth is earned. Receive it fully.\n\nThis card's shadow is rare — the Sun doesn't carry much darkness in it. If there's a trap at all, it's an excess of confidence that forgets other people's vulnerability, because it's so full of its own light. Share your joy, don't flaunt it. A sun that shines equally on everyone is more beautiful than one that shines only on itself.\n\nIn relationships, this card brings lightness, laughter, joy without complications — a season when love is simple, not tangled. At work, it signals recognition, success, a visible result of your effort. Don't be modest about what you've achieved. The child on the horse doesn't apologize for its joy. You don't have to either.",
    },
  },
  {
    key: "judgement",
    number: 20,
    name: { sl: "Sodba", en: "Judgement" },
    keywords: { sl: ["Prebujenje", "Odpuščanje", "Klic"], en: ["Awakening", "Forgiveness", "A calling"] },
    meaning: {
      sl: "Trobenta ne sodi. Samo kliče tiste, ki so pripravljeni vstati.",
      en: "The trumpet doesn't judge. It just calls those who are ready to rise.",
    },
    profile: {
      sl: "Angel trobi nad odprtimi grobovi, in mrtvi vstajajo, roke dvignjene, pripravljeni na nekaj novega. To ni kazen. Je klic k prebujenju — trenutek, ko postane nemogoče še naprej ignorirati resnico o sebi ali svojem življenju. Vsi, ki vstajajo, imajo enako izraz na obrazu — ne strahu, ampak olajšanja, kot bi končno slišali nekaj, kar so ves čas čakali.\n\nKadar se pojavi, ta karta vabi k pošteni presoji preteklosti — ne z obsojanjem, ampak z odpuščanjem, tako sebi kot drugim. Nekaj v tebi je pripravljeno vstati iz tega, kar je bilo. Poslušaj klic, tudi če prihaja ob neprijetnem času. Prebujenje ni vedno udobno. A je vedno vredno odziva.\n\nSenca te karte je samoobsojanje, ki se skriva pod krinko 'prebujenja' — nenehno pretresanje preteklih napak, brez da bi kdaj resnično odpustil. Trobenta ne kliče, da bi te kaznovala za to, kdo si bil. Kliče te, da postaneš, kar si zdaj sposoben biti.\n\nV odnosih ta karta lahko naznanja spravo — s partnerjem, s samim sabo, z verzijo sebe, ki jo je bilo lažje obsojati kot razumeti. Pri delu govori o poklicu, ki končno začuti pravi smisel, ali o priznanju za trud, ki je predolgo ostajal neopažen. Odzovi se na klic, tudi če prihaja iz smeri, ki je nisi pričakoval. Nekaj v tebi je čakalo prav na ta trenutek.",
      en: "An angel blows a trumpet over open graves, and the dead rise, arms raised, ready for something new. This isn't punishment. It's a call to awaken — the moment it becomes impossible to keep ignoring the truth about yourself or your life. Everyone rising wears the same expression — not fear, but relief, as if they'd finally heard something they'd been waiting for the whole time.\n\nWhen this card appears, it invites an honest reckoning with the past — not with judgment, but with forgiveness, both of yourself and others. Something in you is ready to rise from what has been. Listen for the call, even if it comes at an inconvenient time. Awakening isn't always comfortable. But it's always worth answering.\n\nThis card's shadow is self-judgment disguised as \"awakening\" — endlessly rehashing past mistakes without ever actually forgiving. The trumpet doesn't call to punish you for who you were. It calls you to become who you're now capable of being.\n\nIn relationships, this card can signal reconciliation — with a partner, with yourself, with a version of you that was easier to judge than to understand. At work, it speaks of a calling that finally feels like it makes real sense, or recognition for effort that went unnoticed for too long. Answer the call, even if it comes from a direction you didn't expect. Something in you has been waiting for exactly this moment.",
    },
  },
  {
    key: "world",
    number: 21,
    name: { sl: "Svet", en: "The World" },
    keywords: { sl: ["Dopolnitev", "Celovitost", "Nov cikel"], en: ["Completion", "Wholeness", "A new cycle"] },
    meaning: {
      sl: "Krog se zapre. In v istem trenutku se že odpre naslednji.",
      en: "The circle closes. And in the same moment, the next one is already opening.",
    },
    profile: {
      sl: "Figura pleše sredi lovorovega venca, obdana s štirimi bitji vogalov sveta — bik, lev, orel, človek. Vse je tukaj, vse je povezano, nič ne manjka. To je zadnja karta Velikih Arkan, dopolnitev dolgega potovanja, ki se je začelo z Norcem na robu prepada. V vsaki roki drži palico — simbol ravnovesja, doseženega ne z izogibanjem skrajnostim, ampak z združitvijo vsega, kar je bilo prej, v eno samo, celo gibanje.\n\nKadar se pojavi, ta karta naznanja zaključek — cikel, projekt, poglavje življenja, ki je prišlo do svojega naravnega konca, uspešno. Praznuj to, kar si dosegel. A vedi tudi, da vsak konec nosi seme naslednjega začetka. Svet se ne ustavi. Samo zavrti se naprej, v nov krog, z vsem, kar si se naučil, že vgrajenim vase.\n\nSenca te karte je redkokdaj njena lastna — pojavi se, kadar nekdo ne prizna zaključka, ki je že tu, in se oklepa poglavja, ki je že napisano do konca. Svet ne kaznuje tistega, ki se ustavi, da bi praznoval. Kaznuje samo tistega, ki noče nikoli reči, da je nekaj dokončano.\n\nV odnosih ta karta naznanja globoko izpolnitev — povezavo, ki se počuti celo, brez manjkajočih delov. Pri delu govori o zaključku, ki je dokaz tvoje rasti od prve karte do te zadnje. Ustavi se za trenutek. Poglej, kako daleč si prišel. In ko boš pripravljen, se Norec spet pojavi na obzorju, s prazno culo in pripravljen na novo pot.",
      en: "A figure dances inside a laurel wreath, surrounded by the four creatures of the world's corners — bull, lion, eagle, human. Everything is here, everything connected, nothing missing. This is the final card of the Major Arcana, the completion of the long journey that began with the Fool at the cliff's edge. She holds a wand in each hand — a symbol of balance achieved not by avoiding extremes, but by uniting everything that came before into one single, whole movement.\n\nWhen this card appears, it announces a completion — a cycle, a project, a chapter of life that has reached its natural end, successfully. Celebrate what you've achieved. But know too that every ending carries the seed of the next beginning. The world doesn't stop. It just turns forward, into a new circle, with everything you've learned already built into you.\n\nThis card's shadow is rarely its own — it shows up when someone refuses to acknowledge a completion that's already here, clinging to a chapter that's already been written to its end. The world doesn't punish someone who stops to celebrate. It only punishes someone who can never say something is finished.\n\nIn relationships, this card signals deep fulfillment — a connection that feels whole, with no missing pieces. At work, it speaks of a completion that proves your growth from the very first card to this last one. Pause for a moment. Look at how far you've come. And when you're ready, the Fool appears again on the horizon, bundle empty, ready for a new road.",
    },
  },
];

export function getCardOfTheDayKey(): string {
  const now = new Date();
  const start = Date.UTC(now.getUTCFullYear(), 0, 0);
  const diff = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()) - start;
  const dayOfYear = Math.floor(diff / 86400000);
  return TAROT_CARDS[dayOfYear % TAROT_CARDS.length].key;
}
