import type { CardText } from "./tarotData";

/**
 * Italian text for the 22 Major Arcana. Same readings as the Slovenian and English in
 * tarotData.ts — same four paragraphs, same images. Mine, not a translator's.
 */
export const TAROT_IT: Record<string, CardText> = {
  fool: {
    name: "Il Matto",
    keywords: ["Nuovo inizio", "Fiducia", "Il salto"],
    meaning: "Il bordo del dirupo non è un segnale per fermarsi. È il segnale che è ora del primo passo.",
    profile:
      "Il Matto sta sul ciglio, un piccolo fagotto in spalla, un cane ai piedi che lo avverte fedelmente — ma lui guarda in alto, non in basso. La strada non la conosce ancora, ed è proprio questo a renderlo libero. Ogni cammino mai percorso è cominciato con qualcuno che non sapeva dove portasse. Il suo fagotto porta solo l'essenziale — tutto il resto è disposto a trovarlo per strada, o a imparare a vivere senza.\n\nQuesta carta non parla di stoltezza, ma di un coraggio che ha solo chi non è ancora stato ferito dall'esperienza. Quando appare, ti invita a entrare nell'ignoto senza il piano completo — a fidarti che le risposte si presenteranno lungo la via. Non è tempo di prudenza. È tempo di saltare.\n\nL'ombra del Matto è l'avventatezza senza alcuna coscienza delle conseguenze — un salto fatto senza nemmeno guardare dove si atterra. La differenza tra coraggio e leggerezza non sta nel gesto, ma nell'essere disposti ad accogliere ciò che arriva, anche se non è quello che ti eri immaginato. Il Matto non promette un atterraggio sicuro. Promette solo che la strada stessa ti insegnerà qualcosa.\n\nNelle relazioni il Matto porta freschezza dove tutto aveva iniziato a sembrare familiare — una nuova conoscenza, un inizio inatteso, la disponibilità ad amare senza assicurarsi contro la perdita. Nel lavoro annuncia un progetto o un'idea che a tutti intorno sembra rischiosa, ma che a te, nella pancia, sembra giusta. Quando questa carta cade nella tua lettura, non chiederti se sei abbastanza pronto. Nessuno sul ciglio di un dirupo lo è mai del tutto. Fai il passo.",
  },
  magician: {
    name: "Il Mago",
    keywords: ["Volontà", "Creazione", "Hai tutti gli strumenti"],
    meaning: "Tutto ciò che ti serve è già sul tavolo davanti a te. La domanda è se allungherai la mano.",
    profile:
      "Il Mago sta dietro un tavolo su cui giacciono tutti e quattro gli strumenti — coppa, spada, bastone, pentacolo — sentimento, pensiero, azione, corpo. Una mano indica il cielo, l'altra la terra: unisce l'idea alla realtà. Qui nulla aspetta il caso. Sa prendere ciò che ha già e farne qualcosa di nuovo. Sopra la sua testa fluttua il segno dell'infinito — un promemoria che la fonte da cui crea non ha limiti, finché sa collegarsi ad essa.\n\nQuando questa carta appare, dice che possiedi già ogni capacità richiesta da questo compito — la questione non è l'abilità, ma l'intenzione. Concentra la volontà su una cosa invece di disperderla su dieci. Il mondo non si muoverà da solo. Ma tu puoi muoverti dentro di esso, proprio ora.\n\nL'ombra del Mago è la manipolazione — l'abilità usata per convincere gli altri di qualcosa che non è vero, invece di creare qualcosa che regge da sé. La vera forza di questa carta non sta nei trucchi, ma nell'allineamento tra ciò che pensi, dici e fai. Quando i tre si allineano, le cose si muovono quasi senza sforzo. Quando non lo fanno, resta solo una recita.\n\nNelle relazioni il Mago significa iniziativa — l'occasione di dire ciò che senti invece di aspettare che sia un altro a fare il primo passo. Nel lavoro annuncia un progetto in cui puoi davvero usare tutte le tue capacità insieme, non una sola. Fidati della tua capacità di comporre qualcosa di intero da pezzi sparsi. Tutto ciò che ti serve è già sul tavolo davanti a te.",
  },
  "high-priestess": {
    name: "La Papessa",
    keywords: ["Intuizione", "Mistero", "Sapere interiore"],
    meaning: "La risposta che cerchi fuori sussurra già dentro di te. Fatti abbastanza silenzio da sentirla.",
    profile:
      "La Papessa siede tra due colonne, una nera e una bianca, ombra e luce, e non sceglie nessuna delle due — resta nel mezzo, dove il mistero si sta ancora formando. Dietro di lei pende un velo sottile; non ti proibisce di guardare, chiede solo che tu sia pronto a vedere. Il suo sapere non è nei libri. È nel silenzio. In grembo tiene un rotolo su cui si legge una parola solo in parte visibile — un promemoria che non ogni sapere è destinato a una comprensione immediata.\n\nQuando questa carta appare, ti invita a fidarti di ciò che ancora non sai spiegare con la ragione. Sai già qualcosa prima di averne prova. Non è tempo di decisioni rumorose o di azioni rapide — è tempo di ascolto. Sogni, presentimenti, segnali del corpo: tutto questo è un linguaggio che vale la pena capire.\n\nL'ombra di questa carta è un ritiro interiore così profondo da perdere il contatto con il mondo intorno — il mistero che diventa isolamento invece che fonte interiore di forza. La Papessa non fugge dal mondo. Sa soltanto che certe risposte non si trovano nel rumore, ma in uno spazio che ti costruisci da solo, lontano dalle aspettative altrui.\n\nNelle relazioni questa carta parla di qualcosa non ancora detto ad alta voce — un sentimento che percepisci ma non sai ancora mettere in parole, o un segreto che qualcun altro porta. Nel lavoro mette in guardia dal forzare una decisione prima di avere il quadro completo. Fidati del silenzio prima della risposta più che della pressione di dover dire qualcosa adesso. La vera chiarezza arriva a chi sa aspettarla.",
  },
  empress: {
    name: "L'Imperatrice",
    keywords: ["Abbondanza", "Creatività", "Cura"],
    meaning: "Ciò che viene curato cresce. Vale per i campi quanto per le persone.",
    profile:
      "L'Imperatrice siede in mezzo a un campo rigoglioso, il grano matura intorno a lei, un fiume scorre lì accanto — tutto ciò che tocca cresce. La sua corona è di stelle, e il suo regno non è stato conquistato ma coltivato. Non forza nulla. Crea semplicemente le condizioni in cui la vita trova da sé la strada verso l'alto. Nei cuscini intorno a lei è inciso il simbolo di Venere — la bellezza non come ornamento, ma come forza a sé.\n\nQuando questa carta appare, parla di un'abbondanza che nasce dalla cura, non dallo sforzo a ogni costo — un progetto creativo, una relazione, un corpo che ha bisogno di attenzione, non di pressione. Torna a legarti al mondo dei sensi: bellezza, sapore, tatto. Qualcosa in te è pronto a fiorire, se gli dai spazio e tempo.\n\nL'ombra dell'Imperatrice è la cura spinta troppo in là, che soffoca invece di nutrire — l'amore che diventa controllo, o la creatività versata in tutti gli altri e mai in sé. Il suo campo è rigoglioso perché sa quando ritrarsi e lasciare che le cose crescano per conto loro. Non ogni cura equivale a intervenire. La cura vera lascia spazio a ciò che ami di crescere a modo suo.\n\nNelle relazioni l'Imperatrice porta calore, sensualità e la disponibilità a dare senza contare quanto torna indietro. Nel lavoro annuncia una stagione in cui un progetto, un'attività o un'idea finalmente dà frutto — visibile, concreto, dopo settimane o mesi di cura. Guarda cosa nella tua vita sta già crescendo in silenzio, anche se non te ne sei accorto. Merita acqua e luce, non solo sorveglianza.",
  },
  emperor: {
    name: "L'Imperatore",
    keywords: ["Struttura", "Autorità", "Solidità"],
    meaning: "La libertà senza forma si dissolve. L'Imperatore sa porre un confine dentro cui qualcosa può durare.",
    profile:
      "L'Imperatore siede su un trono di pietra, l'armatura sotto il manto, lo sguardo fermo, le mani immobili. Dietro di lui montagne che nessuna tempesta ha mai spostato. Non è lì per caso — ha costruito la sua autorità con fatica e disciplina, e ora protegge ciò che ha creato con regole chiare, non con la tirannia. Il suo trono porta teste di ariete — un promemoria che anche lui è stato giovane e impaziente, prima di imparare a governare.\n\nQuando questa carta appare, porta un bisogno di struttura — in un progetto senza cornice, in una relazione che ha bisogno di confini chiari, in te stesso quando sei disperso. Prenditi la responsabilità del tuo regno, qualunque forma abbia. L'ordine non è il contrario della libertà. È il palco di cui la libertà ha bisogno per andare in scena.\n\nL'ombra dell'Imperatore è una rigidità che non ammette eccezioni nemmeno quando servirebbero — un potere che dimentica perché era stato costruito. Una guida vera non governa con la paura, ma con l'affidabilità. Quando senti il bisogno di controllare tutto, chiediti se stai difendendo qualcosa di prezioso o solo la tua inquietudine.\n\nNelle relazioni l'Imperatore porta affidabilità — una persona che mantiene la parola, che crea sicurezza con la costanza e non con i gesti grandiosi. Nel lavoro annuncia un momento in cui prendere la guida, fare un piano chiaro e tenerlo. Costruisci il tuo regno lentamente, pietra su pietra, e non lasciare che lo abbatta la prima folata di dubbio.",
  },
  hierophant: {
    name: "Il Papa",
    keywords: ["Tradizione", "Insegnamento", "Comunità"],
    meaning: "Non devi sempre reinventare la ruota. Alcune risposte esistono già — vai a chiedere.",
    profile:
      "Il Papa siede tra due colonne nel tempio, due discepoli in ascolto davanti a lui. La mano è alzata in benedizione, e il suo sapere è ereditato — passato di generazione in generazione, provato, duraturo. Non gli interessa l'originalità a ogni costo. Gli interessa ciò che funziona davvero. Davanti a lui giacciono due chiavi incrociate — al sapere esterno e a quello interno, a ciò che si impara e a ciò che si risveglia.\n\nQuando questa carta appare, può parlare di mentore, di studio formale, di fede o di una comunità che ti offre appartenenza. Forse è il momento di cercare una guida, un maestro o un sistema che non devi costruire da zero. Non ogni cammino si fa da soli. Alcuni si percorrono più facilmente in fila dietro a chi li ha già fatti.\n\nL'ombra del Papa è seguire le regole alla cieca anche quando non servono più — la tradizione per la tradizione, non perché abbia ancora senso. La vera saggezza di questa carta non sta nella sottomissione, ma nel riconoscere quale sapere del passato merita di essere portato avanti e quale è tempo di posare.\n\nNelle relazioni il Papa può annunciare un impegno formale — un matrimonio, una promessa, il riconoscimento pubblico di un legame, o semplicemente una relazione costruita su valori condivisi. Nel lavoro parla di apprendimento strutturato, di una certificazione, di un mentore che può risparmiarti anni di vagabondaggio solitario. Non vergognarti di chiedere aiuto a chi il cammino l'ha già fatto. Non è debolezza. È saggezza.",
  },
  lovers: {
    name: "Gli Amanti",
    keywords: ["Scelta", "Unione", "Allineamento"],
    meaning: "Non ogni decisione è facile, ma alcune ti portano a casa, da te stesso.",
    profile:
      "Due stanno nudi, senza vergogna, un angelo veglia su di loro con le braccia aperte come una benedizione. Dietro di loro l'albero della conoscenza e l'albero della vita — una scelta tra ciò che è sicuro e ciò che è vero. Questa carta non parla solo d'amore. Parla di ogni momento in cui devi decidere cosa è davvero allineato con te. Sullo sfondo, tra loro, si alza una montagna — un promemoria che ogni legame vero richiede anche una salita, non solo la scintilla iniziale.\n\nQuando questa carta appare, parla di una scelta importante — tra due strade, due persone, due parti di te. Non scegliere ciò che ci si aspetta. Scegli ciò che risuona in profondità, anche se è più difficile spiegare perché. Un legame vero, con una persona o con una vocazione, si sente come riconoscimento, non come compromesso.\n\nL'ombra degli Amanti è una scelta fatta per paura della solitudine e non per vero allineamento — restare con qualcuno o qualcosa perché è familiare, non perché è giusto. Un legame vero non chiede che ti rimpicciolisca per entrare. Chiede che ti mostri intero, e che ti fidi che basti.\n\nNelle relazioni questa carta annuncia spesso un legame profondo e significativo — non necessariamente facile, ma reale. Nel lavoro può parlare di una collaborazione, di una società, o di una scelta tra due direzioni di carriera che ti chiamano entrambe davvero. Ascolta quale scelta ti lascia più intero, non quale sembra più sicura. L'anima mente di rado su ciò che vuole davvero.",
  },
  chariot: {
    name: "Il Carro",
    keywords: ["Volontà", "Vittoria", "Controllo"],
    meaning: "Due forze tirano in direzioni diverse. Vinci quando le punti entrambe verso lo stesso punto.",
    profile:
      "L'auriga sta in un carro trainato da due sfingi, una nera e una bianca — non legate da redini, ma solo dalla sua volontà. Non è questione di forza, è questione di direzione. Le stelle gli incoronano il capo, l'armatura attende sotto la veste. La vittoria non è un caso. È il risultato della disciplina puntata nella direzione giusta. La città da cui viene resta alle sue spalle — non si volta, perché l'unica strada che gli interessa è quella davanti.\n\nQuando questa carta appare, porta la forza di superare forze contrarie — dentro di te o intorno a te — e di andare avanti con intenzione chiara. Non è tempo di dubbio. È tempo di prendere le redini e muoverti, anche se due parti di te non sono ancora del tutto d'accordo.\n\nL'ombra del Carro è la forza senza direzione — energia che corre avanti senza sapere dove. La vera vittoria di questa carta non sta nel battere gli altri, ma nell'allineare abbastanza le parti opposte di te perché possano muoversi nella stessa direzione. Un carro senza nessuno alla guida è solo un incidente che attende di accadere.\n\nNelle relazioni questa carta porta decisione — un momento per prendere l'iniziativa invece di aspettare un segnale dall'altro. Nel lavoro annuncia una stagione di ambizione concentrata, in cui puoi ottenere più di quanto credessi, se resti raccolto. Non cercare di controllare tutto insieme. Punta la volontà in una direzione, e le forze che sembravano opposte ti porteranno avanti invece che a pezzi.",
  },
  strength: {
    name: "La Forza",
    keywords: ["Dolcezza", "Coraggio", "Potere interiore"],
    meaning: "La vera forza non grida. Posa una mano sulla testa del leone e lo calma con la dolcezza, non con la violenza.",
    profile:
      "Una donna sta accanto a un leone, la mano posata con calma sulla sua testa, sopra di lei il simbolo dell'infinito. Non combatte la bestia. La addomestica con l'amore, non con la paura. È un'immagine della forza che il mondo insegna di rado — quella che non ha bisogno di volume per essere vera. La sua postura è rilassata, quasi tenera — nelle mani non c'è tensione, perché sa che questa battaglia non va vinta con la forza.\n\nQuando questa carta appare, parla del coraggio di affrontare i propri istinti, le proprie paure o la propria rabbia — non soffocandoli, ma comprendendoli e guidandoli. La dolcezza non è debolezza. Quando qualcosa in te vuole fuggire o attaccare, prova invece a restare — con una morbidezza che regge.\n\nL'ombra di questa carta è la repressione — fingere che il leone non esista affatto, invece di imparare a capirlo. La forza che nascondi a te stesso prima o poi si esprime in un modo che non scegli tu. La Forza vera non significa non avere istinti selvaggi. Significa saperci convivere senza esserne guidato.\n\nNelle relazioni questa carta porta pazienza verso ciò che nell'altro è difficile accettare — la capacità di restare morbido anche quando sarebbe più facile reagire con durezza. Nel lavoro parla di costanza senza forzature, del continuare con calma anche quando le circostanze invitano al panico. La tua forza più grande in questo periodo non è quanto riesci a sopportare, ma con quanta dolcezza sai affrontare ciò che più temi.",
  },
  hermit: {
    name: "L'Eremita",
    keywords: ["Solitudine", "Ricerca interiore", "Saggezza"],
    meaning: "La lanterna che porta non illumina prima la strada agli altri. Illumina la sua.",
    profile:
      "L'Eremita sta solo in cima a una montagna, una lanterna in mano, un bastone per appoggio. Non fugge dal mondo — si ritira dentro di esso, in un silenzio in cui le voci di tutti gli altri finalmente tacciono e resta solo la sua. La sua luce è piccola, ma basta a vedere il passo successivo. Non illumina la via a una folla — solo a chi è disposto a cercarla da solo.\n\nQuando questa carta appare, invita al ritiro — dal rumore, dalle aspettative altrui, dal reagire continuamente. Non è solitudine subita, è solitudine scelta, in cui puoi trovare una risposta che tra la gente non sentiresti mai. Certe domande non si risolvono in compagnia. Hanno bisogno di silenzio, e di te, solo con te stesso.\n\nL'ombra dell'Eremita è un isolamento che dura troppo — un ritiro che diventa fuga dal legame stesso, non solo dal rumore. La vera saggezza di questa carta non sta nel restare soli per sempre. Sta nel tornare dal silenzio con qualcosa da condividere con gli altri, arricchiti e non svuotati.\n\nNelle relazioni l'Eremita può significare un periodo in cui ti serve spazio per te prima di poter essere davvero presente per qualcun altro. Nel lavoro parla di ricerca, di studio, di riflessione profonda prima della mossa successiva. Non costringerti alla compagnia finché non sei pronto. La tua luce, per quanto piccola, ti mostrerà quando è ora di tornare tra le persone.",
  },
  "wheel-of-fortune": {
    name: "La Ruota della Fortuna",
    keywords: ["Cambiamento", "Cicli", "Destino"],
    meaning: "La ruota gira, che tu provi a fermarla o no. La domanda è come giri insieme a lei.",
    profile:
      "Una grande ruota gira nell'aria, segnata da simboli più antichi della nostra epoca — ogni ciclo è già accaduto, in qualche forma, a qualcun altro prima. Ciò che era in alto scende; ciò che era in basso sale. Nulla resta uguale per sempre, e in questo c'è un vero sollievo. Intorno alla ruota vegliano quattro creature, ciascuna con il suo libro — un promemoria che ogni ciclo viene scritto da qualche parte, anche quando sembra svanire senza lasciare traccia.\n\nQuando questa carta appare, segnala uno spostamento — qualcosa su cui non avevi pieno controllo sta girando. Non aggrapparti a ciò che se ne va e non temere ciò che arriva. I cicli esistono perché impariamo attraverso di essi, non per sfuggirvi. La fortuna o la sfortuna del momento non sono uno stato permanente. Sono solo un istante sulla ruota.\n\nL'ombra di questa carta è credere di non avere alcuna influenza sul proprio destino — una passività che aspetta che la ruota giri da sé, invece di lavorare con il suo movimento. La Ruota della Fortuna gira davvero da sola. Ma come ti tieni e cosa impari lungo il percorso resta una tua scelta.\n\nNelle relazioni questa carta annuncia un cambio di dinamica — forse la fine di un periodo di incertezza, forse una svolta inattesa che rimette tutto in gioco. Nel lavoro parla di un'occasione che arriva da fuori, non come risultato diretto del tuo sforzo, ma che vale comunque la pena afferrare. Non cercare di controllare la ruota. Impara a cavalcarla, e ci sarà sempre un altro giro a portarti avanti.",
  },
  justice: {
    name: "La Giustizia",
    keywords: ["Equilibrio", "Verità", "Conseguenze"],
    meaning: "La bilancia non mente. Ciò che semini, alla fine lo vedi dall'altra parte.",
    profile:
      "La Giustizia siede tra due colonne, in una mano la spada, nell'altra la bilancia. La spada è alzata dritta, senza favorire nessuna parte. Non decide con il sentimento. Decide con la verità com'è, non come qualcuno vorrebbe che fosse. Il suo sguardo è calmo, quasi implacabile — non perché non le importi, ma perché sa che la verità deve venire prima della comodità.\n\nQuando questa carta appare, invita a un giudizio onesto — verso di te e verso gli altri. Forse sta arrivando una decisione, un contratto, o la conseguenza di un'azione che hai già compiuto. Non evitare la responsabilità e non aspettarti che l'ingiustizia duri per sempre. L'equilibrio si ristabilisce sempre, anche se non nel modo o nel tempo che avresti scelto.\n\nL'ombra di questa carta è il giudizio rigido senza misericordia — una regola applicata senza capire le circostanze che l'hanno formata. La vera giustizia non è solo punire un errore. È vedere il quadro intero prima di pronunciare la sentenza, anche quando quella sentenza riguarda te stesso.\n\nNelle relazioni la Giustizia porta un bisogno di onestà — riconoscere la propria parte in un conflitto, non solo quella dell'altro. Nel lavoro annuncia un contratto, una questione legale o una decisione che va presa sui fatti, non sulla simpatia. Assumiti la responsabilità di ciò che è tuo e non portare un peso che non lo è. L'universo tiene una contabilità precisa, anche quando non sembra.",
  },
  "hanged-man": {
    name: "L'Appeso",
    keywords: ["Pausa", "Nuova prospettiva", "Resa"],
    meaning: "Il mondo ha un altro aspetto a testa in giù. A volte è proprio ciò che devi vedere.",
    profile:
      "L'Appeso pende da un albero per una gamba, il viso calmo, quasi sorridente. Non è una punizione. È una resa scelta — restare in una posizione scomoda abbastanza a lungo perché la prospettiva si capovolga. Un tenue bagliore gli illumina il capo, un sapere che in piedi non avrebbe ottenuto. L'altra gamba si incrocia dietro la prima, formando un quattro quasi perfetto — una forma che ritorna in tutto il mazzo ogni volta che qualcosa è pronto a cambiare figura.\n\nQuando questa carta appare, dice: non spingere avanti. Resta invece, aspetta, guarda le cose dall'altro lato. Non è tempo di decisioni o di azioni — è tempo di arrendersi a ciò che non puoi controllare e di fidarti che la pausa porti con sé il proprio valore, anche se da fuori sembra niente.\n\nL'ombra di questa carta è il sacrificio senza scopo — restare bloccati nel disagio senza ricavarne nulla, solo perché è andata così. La vera resa di questa carta non è passiva. È la decisione attiva di restare in una posizione difficile finché non ti mostra ciò che altrimenti non vedresti.\n\nNelle relazioni l'Appeso può annunciare un tempo di attesa — di una risposta, di chiarezza, che l'altra persona arrivi alla propria consapevolezza con i suoi tempi. Nel lavoro mette in guardia dal forzare una decisione non ancora matura. Non ogni pausa è tempo perso. Alcune pause sono l'unico modo per vedere cosa è stato capovolto per tutto il tempo.",
  },
  death: {
    name: "La Morte",
    keywords: ["Fine", "Trasformazione", "Nuovo capitolo"],
    meaning: "Qualcosa deve morire perché qualcos'altro viva. Non è una tragedia — è natura.",
    profile:
      "La Morte cavalca un cavallo bianco, l'armatura nera, un vessillo con una rosa che fiorisce comunque. Davanti a lei tutti cadono allo stesso modo — re, bambino, sacerdote — nessuno è esente dal cambiamento. Ma dietro di lei sorge anche il sole. La fine di una cosa è sempre l'inizio della successiva. Un fiume scorre verso quel sole nascente — una via avanti esiste, anche se da dove sei non la vedi ancora.\n\nQuando questa carta appare, raramente annuncia una morte letterale — parla della fine di una fase, di una relazione, di un'identità che ha servito il suo scopo e ora deve andarsene per far posto a qualcosa di nuovo. Non aggrapparti a ciò che è già morto. Un cambiamento che sembra una perdita è spesso una nascita travestita.\n\nL'ombra di questa carta è la negazione — il tentativo di tenere artificialmente in vita qualcosa di già finito, perché temi il vuoto che lascerebbe. La Morte non chiede permesso. Arriva quando è ora, non quando siamo pronti. Ma proprio in questo sta anche la sua misericordia: non lascia che le cose marciscano più a lungo del necessario.\n\nNelle relazioni questa carta può annunciare la fine di una fase — non necessariamente della relazione, ma spesso la fine di com'è stata finora, perché possa diventare altro. Nel lavoro parla della chiusura di un progetto, di un ruolo, di un capitolo di carriera. Fai il lutto se serve, ma non restare troppo accanto alla tomba di ciò che è passato. Qualcosa di nuovo aspetta già di sorgere.",
  },
  temperance: {
    name: "La Temperanza",
    keywords: ["Equilibrio", "Pazienza", "Mescolare"],
    meaning: "Non entrambi gli estremi insieme. Da qualche parte in mezzo c'è il liquido che non si versa.",
    profile:
      "Un angelo sta con un piede nell'acqua e uno sulla terra, e versa il liquido da una coppa all'altra senza perderne una goccia. Qui non c'è fretta. Il mondo non viene diviso in bianco e nero — trova il terzo spazio in cui possono incontrarsi le cose che sembrano opposte. Il sentiero dietro di lei porta verso i monti e un sole che sorge — una direzione lenta ma chiara, senza bisogno di scorciatoie.\n\nQuando questa carta appare, invita alla pazienza e alla misura — nei sentimenti che vorresti magari esprimere tutti insieme, nelle decisioni che sembrano un «tutto o niente». Cerca la via di mezzo. Ciò che dura nasce di rado nella fretta. Mescolare, accordare, adattare lentamente — è questa l'alchimia di questa carta.\n\nL'ombra della Temperanza è evitare la decisione in nome dell'«equilibrio» — non impegnarsi mai in nulla, per paura di perdere altro. La vera temperanza non significa evitare gli estremi a ogni costo. Significa sapere quando darsi del tutto a qualcosa e quando aspettare che le cose si posino da sole.\n\nNelle relazioni questa carta porta guarigione dopo un disaccordo — la capacità di trovare un linguaggio comune anche quando tu e l'altro sembrate troppo diversi. Nel lavoro parla di progresso graduale e costante, non di vittorie rapide. Non cercare di sistemare tutto in una volta. Poco per volta, giorno dopo giorno, si costruisce ciò che alla fine tiene la forma.",
  },
  devil: {
    name: "Il Diavolo",
    keywords: ["Attaccamento", "Ombra", "Illusione di essere in trappola"],
    meaning: "Le catene attorno al collo della coppia sono abbastanza larghe da sfilarsi. Nulla li trattiene lì se non loro stessi.",
    profile:
      "Il Diavolo incombe su una coppia, entrambi incatenati, ma con catene larghe — scivolerebbero sopra la testa, se solo ci provassero. Non è una prigionia vera. È abitudine, paura, dipendenza, la convinzione di non avere scelta. Il Diavolo non costringe nessuno. Sfrutta solo ciò che loro continuano a scegliere, ancora e ancora. La sua torcia brucia verso il basso, non verso l'alto — una luce voltata via dalla verità invece che verso di essa.\n\nQuando questa carta appare, rivela uno schema che ti tiene in trappola — una relazione che non ti serve, un'abitudine che ripeti, un pensiero che ti convince di essere impotente. La verità è scomoda ma libera: la catena si sfila. Il primo passo verso la libertà è ammettere che sei rimasto lì per scelta.\n\nL'ombra di questa carta è la carta stessa — ma dentro quell'ombra ce n'è una più profonda: giudicarti per esserci rimasto, invece di ammetterlo semplicemente e andare avanti. Il Diavolo non pretende perfezione da chi si libera. Pretende solo la disponibilità a provare a sollevare la catena, anche senza sapere cosa viene dopo.\n\nNelle relazioni questa carta può rivelare un attaccamento malsano — una passione al confine con la dipendenza, o una relazione che entrambi mantengono per paura della solitudine, non per amore. Nel lavoro mette in guardia dalla trappola delle catene d'oro — una comoda situazione sbagliata da cui non ti muovi perché è familiare. Guarda in basso. La catena c'è davvero. Ma la tua mano è libera di sollevarla sopra la testa, quando sarai pronto.",
  },
  tower: {
    name: "La Torre",
    keywords: ["Sconvolgimento improvviso", "Rivelazione", "Crollo"],
    meaning: "Il fulmine non distrugge ciò che era solido. Rivela ciò che era già vuoto.",
    profile:
      "Un fulmine colpisce la cima di una torre, la corona vola via, due figure cadono nell'aria. Una costruzione creduta eterna crolla in un solo istante. È la carta più dolorosa del mazzo — e anche una delle più necessarie. Le fiamme escono da finestre che un tempo erano una casa sicura — prova che qualcosa dentro bruciava da molto prima che da fuori qualcuno vedesse il fumo.\n\nQuando questa carta appare, annuncia uno sconvolgimento improvviso che non hai scelto — la fine di un'illusione, la rivelazione di una verità che era più comodo non vedere. Non è una punizione. È la liberazione da una struttura costruita su fondamenta sbagliate. Ciò che cade doveva cadere, perché al suo posto si potesse costruire qualcosa di vero.\n\nL'ombra di questa carta non sta nella caduta, ma in quanto a lungo hai saputo che sarebbe arrivata e l'hai comunque ignorata. La Torre colpisce di rado senza preavviso. Prima manda crepe, segnali silenziosi che era più facile trascurare che affrontare. Quando il fulmine cade, è solo l'ultimo e il più rumoroso di tutti gli avvertimenti.\n\nNelle relazioni questa carta può annunciare una rivelazione che cambia tutto — una verità tenuta nascosta troppo a lungo, o la fine di qualcosa che da fuori sembrava solido. Nel lavoro mette in guardia da una svolta improvvisa, da una perdita che non avevi previsto. Non cercare di ricostruire la torre nella stessa forma. Ciò che è caduto doveva cadere — perché sul terreno sgombro cresca stavolta qualcosa costruito su fondamenta più salde.",
  },
  star: {
    name: "La Stella",
    keywords: ["Speranza", "Rinnovamento", "Una luce che guida"],
    meaning: "Dopo la tempesta della Torre arriva il silenzio, e nel silenzio una sola luce che mostra la via.",
    profile:
      "Una donna è inginocchiata vicino all'acqua, nuda, senza vergogna, e versa acqua da due brocche — una di nuovo nell'acqua, una sulla terra. Sopra di lei sette piccole stelle e una grande, che guida. Dopo tutto ciò che la Torre ha abbattuto, questa carta arriva come un respiro dopo averlo trattenuto troppo a lungo. Dietro di lei un uccello è posato su un albero — segno che la vita è già tornata dove sembrava non fosse rimasto nulla.\n\nQuando questa carta appare, porta una speranza che non è ingenua — è meritata, dopo qualcosa che hai attraversato. Fidati che le cose stiano migliorando, anche lentamente. Non è tempo di dubitare di te. Da qualche parte lontano arde una luce che ti guida, anche quando non la vedi con perfetta chiarezza. Continua nella sua direzione.\n\nL'ombra della Stella è una speranza che diventa attesa passiva di un miracolo, invece di un gesto silenzioso ripetuto ogni giorno. La donna vicino all'acqua non sta ferma — continua a versare, a curare, a rinnovare. La sua speranza è un atto, non solo un sentimento. La differenza tra il fantasticare e la speranza vera è esattamente questa: la seconda chiede che tu faccia qualcosa mentre aspetti.\n\nNelle relazioni la Stella porta una vulnerabilità che non è più pericolosa — la capacità di mostrarti di nuovo per quello che sei, dopo che qualcosa ti ha già ferito. Nel lavoro annuncia una stagione dopo la crisi, in cui le cose lentamente ma sicuramente volgono al meglio. Credi di essere degno di questa speranza. Le stelle non brillano solo per chi è già arrivato. Brillano anche, e soprattutto, per chi è ancora in cammino.",
  },
  moon: {
    name: "La Luna",
    keywords: ["Incertezza", "Inconscio", "Illusione"],
    meaning: "Il sentiero nella notte è reale, anche se non vedi dove porta. Continua, un passo alla volta.",
    profile:
      "La Luna brilla su un sentiero che passa tra due torri e va verso l'ignoto. Un cane e un lupo le ululano, un granchio striscia fuori dall'acqua — tutto ciò che è nascosto si sveglia di notte. È la carta delle ombre, dei sogni e delle paure che alla luce del giorno non hanno una forma del tutto chiara. La Luna stessa porta un volto da cui gocciolano lacrime di luce — persino la luce che guida questa notte è imperfetta, incerta, essa stessa ancora in mutamento.\n\nQuando questa carta appare, avverte che le cose potrebbero non essere come sembrano — le informazioni sono incomplete, i sentimenti aggrovigliati, il cammino non del tutto chiaro. Non forzare una chiarezza che ancora non c'è. Fidati piuttosto dell'intuizione, che al buio vede meglio della ragione. L'incertezza non è un segno di essere sulla strada sbagliata. È solo parte della notte che devi attraversare.\n\nL'ombra di questa carta è perdersi nelle proprie paure — i mostri creati dalla mente diventano più reali del pericolo effettivo. Il cane e il lupo in realtà ululano alla stessa luna. Paura e immaginazione hanno la stessa sorgente. Impara a distinguere un avvertimento vero da un'ombra creata solo dalla tua stanchezza.\n\nNelle relazioni la Luna può segnalare confusione — qualcosa non detto, un malinteso nato dalla vaghezza e non dalla malizia. Nel lavoro mette in guardia dal firmare o decidere qualcosa di importante prima che la nebbia si diradi. Certe verità si rivelano solo con la luce del mattino. Fino ad allora fidati del passo dopo passo, anche se la strada davanti non è del tutto illuminata.",
  },
  sun: {
    name: "Il Sole",
    keywords: ["Gioia", "Chiarezza", "Successo"],
    meaning: "Non c'è motivo di nascondersi all'ombra quando il cielo è così limpido.",
    profile:
      "Un bambino cavalca un cavallo bianco sotto un grande sole ardente, le braccia aperte, girasoli in fiore alle sue spalle. Nulla di nascosto, nulla in ombra — è la carta più direttamente gioiosa di tutto il mazzo. La gioia qui non è ingenuità. È una semplicità meritata, dopo tutto ciò che è venuto prima. Una bandiera rossa sventola nel vento, senza paura, senza bisogno di difendere nulla — non si nasconde niente, perché non c'è più niente di cui vergognarsi.\n\nQuando questa carta appare, porta chiarezza, successo e gioia sincera — in un progetto che finalmente dà frutto, in una relazione che si sente leggera, in te stesso che ti senti di nuovo intero. Concediti di goderne senza sensi di colpa, senza aspettare la prossima preoccupazione. Questo calore è meritato. Accoglilo per intero.\n\nL'ombra di questa carta è rara — il Sole non porta molta oscurità dentro di sé. Se una trappola esiste, è un eccesso di sicurezza che dimentica la fragilità degli altri, perché è così pieno della propria luce. Condividi la tua gioia, non ostentarla. Un sole che illumina tutti allo stesso modo è più bello di uno che brilla solo su di sé.\n\nNelle relazioni questa carta porta leggerezza, risate, allegria senza complicazioni — una stagione in cui l'amore è semplice, non aggrovigliato. Nel lavoro annuncia riconoscimento, successo, un risultato visibile del tuo impegno. Non essere modesto su ciò che hai ottenuto. Il bambino sul cavallo non si scusa per la sua gioia. Non devi farlo nemmeno tu.",
  },
  judgement: {
    name: "Il Giudizio",
    keywords: ["Risveglio", "Perdono", "Una chiamata"],
    meaning: "La tromba non giudica. Chiama soltanto chi è pronto ad alzarsi.",
    profile:
      "Un angelo suona la tromba sopra tombe aperte, e i morti si alzano, le braccia levate, pronti a qualcosa di nuovo. Non è una punizione. È una chiamata al risveglio — il momento in cui diventa impossibile continuare a ignorare la verità su di sé o sulla propria vita. Tutti quelli che si alzano hanno la stessa espressione — non paura, ma sollievo, come se avessero finalmente sentito qualcosa che aspettavano da sempre.\n\nQuando questa carta appare, invita a fare i conti onestamente con il passato — non con il giudizio, ma con il perdono, verso te stesso e verso gli altri. Qualcosa in te è pronto ad alzarsi da ciò che è stato. Ascolta la chiamata, anche se arriva in un momento scomodo. Il risveglio non è sempre comodo. Ma vale sempre la pena rispondere.\n\nL'ombra di questa carta è l'autocondanna travestita da «risveglio» — rimuginare all'infinito sugli errori passati senza mai perdonare davvero. La tromba non chiama per punirti per chi sei stato. Ti chiama a diventare chi ora sei in grado di essere.\n\nNelle relazioni questa carta può annunciare una riconciliazione — con una persona, con te stesso, con una versione di te che era più facile giudicare che capire. Nel lavoro parla di una vocazione che finalmente acquista un senso vero, o di un riconoscimento per una fatica rimasta troppo a lungo invisibile. Rispondi alla chiamata, anche se arriva da una direzione che non ti aspettavi. Qualcosa in te aspettava proprio questo momento.",
  },
  world: {
    name: "Il Mondo",
    keywords: ["Compimento", "Interezza", "Un nuovo ciclo"],
    meaning: "Il cerchio si chiude. E nello stesso istante il successivo si sta già aprendo.",
    profile:
      "Una figura danza dentro una corona d'alloro, circondata dalle quattro creature degli angoli del mondo — toro, leone, aquila, uomo. Tutto è qui, tutto è collegato, nulla manca. È l'ultima carta degli Arcani Maggiori, il compimento del lungo viaggio cominciato con il Matto sul ciglio del dirupo. In ciascuna mano tiene una bacchetta — simbolo di un equilibrio raggiunto non evitando gli estremi, ma unendo tutto ciò che è venuto prima in un unico movimento intero.\n\nQuando questa carta appare, annuncia un compimento — un ciclo, un progetto, un capitolo di vita giunto alla sua fine naturale, con successo. Festeggia ciò che hai raggiunto. Ma sappi anche che ogni fine porta il seme dell'inizio successivo. Il mondo non si ferma. Gira soltanto avanti, in un nuovo cerchio, con tutto ciò che hai imparato già costruito dentro di te.\n\nL'ombra di questa carta è raramente la sua — compare quando qualcuno non riconosce un compimento che è già qui e si aggrappa a un capitolo ormai scritto fino in fondo. Il Mondo non punisce chi si ferma a festeggiare. Punisce solo chi non sa mai dire che qualcosa è finito.\n\nNelle relazioni questa carta annuncia una profonda pienezza — un legame che si sente intero, senza pezzi mancanti. Nel lavoro parla di un compimento che dimostra la tua crescita dalla primissima carta a quest'ultima. Fermati un momento. Guarda quanta strada hai fatto. E quando sarai pronto, il Matto ricompare all'orizzonte, con il fagotto vuoto e pronto per una nuova strada.",
  },
};
