import type { CardText } from "./tarotData";

/**
 * German text for the 22 Major Arcana. Same readings as the Slovenian and English in
 * tarotData.ts — same four paragraphs, same images. Mine, not a translator's.
 */
export const TAROT_DE: Record<string, CardText> = {
  fool: {
    name: "Der Narr",
    keywords: ["Neuanfang", "Vertrauen", "Der Sprung"],
    meaning: "Die Kante der Klippe ist kein Zeichen anzuhalten. Sie ist ein Zeichen für den ersten Schritt.",
    profile:
      "Der Narr steht am Rand, ein kleines Bündel über der Schulter, ein Hund zu seinen Füßen, der treu warnt — doch er blickt nach oben, nicht nach unten. Den Weg kennt er noch nicht, und genau das macht ihn frei. Jede Straße, die je jemand gegangen ist, begann mit jemandem, der nicht wusste, wohin sie führt. Sein Bündel trägt nur das Nötigste — alles andere will er unterwegs finden oder lernen, ohne es zu leben.\n\nDiese Karte spricht nicht von Torheit, sondern von einem Mut, den nur hat, wer von Erfahrung noch nicht verwundet wurde. Wenn sie erscheint, lädt sie dich ein, ins Unbekannte zu treten, ohne den ganzen Plan — darauf zu vertrauen, dass sich die Antworten unterwegs zeigen. Dies ist keine Zeit für Vorsicht. Es ist eine Zeit zu springen.\n\nDer Schatten des Narren ist Leichtsinn ohne jedes Bewusstsein für Folgen — ein Sprung, ohne je hinzusehen, wo du landest. Der Unterschied zwischen Mut und Unbedachtheit liegt nicht in der Tat selbst, sondern darin, ob du bereit bist anzunehmen, was kommt, auch wenn es nicht das ist, was du dir vorgestellt hast. Der Narr verspricht keine sichere Landung. Er verspricht nur, dass der Weg selbst dich etwas lehren wird.\n\nIn Beziehungen bringt der Narr Frische dorthin, wo alles vertraut zu werden begann — eine neue Bekanntschaft, ein unerwarteter Anfang, die Bereitschaft zu lieben, ohne sich gegen Verlust zu versichern. In der Arbeit kündigt er ein Projekt oder eine Idee an, die allen um dich herum riskant erscheint, sich für dich aber im Bauch richtig anfühlt. Wenn diese Karte in deiner Legung landet, frag dich nicht, ob du bereit genug bist. Niemand am Rand einer Klippe ist je ganz bereit. Tritt vor.",
  },
  magician: {
    name: "Der Magier",
    keywords: ["Willenskraft", "Erschaffen", "Du hast alle Werkzeuge"],
    meaning: "Alles, was du brauchst, liegt schon vor dir auf dem Tisch. Die Frage ist, ob du danach greifst.",
    profile:
      "Der Magier steht hinter einem Tisch, auf dem alle vier Werkzeuge liegen — Kelch, Schwert, Stab, Pentakel — Gefühl, Gedanke, Tat, Körper. Eine Hand zeigt zum Himmel, die andere zur Erde: sie verbindet die Idee mit der Wirklichkeit. Hier wartet nichts auf Zufall. Er kann nehmen, was er schon hat, und daraus etwas Neues machen. Über seinem Kopf schwebt das Zeichen der Unendlichkeit — eine Erinnerung daran, dass die Quelle, aus der er schöpft, unbegrenzt ist, solange er sich mit ihr zu verbinden weiß.\n\nWenn diese Karte erscheint, sagt sie: Du hast bereits jede Fähigkeit, die diese Aufgabe verlangt — die Frage ist nicht das Können, sondern die Absicht. Richte deinen Willen auf eine Sache, statt ihn auf zehn zu verteilen. Die Welt bewegt sich nicht von selbst. Aber du kannst dich in sie hineinbewegen, genau jetzt.\n\nDer Schatten des Magiers ist Manipulation — Geschick, eingesetzt, um andere von etwas Unwahrem zu überzeugen, statt etwas zu schaffen, das für sich allein trägt. Die wirkliche Kraft dieser Karte liegt nicht in Tricks, sondern in der Übereinstimmung von dem, was du denkst, sagst und tust. Wenn diese drei in einer Linie stehen, bewegen sich Dinge fast mühelos. Wenn nicht, bleibt nur eine Vorstellung.\n\nIn Beziehungen bedeutet der Magier Initiative — die Gelegenheit zu sagen, was du fühlst, statt zu warten, dass jemand anders den ersten Schritt macht. In der Arbeit kündigt er ein Projekt an, in dem du tatsächlich alle deine Fähigkeiten zugleich nutzen kannst, nicht nur eine. Vertrau deiner Fähigkeit, aus verstreuten Stücken etwas Ganzes zu bauen. Alles, was du brauchst, liegt schon vor dir auf dem Tisch.",
  },
  "high-priestess": {
    name: "Die Hohepriesterin",
    keywords: ["Intuition", "Geheimnis", "Inneres Wissen"],
    meaning: "Die Antwort, die du außen suchst, flüstert längst in dir. Werde still genug, um sie zu hören.",
    profile:
      "Die Hohepriesterin sitzt zwischen zwei Säulen, einer schwarzen und einer weißen, Schatten und Licht, und wählt keine von beiden — sie bleibt dazwischen, dort, wo das Geheimnis sich erst formt. Hinter ihr hängt ein dünner Schleier; er verbietet dir den Blick nicht, er bittet nur, dass du bereit bist zu sehen. Ihr Wissen steht nicht in Büchern. Es liegt in der Stille. In ihrem Schoß hält sie eine Schriftrolle mit einem nur halb sichtbaren Wort — eine Erinnerung daran, dass nicht alles Wissen für sofortiges Verstehen gedacht ist.\n\nWenn diese Karte erscheint, lädt sie dich ein, dem zu vertrauen, was du mit dem Verstand noch nicht erklären kannst. Du weißt etwas schon, bevor du Beweise hast. Dies ist keine Zeit für laute Entscheidungen oder schnelles Handeln — es ist eine Zeit des Zuhörens. Träume, Ahnungen, die Signale des Körpers: all das ist eine Sprache, die es zu verstehen lohnt.\n\nDer Schatten dieser Karte ist ein Rückzug nach innen, der so weit geht, dass du den Kontakt zur Welt verlierst — Geheimnis, das zu Isolation wird, statt zu einer inneren Kraftquelle. Die Hohepriesterin flieht die Welt nicht. Sie weiß nur, dass manche Antworten nicht im Lärm zu finden sind, sondern in einem Raum, den du dir selbst baust, fern von den Erwartungen aller anderen.\n\nIn Beziehungen spricht diese Karte von etwas noch nicht laut Gesagtem — einem Gefühl, das du spürst, aber noch nicht in Worte fassen kannst, oder einem Geheimnis, das jemand anders trägt. In der Arbeit warnt sie davor, eine Entscheidung zu erzwingen, bevor du das ganze Bild hast. Vertrau der Stille vor der Antwort mehr als dem Druck, jetzt sofort etwas sagen zu müssen. Echte Klarheit kommt zu dem, der auf sie zu warten weiß.",
  },
  empress: {
    name: "Die Herrscherin",
    keywords: ["Fülle", "Schöpferkraft", "Fürsorge"],
    meaning: "Was gepflegt wird, wächst. Für Felder gilt das genauso wie für Menschen.",
    profile:
      "Die Herrscherin sitzt mitten in einem üppigen Feld, Weizen reift um sie her, ein Fluss zieht vorbei — alles, was sie berührt, wächst. Ihre Krone ist aus Sternen, und ihr Reich wurde nicht erobert, sondern kultiviert. Sie erzwingt nichts. Sie schafft nur die Bedingungen, in denen das Leben seinen eigenen Weg nach oben findet. In die Kissen um sie herum ist das Venuszeichen geschnitten — Schönheit nicht als Zierde, sondern als eigene Kraft.\n\nWenn diese Karte erscheint, spricht sie von einer Fülle, die aus Fürsorge kommt, nicht aus Anstrengung um jeden Preis — ein schöpferisches Projekt, eine Beziehung, ein Körper, der Aufmerksamkeit braucht, keinen Druck. Verbinde dich wieder mit der sinnlichen Welt: Schönheit, Geschmack, Berührung. Etwas in dir ist bereit zu blühen, wenn du ihm Raum und Zeit gibst.\n\nDer Schatten der Herrscherin ist zu weit getriebene Fürsorge, die erstickt statt zu nähren — Liebe, die zu Kontrolle wird, oder Schöpferkraft, die in alle anderen fließt und nie in dich selbst. Ihr Feld ist üppig, weil sie weiß, wann sie zurücktreten und die Dinge von selbst wachsen lassen muss. Nicht jede Fürsorge ist dasselbe wie Eingreifen. Echte Fürsorge lässt dem, was du liebst, Raum, auf eigene Weise zu wachsen.\n\nIn Beziehungen bringt die Herrscherin Wärme, Sinnlichkeit und die Bereitschaft zu geben, ohne zu zählen, was zurückkommt. In der Arbeit kündigt sie eine Zeit an, in der ein Projekt, ein Geschäft oder eine Idee endlich Früchte trägt — sichtbar, greifbar, nach Wochen oder Monaten des Pflegens. Schau, was in deinem Leben schon still wächst, auch wenn du es noch nicht bemerkt hast. Es verdient Wasser und Licht, nicht nur Aufsicht.",
  },
  emperor: {
    name: "Der Herrscher",
    keywords: ["Struktur", "Autorität", "Festigkeit"],
    meaning: "Freiheit ohne Form löst sich auf. Der Herrscher weiß eine Grenze zu setzen, in der etwas bestehen kann.",
    profile:
      "Der Herrscher sitzt auf einem Steinthron, Rüstung unter dem Gewand, Blick fest, Hände ruhig. Hinter ihm Berge, die kein Sturm je bewegt hat. Er ist nicht zufällig dort — er hat seine Autorität durch Mühe und Disziplin aufgebaut und schützt jetzt, was er geschaffen hat, mit klaren Regeln, nicht mit Tyrannei. Sein Thron trägt Widderköpfe — eine Erinnerung daran, dass auch er einmal jung und ungeduldig war, bevor er zu herrschen lernte.\n\nWenn diese Karte erscheint, bringt sie ein Bedürfnis nach Struktur — in einem Projekt ohne Rahmen, in einer Beziehung, die klare Grenzen braucht, in dir selbst, wenn du zerstreut bist. Übernimm Verantwortung für dein eigenes Reich, welche Form es auch hat. Ordnung ist nicht das Gegenteil von Freiheit. Sie ist die Bühne, die Freiheit überhaupt erst braucht, um aufzutreten.\n\nDer Schatten des Herrschers ist eine Starrheit, die keine Ausnahmen zulässt, auch wenn sie nötig wären — Macht, die vergisst, wozu sie einst errichtet wurde. Eine echte Führung herrscht nicht durch Angst, sondern durch Verlässlichkeit. Wenn du das Bedürfnis spürst, alles zu kontrollieren, frag dich, ob du etwas Wertvolles schützt oder nur deine eigene Unruhe.\n\nIn Beziehungen bringt der Herrscher Verlässlichkeit — einen Menschen, der sein Wort hält, der Sicherheit durch Beständigkeit schafft und nicht durch große Gesten. In der Arbeit kündigt er eine Zeit an, die Führung verlangt, einen klaren Plan und das Festhalten daran. Bau dein Reich langsam, Stein um Stein, und lass es nicht vom ersten Windstoß des Zweifels umwerfen.",
  },
  hierophant: {
    name: "Der Hierophant",
    keywords: ["Tradition", "Lehre", "Gemeinschaft"],
    meaning: "Du musst das Rad nicht immer neu erfinden. Manche Antworten gibt es schon — geh und frag.",
    profile:
      "Der Hierophant sitzt zwischen zwei Säulen im Tempel, zwei Schüler hören ihm zu. Seine Hand ist zum Segen erhoben, und sein Wissen ist geerbt — von Generation zu Generation weitergegeben, erprobt, haltbar. Originalität um jeden Preis interessiert ihn nicht. Ihn interessiert, was tatsächlich funktioniert. Vor ihm liegen zwei gekreuzte Schlüssel — zum äußeren und zum inneren Wissen, zu dem, was gelernt, und dem, was geweckt wird.\n\nWenn diese Karte erscheint, kann sie von Mentorschaft sprechen, von formaler Ausbildung, von Glauben oder einer Gemeinschaft, die dir Zugehörigkeit bietet. Vielleicht ist es Zeit, eine Führung, eine Lehrerin oder ein System zu suchen, das du nicht von Grund auf bauen musst. Nicht jeder Weg wird allein gegangen. Manche gehen sich leichter in der Reihe hinter jemandem, der ihn schon zurückgelegt hat.\n\nDer Schatten des Hierophanten ist blindes Befolgen von Regeln, auch wenn sie längst nicht mehr dienen — Tradition um der Tradition willen, nicht weil sie noch Sinn ergibt. Die eigentliche Weisheit dieser Karte liegt nicht in Unterwerfung, sondern darin zu erkennen, welches Wissen der Vergangenheit es wert ist, weitergetragen zu werden, und welches man ablegen darf.\n\nIn Beziehungen kann der Hierophant eine formale Bindung anzeigen — eine Ehe, ein Versprechen, die öffentliche Anerkennung einer Verbindung, oder schlicht eine Beziehung auf gemeinsamen Werten. In der Arbeit spricht er von strukturiertem Lernen, einer Ausbildung, einer Mentorin, die dir Jahre einsamen Umherirrens ersparen kann. Schäm dich nicht, den um Hilfe zu bitten, der den Weg schon gegangen ist. Das ist keine Schwäche. Das ist Weisheit.",
  },
  lovers: {
    name: "Die Liebenden",
    keywords: ["Wahl", "Verbindung", "Übereinstimmung"],
    meaning: "Nicht jede Entscheidung ist leicht, aber manche führen dich nach Hause, zu dir selbst.",
    profile:
      "Zwei stehen nackt da, ohne Scham, ein Engel wacht über ihnen, die Arme ausgebreitet wie ein Segen. Hinter ihnen der Baum der Erkenntnis und der Baum des Lebens — eine Wahl zwischen dem Sicheren und dem Wahren. Diese Karte handelt nicht nur von Romantik. Sie handelt von jedem Augenblick, in dem du entscheiden musst, was wirklich zu dir passt. Im Hintergrund erhebt sich zwischen ihnen ein Berg — eine Erinnerung daran, dass jede wirkliche Verbindung auch einen Aufstieg verlangt, nicht nur den ersten Funken.\n\nWenn diese Karte erscheint, spricht sie von einer wichtigen Wahl — zwischen zwei Wegen, zwei Menschen, zwei Teilen von dir. Wähl nicht das Erwartete. Wähl das, was tief in dir nachklingt, auch wenn schwerer zu erklären ist, warum. Eine echte Verbindung, mit einem Menschen oder einer Berufung, fühlt sich wie Wiedererkennen an, nicht wie ein Kompromiss.\n\nDer Schatten der Liebenden ist eine Wahl aus Angst vor dem Alleinsein statt aus wirklicher Übereinstimmung — bei jemandem oder etwas zu bleiben, weil es vertraut ist, nicht weil es richtig ist. Eine echte Verbindung verlangt nicht, dass du dich kleiner machst, um zu passen. Sie verlangt, dass du dich ganz zeigst und darauf vertraust, dass das genügt.\n\nIn Beziehungen kündigt diese Karte oft eine tiefe, bedeutsame Bindung an — nicht unbedingt eine leichte, aber eine echte. In der Arbeit kann sie von einer Partnerschaft sprechen, einer Zusammenarbeit oder einer Wahl zwischen zwei Richtungen, die dich beide wirklich rufen. Hör darauf, welche Wahl dich ganzer zurücklässt, nicht welche sicherer wirkt. Die Seele lügt selten über das, was sie wirklich will.",
  },
  chariot: {
    name: "Der Wagen",
    keywords: ["Willenskraft", "Sieg", "Kontrolle"],
    meaning: "Zwei Kräfte ziehen in verschiedene Richtungen. Du gewinnst, wenn du beide auf denselben Punkt richtest.",
    profile:
      "Der Lenker steht in einem Wagen, gezogen von zwei Sphinxen, einer schwarzen, einer weißen — nicht von Zügeln gehalten, nur von seinem Willen. Es geht nicht um Gewalt, es geht um Richtung. Sterne krönen seinen Kopf, unter der Kleidung wartet die Rüstung. Sieg ist kein Zufall. Er ist das Ergebnis von Disziplin, richtig ausgerichtet. Die Stadt, aus der er kam, bleibt hinter ihm — er schaut nicht zurück, weil ihn nur der Weg nach vorn interessiert.\n\nWenn diese Karte erscheint, bringt sie die Kraft, widerstreitende Kräfte zu überwinden — in dir oder um dich herum — und mit klarer Absicht weiterzugehen. Dies ist keine Zeit für Zweifel. Es ist Zeit, die Zügel zu nehmen und dich zu bewegen, auch wenn zwei Teile von dir noch nicht ganz einig sind.\n\nDer Schatten des Wagens ist Kraft ohne Richtung — Energie, die vorwärtsstürmt, ohne zu wissen, wohin. Der wirkliche Sieg dieser Karte besteht nicht darin, andere zu schlagen, sondern darin, die gegenläufigen Teile in dir so weit auszurichten, dass sie in dieselbe Richtung ziehen können. Ein Wagen ohne Lenker ist nur ein Unfall, der darauf wartet zu geschehen.\n\nIn Beziehungen bringt diese Karte Entschlossenheit — eine Zeit, die Initiative zu ergreifen, statt auf ein Zeichen des anderen zu warten. In der Arbeit kündigt sie eine Phase konzentrierten Ehrgeizes an, in der du mehr erreichen kannst, als du dachtest, wenn du gesammelt bleibst. Versuch nicht, alles auf einmal zu kontrollieren. Richte deinen Willen in eine Richtung, und die Kräfte, die eben noch gegeneinander schienen, tragen dich vorwärts statt auseinander.",
  },
  strength: {
    name: "Die Kraft",
    keywords: ["Sanftheit", "Mut", "Innere Stärke"],
    meaning: "Echte Kraft schreit nicht. Sie legt eine Hand auf den Kopf des Löwen und beruhigt ihn mit Sanftheit, nicht mit Gewalt.",
    profile:
      "Eine Frau steht neben einem Löwen, die Hand ruhig auf seinem Kopf, über ihr das Zeichen der Unendlichkeit. Sie kämpft nicht mit dem Tier. Sie zähmt es mit Liebe, nicht mit Angst. Das ist ein Bild von Stärke, wie die Welt sie selten lehrt — die Art, die keine Lautstärke braucht, um wirklich zu sein. Ihre Haltung ist entspannt, fast zärtlich — in ihren Händen liegt keine Spannung, weil sie weiß, dass dieser Kampf gar nicht mit Gewalt gewonnen werden muss.\n\nWenn diese Karte erscheint, spricht sie vom Mut, den eigenen Trieben, Ängsten oder dem eigenen Zorn zu begegnen — nicht indem du sie unterdrückst, sondern indem du sie verstehst und führst. Sanftheit ist keine Schwäche. Wenn etwas in dir fliehen oder angreifen will, versuch stattdessen zu bleiben — mit einer Weichheit, die trägt.\n\nDer Schatten dieser Karte ist Verdrängung — so zu tun, als gäbe es den Löwen gar nicht, statt ihn verstehen zu lernen. Kraft, die du vor dir selbst versteckst, drückt sich früher oder später auf eine Weise aus, die du nicht wählst. Wirkliche Kraft heißt nicht, dass du keine wilden Triebe hast. Sie heißt, dass du mit ihnen leben kannst, ohne von ihnen beherrscht zu werden.\n\nIn Beziehungen bringt diese Karte Geduld mit dem, was am anderen schwer anzunehmen ist — die Fähigkeit, weich zu bleiben, auch wenn es leichter wäre, scharf zu reagieren. In der Arbeit spricht sie von Ausdauer ohne Gewalt, davon, ruhig weiterzumachen, auch wenn die Umstände nach Panik rufen. Deine größte Stärke in dieser Zeit liegt nicht darin, wie viel du aushältst, sondern darin, wie sanft du dem begegnen kannst, wovor du dich am meisten fürchtest.",
  },
  hermit: {
    name: "Der Eremit",
    keywords: ["Einsamkeit", "Innere Suche", "Weisheit"],
    meaning: "Die Laterne, die er trägt, leuchtet nicht zuerst anderen den Weg. Sie leuchtet seinem eigenen.",
    profile:
      "Der Eremit steht allein auf einem Berggipfel, eine Laterne in der Hand, einen Stab als Stütze. Er flieht die Welt nicht — er zieht sich in sie zurück, in eine Stille, in der die Stimmen aller anderen endlich verstummen und nur seine eigene bleibt. Sein Licht ist klein, aber es genügt, um den nächsten Schritt zu sehen. Er leuchtet keiner Menge den Weg — nur dem, der bereit ist, ihn allein zu suchen.\n\nWenn diese Karte erscheint, lädt sie zum Rückzug ein — vom Lärm, von den Erwartungen anderer, vom ständigen Reagieren. Das ist keine Einsamkeit, es ist gewählte Zurückgezogenheit, in der du eine Antwort finden kannst, die du unter Menschen nie hören würdest. Manche Fragen lassen sich nicht in Gesellschaft lösen. Sie brauchen Stille, und dich, allein mit dir.\n\nDer Schatten des Eremiten ist eine Abgeschiedenheit, die zu lange dauert — ein Rückzug, der zur Flucht vor Verbindung selbst wird, nicht nur vor dem Lärm. Die wirkliche Weisheit dieser Karte liegt nicht darin, für immer allein zu bleiben. Sie liegt darin, aus der Stille mit etwas zurückzukommen, das du mit anderen teilen kannst — bereichert, nicht erschöpft.\n\nIn Beziehungen kann der Eremit eine Zeit bedeuten, in der du Raum für dich brauchst, bevor du wirklich für jemand anderen da sein kannst. In der Arbeit spricht er von Forschung, Studium, tiefem Nachdenken vor dem nächsten Schritt. Zwing dich nicht in Gesellschaft, bevor du bereit bist. Dein eigenes Licht, so klein es ist, zeigt dir, wann es Zeit ist, zu den Menschen zurückzukehren.",
  },
  "wheel-of-fortune": {
    name: "Das Rad des Schicksals",
    keywords: ["Wandel", "Zyklen", "Schicksal"],
    meaning: "Das Rad dreht sich, ob du es aufzuhalten versuchst oder nicht. Die Frage ist, wie du dich mit ihm drehst.",
    profile:
      "Ein großes Rad dreht sich in der Luft, gezeichnet mit Symbolen, die älter sind als unsere Zeit — jeder Zyklus hat sich schon einmal ereignet, in irgendeiner Form, bei jemand anderem zuvor. Was oben war, geht nach unten; was unten war, steigt. Nichts bleibt für immer gleich, und darin liegt tatsächlich eine Erleichterung. Vier Wesen wachen um das Rad, jedes mit einem Buch — eine Erinnerung daran, dass jeder Zyklus irgendwo aufgeschrieben wird, auch wenn er spurlos zu verschwinden scheint.\n\nWenn diese Karte erscheint, zeigt sie eine Wendung an — etwas, worauf du keinen vollen Einfluss hattest, dreht sich. Klammere dich nicht an das, was geht, und fürchte nicht, was kommt. Zyklen gibt es, damit wir durch sie lernen, nicht damit wir ihnen entkommen. Gegenwärtiges Glück oder Unglück ist kein Dauerzustand. Es ist nur ein Moment auf dem Rad.\n\nDer Schatten dieser Karte ist der Glaube, du habest gar keinen Einfluss auf dein eigenes Schicksal — eine Passivität, die wartet, dass das Rad sich von selbst dreht, statt mit seiner Bewegung zu arbeiten. Das Rad des Schicksals dreht sich tatsächlich von selbst. Aber wie du dich festhältst und was du unterwegs lernst, bleibt deine Wahl.\n\nIn Beziehungen kündigt diese Karte eine veränderte Dynamik an — vielleicht das Ende einer Phase der Ungewissheit, vielleicht eine unerwartete Wendung, die alles neu setzt. In der Arbeit spricht sie von einer Gelegenheit, die von außen kommt, nicht als direkte Folge deiner Mühe, die es aber trotzdem zu ergreifen gilt. Versuch nicht, das Rad zu steuern. Lern, mit ihm zu fahren, und es wird immer eine nächste Drehung geben, die dich weiterträgt.",
  },
  justice: {
    name: "Die Gerechtigkeit",
    keywords: ["Gleichgewicht", "Wahrheit", "Folgen"],
    meaning: "Die Waage lügt nicht. Was du säst, siehst du am Ende auf der anderen Seite.",
    profile:
      "Die Gerechtigkeit sitzt zwischen zwei Säulen, in einer Hand ein Schwert, in der anderen eine Waage. Das Schwert ist gerade erhoben, keiner Seite zugeneigt. Sie entscheidet nicht nach Gefühl. Sie entscheidet nach der Wahrheit, wie sie ist, nicht wie jemand sie sich wünschen würde. Ihr Blick ist ruhig, fast unerbittlich — nicht weil es ihr gleichgültig wäre, sondern weil sie weiß, dass die Wahrheit vor der Bequemlichkeit kommen muss.\n\nWenn diese Karte erscheint, lädt sie zu einem redlichen Urteil ein — über dich und über andere. Vielleicht kommt eine Entscheidung, ein Vertrag oder die Folge einer Tat, die du längst begangen hast. Weich der Verantwortung nicht aus und erwarte nicht, dass Unrecht ewig währt. Das Gleichgewicht stellt sich immer wieder her, wenn auch manchmal nicht so und nicht dann, wie du es gewählt hättest.\n\nDer Schatten dieser Karte ist starres Richten ohne Gnade — eine Regel, angewandt ohne Verständnis für die Umstände, die sie geformt haben. Wirkliche Gerechtigkeit heißt nicht nur, ein Unrecht zu bestrafen. Sie heißt, das ganze Bild zu sehen, bevor du das Urteil sprichst, auch wenn dieses Urteil dir selbst gilt.\n\nIn Beziehungen bringt die Gerechtigkeit ein Bedürfnis nach Ehrlichkeit — das Eingeständnis des eigenen Anteils an einem Konflikt, nicht nur des fremden. In der Arbeit kündigt sie einen Vertrag an, ein rechtliches Verfahren oder eine Entscheidung, die auf Fakten getroffen werden muss, nicht auf Sympathie. Übernimm die Verantwortung für das, was deins ist, und trag keine Last, die es nicht ist. Das Universum führt genaue Bücher, auch wenn es nicht danach aussieht.",
  },
  "hanged-man": {
    name: "Der Gehängte",
    keywords: ["Pause", "Neue Perspektive", "Hingabe"],
    meaning: "Kopfüber sieht die Welt anders aus. Manchmal ist genau das, was du sehen musst.",
    profile:
      "Der Gehängte hängt an einem Bein von einem Baum, das Gesicht ruhig, fast lächelnd. Das ist keine Strafe. Es ist eine gewählte Hingabe — lange genug in einer unbequemen Lage zu bleiben, bis die Perspektive kippt. Ein dünner Schein erhellt seinen Kopf, ein Wissen, das er aufrecht stehend nicht bekommen hätte. Sein anderes Bein kreuzt dahinter und bildet eine fast perfekte Vier — eine Form, die im ganzen Deck auftaucht, wann immer etwas bereit ist, die Gestalt zu wechseln.\n\nWenn diese Karte erscheint, sagt sie: dräng nicht vorwärts. Bleib stattdessen, warte, sieh die Dinge von der anderen Seite. Dies ist keine Zeit für Entscheidungen oder Taten — es ist eine Zeit, sich dem hinzugeben, was du nicht kontrollieren kannst, und darauf zu vertrauen, dass die Pause ihren eigenen Wert trägt, auch wenn sie von außen wie nichts aussieht.\n\nDer Schatten dieser Karte ist Opfer ohne Sinn — im Unbehagen festzustecken, ohne etwas daraus zu gewinnen, nur weil es eben so gekommen ist. Die wirkliche Hingabe dieser Karte ist nicht passiv. Sie ist die aktive Entscheidung, in einer schwierigen Lage zu bleiben, bis sie dir zeigt, was du sonst nicht sähest.\n\nIn Beziehungen kann der Gehängte eine Zeit des Wartens anzeigen — auf eine Antwort, auf Klarheit, darauf, dass der andere im eigenen Tempo zu seiner Erkenntnis kommt. In der Arbeit warnt er davor, eine Entscheidung zu erzwingen, die noch nicht reif ist. Nicht jede Pause ist verlorene Zeit. Manche Pausen sind der einzige Weg, überhaupt zu sehen, was die ganze Zeit auf dem Kopf stand.",
  },
  death: {
    name: "Der Tod",
    keywords: ["Ende", "Wandlung", "Neues Kapitel"],
    meaning: "Etwas muss sterben, damit etwas anderes leben kann. Das ist keine Tragödie — das ist Natur.",
    profile:
      "Der Tod reitet ein weißes Pferd, die Rüstung schwarz, eine Fahne mit einer Rose, die trotz allem blüht. Vor ihm fallen alle gleich — König, Kind, Priester — niemand ist von der Veränderung ausgenommen. Aber hinter ihm geht auch die Sonne auf. Das Ende einer Sache ist immer der Anfang der nächsten. Ein Fluss fließt dieser aufgehenden Sonne entgegen — einen Weg nach vorn gibt es, auch wenn du ihn von hier, wo du stehst, noch nicht siehst.\n\nWenn diese Karte erscheint, kündigt sie selten einen buchstäblichen Tod an — sie spricht vom Ende einer Phase, einer Beziehung, einer Identität, die ihren Zweck erfüllt hat und nun gehen muss, damit Raum für Neues entsteht. Klammere dich nicht an das, was schon tot ist. Ein Wandel, der sich wie Verlust anfühlt, ist oft eine verkleidete Geburt.\n\nDer Schatten dieser Karte ist Verleugnung — der Versuch, etwas bereits Beendetes künstlich am Leben zu halten, weil du die Leere fürchtest, die bliebe. Der Tod bittet nicht um Erlaubnis. Er kommt, wenn es Zeit ist, nicht wenn wir bereit sind. Doch genau darin liegt auch seine Gnade: er lässt die Dinge nicht länger verwesen als nötig.\n\nIn Beziehungen kann diese Karte das Ende einer Phase anzeigen — nicht unbedingt der Beziehung selbst, aber oft das Ende dessen, was sie bisher war, damit sie etwas anderes werden kann. In der Arbeit spricht sie vom Abschluss eines Projekts, einer Rolle, eines Kapitels deiner Laufbahn. Trauere, wenn du musst, aber bleib nicht zu lange am Grab dessen, was vergangen ist. Etwas Neues wartet schon darauf, aufzugehen.",
  },
  temperance: {
    name: "Die Mäßigkeit",
    keywords: ["Gleichgewicht", "Geduld", "Mischung"],
    meaning: "Nicht beide Extreme zugleich. Irgendwo dazwischen liegt die Flüssigkeit, die nicht überschwappt.",
    profile:
      "Ein Engel steht mit einem Fuß im Wasser, einem an Land, und gießt Flüssigkeit von einem Kelch in den anderen, ohne einen Tropfen zu verlieren. Hier gibt es keine Eile. Die Welt wird nicht in Schwarz und Weiß geteilt — sie findet den dritten Raum, in dem sich Dinge treffen können, die einander zu widersprechen scheinen. Der Weg hinter ihr führt zu den Bergen und einer aufgehenden Sonne — eine langsame, aber klare Richtung, ohne Abkürzungen.\n\nWenn diese Karte erscheint, lädt sie zu Geduld und Maß ein — bei Gefühlen, die du vielleicht alle auf einmal ausdrücken willst, bei Entscheidungen, die sich wie „alles oder nichts“ anfühlen. Such den mittleren Weg. Was bleiben soll, entsteht selten in Eile. Mischen, Abstimmen, langsames Anpassen — das ist die Alchemie dieser Karte.\n\nDer Schatten der Mäßigkeit ist das Ausweichen vor einer Entscheidung im Namen des „Gleichgewichts“ — sich nie auf etwas festzulegen, aus Angst, etwas anderes zu verlieren. Wirkliches Maß heißt nicht, Extreme um jeden Preis zu meiden. Es heißt zu wissen, wann man sich einer Sache ganz hingibt und wann man wartet, bis sich die Dinge von selbst setzen.\n\nIn Beziehungen bringt diese Karte Heilung nach einem Streit — die Fähigkeit, eine gemeinsame Sprache zu finden, auch wenn du und dein Gegenüber zu verschieden scheinen. In der Arbeit spricht sie von allmählichem, stetigem Fortschritt, nicht von schnellen Siegen. Versuch nicht, alles auf einmal zu reparieren. Stück für Stück, Tag für Tag entsteht das, was am Ende seine Form hält.",
  },
  devil: {
    name: "Der Teufel",
    keywords: ["Bindung", "Schatten", "Die Illusion der Gefangenschaft"],
    meaning: "Die Ketten um die Hälse des Paares sind locker genug, um sie abzustreifen. Nichts hält sie dort außer sie selbst.",
    profile:
      "Der Teufel ragt über einem Paar auf, beide angekettet, aber locker — die Ketten würden über die Köpfe gleiten, wenn sie es nur versuchten. Das ist keine wirkliche Gefangenschaft. Es ist Gewohnheit, Angst, Abhängigkeit, der Glaube, keine Wahl zu haben. Der Teufel zwingt niemanden. Er nutzt nur aus, was die beiden selbst immer wieder wählen. Seine Fackel brennt nach unten, nicht nach oben — ein Licht, von der Wahrheit weggedreht statt auf sie zu.\n\nWenn diese Karte erscheint, legt sie ein Muster offen, das dich gefangen hält — eine Beziehung, die dir nicht dient, eine Gewohnheit, die du wiederholst, einen Gedanken, der dir einredet, du seist machtlos. Die Wahrheit ist unbequem, aber befreiend: Die Kette geht ab. Der erste Schritt in die Freiheit ist einzugestehen, dass du aus eigener Wahl geblieben bist.\n\nDer Schatten dieser Karte ist die Karte selbst — doch auch in diesem Schatten liegt ein tieferer: dich dafür zu verurteilen, überhaupt gefangen geblieben zu sein, statt es einfach einzugestehen und weiterzugehen. Der Teufel verlangt keine Vollkommenheit von dem, der sich befreit. Er verlangt nur die Bereitschaft, die Kette anzuheben, auch ohne zu wissen, was danach kommt.\n\nIn Beziehungen kann diese Karte eine ungesunde Bindung aufdecken — eine Leidenschaft an der Grenze zur Abhängigkeit, oder eine Beziehung, die beide aus Angst vor dem Alleinsein aufrechterhalten, nicht aus Liebe. In der Arbeit warnt sie vor der Falle der goldenen Fesseln — einer bequemen schlechten Lage, die du nicht verlässt, weil sie vertraut ist. Schau nach unten. Die Kette ist wirklich da. Aber deine Hand ist frei, sie über den Kopf zu heben, wann immer du bereit bist.",
  },
  tower: {
    name: "Der Turm",
    keywords: ["Plötzlicher Umbruch", "Offenbarung", "Einsturz"],
    meaning: "Der Blitz zerstört nicht, was fest war. Er legt offen, was schon hohl war.",
    profile:
      "Ein Blitz schlägt in die Spitze eines Turms, die Krone fliegt davon, zwei Gestalten fallen durch die Luft. Ein Bauwerk, das man für dauerhaft hielt, stürzt in einem einzigen Augenblick ein. Das ist die schmerzhafteste Karte des Decks — und zugleich eine der nötigsten. Flammen schlagen aus Fenstern, die einmal ein sicheres Zuhause waren — der Beweis, dass drinnen längst etwas brannte, bevor draußen jemand den Rauch sah.\n\nWenn diese Karte erscheint, kündigt sie einen plötzlichen Umbruch an, den du nicht gewählt hast — das Ende einer Illusion, das Aufdecken einer Wahrheit, die leichter zu übersehen war. Das ist keine Strafe. Es ist die Befreiung von einem Bau auf dem falschen Fundament. Was fällt, musste fallen, damit an seiner Stelle etwas Wirkliches entstehen kann.\n\nDer Schatten dieser Karte liegt nicht im Sturz selbst, sondern darin, wie lange du wusstest, dass er kommt, und ihn doch ignoriert hast. Der Turm schlägt selten ohne Warnung zu. Erst schickt er Risse, leise Zeichen, die leichter zu übersehen als anzuschauen waren. Wenn der Blitz einschlägt, ist er nur die letzte, lauteste aller Warnungen.\n\nIn Beziehungen kann diese Karte eine Offenbarung anzeigen, die alles verändert — eine zu lange verborgene Wahrheit, oder das Ende von etwas, das von außen solide aussah. In der Arbeit warnt sie vor einer plötzlichen Wende, einem Verlust, den du nicht kommen sahst. Versuch nicht, den Turm in derselben Form wieder aufzubauen. Was fiel, war zum Fallen bestimmt — damit auf dem leeren Grund diesmal etwas auf festeren Fundamenten wachsen kann.",
  },
  star: {
    name: "Der Stern",
    keywords: ["Hoffnung", "Erneuerung", "Ein leitendes Licht"],
    meaning: "Nach dem Sturm des Turms kommt Stille, und in der Stille ein einziges Licht, das den Weg zeigt.",
    profile:
      "Eine Frau kniet am Wasser, nackt, ohne Scham, und gießt Wasser aus zwei Krügen — einen zurück ins Wasser, einen auf die Erde. Über ihr sieben kleine Sterne und ein großer, leitender. Nach allem, was der Turm niedergerissen hat, kommt diese Karte wie ein Atemzug nach zu langem Anhalten. Hinter ihr sitzt ein Vogel in einem Baum — ein Zeichen, dass das Leben schon dorthin zurückgekehrt ist, wo nichts geblieben zu sein schien.\n\nWenn diese Karte erscheint, bringt sie eine Hoffnung, die nicht naiv ist — sie ist verdient, nach etwas, das du überstanden hast. Vertrau darauf, dass es besser wird, auch langsam. Dies ist keine Zeit, an dir zu zweifeln. Irgendwo in der Ferne brennt ein Licht, das dich führt, auch wenn du es nicht ganz klar siehst. Geh weiter in seine Richtung.\n\nDer Schatten des Sterns ist eine Hoffnung, die zum passiven Warten auf ein Wunder wird, statt zu einer stillen Handlung, jeden Tag wiederholt. Die Frau am Wasser sitzt nicht still — sie gießt weiter, pflegt, erneuert. Ihre Hoffnung ist eine Tat, nicht nur ein Gefühl. Der Unterschied zwischen Wunschdenken und echter Hoffnung ist genau der: echte Hoffnung verlangt, dass du etwas tust, während du wartest.\n\nIn Beziehungen bringt der Stern eine Verletzlichkeit, die nicht mehr gefährlich ist — die Fähigkeit, dich wieder als du selbst zu zeigen, nachdem dich etwas schon verwundet hat. In der Arbeit kündigt er eine Zeit nach der Krise an, in der sich die Dinge langsam, aber sicher zum Besseren wenden. Glaub, dass du diese Hoffnung wert bist. Sterne leuchten nicht nur denen, die schon angekommen sind. Sie leuchten auch, und vor allem, denen, die noch unterwegs sind.",
  },
  moon: {
    name: "Der Mond",
    keywords: ["Ungewissheit", "Unterbewusstsein", "Illusion"],
    meaning: "Der Weg durch die Nacht ist wirklich, auch wenn du nicht siehst, wohin er führt. Geh weiter, Schritt für Schritt.",
    profile:
      "Der Mond scheint über einem Weg, der zwischen zwei Türmen ins Unbekannte führt. Ein Hund und ein Wolf heulen ihn an, ein Krebs kriecht aus dem Wasser — alles Verborgene erwacht bei Nacht. Das ist die Karte der Schatten, der Träume und der Ängste, die bei Tageslicht keine klare Form haben. Der Mond selbst trägt ein Gesicht, aus dem Lichttränen tropfen — sogar das leitende Licht dieser Nacht ist unvollkommen, ungewiss, selbst noch im Wandel.\n\nWenn diese Karte erscheint, warnt sie, dass die Dinge vielleicht nicht sind, wie sie scheinen — die Informationen sind unvollständig, die Gefühle verworren, der Weg nicht ganz klar. Erzwing keine Klarheit, die es noch nicht gibt. Vertrau stattdessen der Intuition, die im Dunkeln besser sieht als der Verstand. Ungewissheit ist kein Zeichen, dass du auf dem falschen Weg bist. Sie ist nur Teil der Nacht, durch die du gehen musst.\n\nDer Schatten dieser Karte ist das Sich-Verlieren in den eigenen Ängsten — Ungeheuer, die der Verstand erschafft, werden wirklicher als die tatsächliche Gefahr. Der Hund und der Wolf heulen in Wahrheit denselben Mond an. Angst und Vorstellungskraft haben dieselbe Quelle. Lern, eine echte Warnung von einem Schatten zu unterscheiden, den nur deine Erschöpfung geworfen hat.\n\nIn Beziehungen kann der Mond Verwirrung anzeigen — etwas Ungesagtes, ein Missverständnis aus Unklarheit, nicht aus Bosheit. In der Arbeit warnt er davor, etwas Wichtiges zu unterschreiben oder zu entscheiden, bevor der Nebel sich hebt. Manche Wahrheiten zeigen sich erst im Morgenlicht. Vertrau bis dahin dem Schritt für Schritt, auch wenn der Weg vor dir nicht ganz beleuchtet ist.",
  },
  sun: {
    name: "Die Sonne",
    keywords: ["Freude", "Klarheit", "Erfolg"],
    meaning: "Es gibt keinen Grund, sich im Schatten zu verstecken, wenn der Himmel so klar ist.",
    profile:
      "Ein Kind reitet ein weißes Pferd unter einer großen, glühenden Sonne, die Arme offen, Sonnenblumen blühen dahinter. Nichts verborgen, nichts im Schatten — das ist die unmittelbarste Freudenkarte des ganzen Decks. Die Freude hier ist nicht naiv. Sie ist eine verdiente Einfachheit, nach allem, was vorher kam. Eine rote Fahne flattert im Wind, ohne Angst, ohne etwas verteidigen zu müssen — nichts wird verborgen, weil es nichts mehr gibt, wofür man sich schämen müsste.\n\nWenn diese Karte erscheint, bringt sie Klarheit, Erfolg und echte Freude — in einem Projekt, das endlich Früchte trägt, in einer Beziehung, die sich leicht anfühlt, in dir selbst, wenn du dich wieder ganz fühlst. Erlaub dir zu genießen, ohne Schuldgefühl, ohne auf die nächste Sorge zu warten. Diese Wärme ist verdient. Nimm sie ganz an.\n\nDer Schatten dieser Karte ist selten — die Sonne trägt nicht viel Dunkelheit in sich. Wenn es überhaupt eine Falle gibt, dann ein Übermaß an Selbstsicherheit, das die Verletzlichkeit anderer vergisst, weil es selbst so voller Licht ist. Teil deine Freude, stell sie nicht zur Schau. Eine Sonne, die alle gleich bescheint, ist schöner als eine, die nur auf sich selbst scheint.\n\nIn Beziehungen bringt diese Karte Leichtigkeit, Lachen, Freude ohne Verwicklung — eine Zeit, in der Liebe einfach ist, nicht verknotet. In der Arbeit kündigt sie Anerkennung an, Erfolg, ein sichtbares Ergebnis deiner Mühe. Sei nicht bescheiden über das, was du erreicht hast. Das Kind auf dem Pferd entschuldigt sich nicht für seine Freude. Du musst es auch nicht.",
  },
  judgement: {
    name: "Das Gericht",
    keywords: ["Erwachen", "Vergebung", "Ein Ruf"],
    meaning: "Die Posaune richtet nicht. Sie ruft nur die, die bereit sind aufzustehen.",
    profile:
      "Ein Engel bläst die Posaune über offenen Gräbern, und die Toten stehen auf, die Arme erhoben, bereit für etwas Neues. Das ist keine Strafe. Es ist ein Ruf zum Erwachen — der Moment, in dem es unmöglich wird, die Wahrheit über dich selbst oder dein Leben weiter zu ignorieren. Alle, die aufstehen, tragen denselben Ausdruck — nicht Furcht, sondern Erleichterung, als hätten sie endlich gehört, worauf sie die ganze Zeit gewartet haben.\n\nWenn diese Karte erscheint, lädt sie zu einer ehrlichen Abrechnung mit der Vergangenheit ein — nicht mit Verurteilung, sondern mit Vergebung, dir selbst wie anderen gegenüber. Etwas in dir ist bereit, aus dem aufzustehen, was gewesen ist. Hör auf den Ruf, auch wenn er zu einem unpassenden Zeitpunkt kommt. Erwachen ist nicht immer bequem. Aber es lohnt sich immer, zu antworten.\n\nDer Schatten dieser Karte ist Selbstverurteilung, als „Erwachen“ verkleidet — das endlose Wiederkäuen vergangener Fehler, ohne je wirklich zu vergeben. Die Posaune ruft nicht, um dich für den zu bestrafen, der du warst. Sie ruft dich, der zu werden, der du jetzt sein kannst.\n\nIn Beziehungen kann diese Karte Versöhnung anzeigen — mit einem Menschen, mit dir selbst, mit einer Version von dir, die leichter zu verurteilen als zu verstehen war. In der Arbeit spricht sie von einer Berufung, die endlich wirklich Sinn ergibt, oder von Anerkennung für Mühe, die zu lange unbemerkt blieb. Antworte auf den Ruf, auch wenn er aus einer Richtung kommt, die du nicht erwartet hast. Etwas in dir hat genau auf diesen Moment gewartet.",
  },
  world: {
    name: "Die Welt",
    keywords: ["Vollendung", "Ganzheit", "Ein neuer Zyklus"],
    meaning: "Der Kreis schließt sich. Und im selben Moment öffnet sich schon der nächste.",
    profile:
      "Eine Gestalt tanzt in einem Lorbeerkranz, umgeben von den vier Wesen der Weltenecken — Stier, Löwe, Adler, Mensch. Alles ist hier, alles verbunden, nichts fehlt. Das ist die letzte Karte der Großen Arkana, die Vollendung der langen Reise, die mit dem Narren am Rand der Klippe begann. In jeder Hand hält sie einen Stab — ein Sinnbild für ein Gleichgewicht, das nicht durch das Meiden von Extremen erreicht wurde, sondern durch die Vereinigung all dessen, was vorher war, zu einer einzigen, ganzen Bewegung.\n\nWenn diese Karte erscheint, verkündet sie eine Vollendung — einen Zyklus, ein Projekt, ein Lebenskapitel, das sein natürliches Ende erreicht hat, erfolgreich. Feiere, was du erreicht hast. Aber wisse auch, dass jedes Ende den Samen des nächsten Anfangs trägt. Die Welt hält nicht an. Sie dreht sich weiter, in einen neuen Kreis, mit allem Gelernten schon in dich eingebaut.\n\nDer Schatten dieser Karte ist selten ihr eigener — er zeigt sich, wenn jemand eine Vollendung nicht anerkennt, die längst da ist, und sich an ein Kapitel klammert, das schon zu Ende geschrieben ist. Die Welt bestraft nicht den, der innehält, um zu feiern. Sie bestraft nur den, der nie sagen mag, dass etwas fertig ist.\n\nIn Beziehungen kündigt diese Karte eine tiefe Erfüllung an — eine Verbindung, die sich ganz anfühlt, ohne fehlende Teile. In der Arbeit spricht sie von einem Abschluss, der dein Wachstum von der allerersten Karte bis zu dieser letzten beweist. Halt einen Moment inne. Schau, wie weit du gekommen bist. Und wenn du bereit bist, taucht der Narr wieder am Horizont auf, das Bündel leer und bereit für einen neuen Weg.",
  },
};
