import { QuotePrint } from "./types";

/**
 * Placeholder quote-print catalog for the Poetry section — a lighter,
 * more affordable product line alongside the original paintings. All text
 * and pricing here is a bracketed placeholder pending Urška's real quotes
 * and prices — do not invent content here.
 */
export const quotes: QuotePrint[] = [
  {
    slug: "quote-01",
    order: 1,
    title: "[QUOTE 01 TITLE]",
    text: "[QUOTE 01 TEXT PENDING]",
    accentColor: "#4A4A4A",
    format: "Fine art print",
    price: 45,
    currency: "EUR",
    priceConfirmed: false,
    availability: "inquire",
    sku: "AU-QT-01",
  },
  {
    slug: "quote-02",
    order: 2,
    title: "[QUOTE 02 TITLE]",
    text: "[QUOTE 02 TEXT PENDING]",
    accentColor: "#1A1A1A",
    format: "Fine art print",
    price: 45,
    currency: "EUR",
    priceConfirmed: false,
    availability: "inquire",
    sku: "AU-QT-02",
  },
  {
    slug: "quote-03",
    order: 3,
    title: "[QUOTE 03 TITLE]",
    text: "[QUOTE 03 TEXT PENDING]",
    accentColor: "#5C5C5C",
    format: "Fine art print",
    price: 45,
    currency: "EUR",
    priceConfirmed: false,
    availability: "inquire",
    sku: "AU-QT-03",
  },
  {
    slug: "quote-04",
    order: 4,
    title: "[QUOTE 04 TITLE]",
    text: "[QUOTE 04 TEXT PENDING]",
    accentColor: "#8A8A8A",
    format: "Fine art print",
    price: 45,
    currency: "EUR",
    priceConfirmed: false,
    availability: "inquire",
    sku: "AU-QT-04",
  },
  {
    slug: "quote-05",
    order: 5,
    title: "[QUOTE 05 TITLE]",
    text: "[QUOTE 05 TEXT PENDING]",
    accentColor: "#6E6E6E",
    format: "Fine art print",
    price: 45,
    currency: "EUR",
    priceConfirmed: false,
    availability: "inquire",
    sku: "AU-QT-05",
  },
  {
    slug: "quote-06",
    order: 6,
    title: "[QUOTE 06 TITLE]",
    text: "[QUOTE 06 TEXT PENDING]",
    accentColor: "#3A3A3A",
    format: "Fine art print",
    price: 45,
    currency: "EUR",
    priceConfirmed: false,
    availability: "inquire",
    sku: "AU-QT-06",
  },
];
