import type { AstroStrings } from "./types";

export const de: AstroStrings = {
  locale: "de-DE",
  productName: "Sternen-Geschäftskalender",
  typeLabel: {
    contracts: "Gut für Verträge",
    beginnings: "Gut für Anfänge",
    avoid: "Fang nichts Neues an",
    self: "Zeit für dich",
  },
  typeAdvice: {
    contracts: "Unterschriften, Verhandlungen, wichtige E-Mails und Absprachen.",
    beginnings: "Projektstart, erster Beitrag, neue Kundschaft, erster Schritt.",
    avoid: "Abschließen, aufräumen und warten — nichts Neues beginnen.",
    self: "Ruhe, Rückblick, Entscheidungen mit kühlem Kopf.",
  },
  categoryLabel: {
    contracts: "Verträge",
    beginnings: "Anfänge",
    avoid: "Nichts anfangen",
    self: "Zeit für dich",
    love: "Liebe",
    money: "Geld",
    health: "Gesundheit",
  },
  signName: {
    aries: "Widder",
    taurus: "Stier",
    gemini: "Zwillinge",
    cancer: "Krebs",
    leo: "Löwe",
    virgo: "Jungfrau",
    libra: "Waage",
    scorpio: "Skorpion",
    sagittarius: "Schütze",
    capricorn: "Steinbock",
    aquarius: "Wassermann",
    pisces: "Fische",
  },
  moonInSign: {
    aries: "im Widder",
    taurus: "im Stier",
    gemini: "in den Zwillingen",
    cancer: "im Krebs",
    leo: "im Löwen",
    virgo: "in der Jungfrau",
    libra: "in der Waage",
    scorpio: "im Skorpion",
    sagittarius: "im Schützen",
    capricorn: "im Steinbock",
    aquarius: "im Wassermann",
    pisces: "in den Fischen",
  },
  planetName: {
    sun: "Die Sonne",
    moon: "Der Mond",
    mercury: "Merkur",
    venus: "Venus",
    mars: "Mars",
    jupiter: "Jupiter",
    saturn: "Saturn",
  },
  planetObject: {
    sun: "zur Sonne",
    moon: "zum Mond",
    mercury: "zu Merkur",
    venus: "zu Venus",
    mars: "zu Mars",
    jupiter: "zu Jupiter",
    saturn: "zu Saturn",
  },
  natalPlanet: {
    sun: "deine Geburtssonne",
    moon: "deinen Geburtsmond",
    mercury: "deinen Geburtsmerkur",
    venus: "deine Geburtsvenus",
    mars: "deinen Geburtsmars",
    jupiter: "deinen Geburtsjupiter",
    saturn: "deinen Geburtssaturn",
  },
  personalVerb: {
    conjunction: "zieht über",
    sextile: "unterstützt",
    trine: "segnet",
    square: "fordert",
    opposition: "stellt auf die Probe:",
  },
  aspectPhrase: {
    conjunction: "steht in Konjunktion",
    sextile: "steht im freundlichen Sextil",
    trine: "steht im harmonischen Trigon",
    square: "steht im gespannten Quadrat",
    opposition: "steht in Opposition",
  },
  moonPhaseName: [
    "Neumond",
    "zunehmende Sichel",
    "erstes Viertel",
    "zunehmender Mond",
    "Vollmond",
    "abnehmender Mond",
    "letztes Viertel",
    "abnehmende Sichel",
  ],
  moonSignHint: {
    aries: "Mut und ein schneller Start.",
    taurus: "Ausdauer, Geld und Genuss.",
    gemini: "Gespräche, Schreiben und Kontakte.",
    cancer: "Zuhause, Gefühle und Fürsorge für dich.",
    leo: "Selbstvertrauen und Auftritt.",
    virgo: "Genauigkeit, Ordnung und Details.",
    libra: "Partnerschaften und faire Absprachen.",
    scorpio: "Tiefe, Strategie und Vertrauen.",
    sagittarius: "Vision, Weite und Optimismus.",
    capricorn: "Struktur, Verantwortung und lange Ziele.",
    aquarius: "Ideen, Gemeinschaft und das Andere.",
    pisces: "Intuition, Träume und Rückzug.",
  },
  pairHintGood: {
    "mercury-jupiter": "großzügige Abschlüsse und gute Nachrichten.",
    "mercury-saturn": "feste, gut durchdachte Vereinbarungen.",
    "mercury-mars": "klare Worte und schnelle Entscheidungen.",
    "sun-jupiter": "das Glück ist auf der Seite der Mutigen.",
    "venus-jupiter": "Fülle in Liebe und Finanzen.",
    "venus-saturn": "Treue und dauerhafte Werte.",
    "venus-mars": "Anziehung und Leidenschaft.",
    "mars-saturn": "Disziplin, die Berge versetzt.",
    "mars-jupiter": "Energie für große Schritte.",
    "moon-jupiter": "Optimismus und Rückhalt.",
    "moon-saturn": "Verlässlichkeit und Ernst.",
    "moon-venus": "Zartheit und Schönheit.",
    "moon-mars": "Schwung und Entschlossenheit.",
  },
  pairHintTense: {
    "mercury-jupiter": "Versprechen können zu groß ausfallen.",
    "mercury-saturn": "Hindernisse, Verzögerungen und Zweifel.",
    "mercury-mars": "scharfe Worte — denk nach, bevor du sendest.",
    "sun-jupiter": "achte darauf, es nicht zu übertreiben.",
    "venus-jupiter": "Vorsicht bei Impulskäufen.",
    "venus-saturn": "Kühle und ein Gefühl von Mangel.",
    "venus-mars": "Reibung in Beziehungen.",
    "mars-saturn": "Frustration — erzwing nichts.",
    "mars-jupiter": "zu viel auf einmal.",
    "moon-jupiter": "etwas zu viel Optimismus.",
    "moon-saturn": "schwerere Gefühle, ein Bedürfnis nach Rückzug.",
    "moon-venus": "Empfindsamkeit.",
    "moon-mars": "Reizbarkeit.",
  },
  pairHintFallback: "eine betonte Energie an diesem Tag.",
  personalHintGood: {
    mercury: "deine Worte überzeugen heute.",
    jupiter: "eine Zeit der Gelegenheiten und des Wachstums für dich.",
    saturn: "die Mühe, die du hineinsteckst, bleibt.",
    mars: "du hast die Energie für einen mutigen Schritt.",
    venus: "du ziehst Menschen und Gelegenheiten an.",
    sun: "du strahlst — zeig dich.",
    moon: "du bist gefühlsmäßig im Gleichgewicht.",
  },
  personalHintHard: {
    mercury: "Missverständnisse sind wahrscheinlicher — schreib klar.",
    jupiter: "versprich nicht zu viel.",
    saturn: "eine Zeit der Prüfung — werde langsamer und festige die Grundlagen.",
    mars: "achte auf Streit und Erschöpfung.",
    venus: "kauf und versprich nichts aus einem Gefühl heraus.",
    sun: "nimm dir mehr Ruhe.",
    moon: "die Gefühle liegen dicht unter der Oberfläche.",
  },
  personalHintFallback: "ein betonter Tag für dich.",
  factor: {
    mercuryRetro:
      "☿℞ Merkur ist rückläufig — Verträge, Technik und Nachrichten geraten leicht durcheinander. Lies das Kleingedruckte zweimal.",
    mercuryDirect: "☿ Merkur läuft vorwärts; Worte und Absprachen fließen.",
    venusRetro:
      "♀℞ Venus ist rückläufig — keine Zeit für große Anschaffungen oder neue Liebesversprechen; gut, um alte Bande wiederzubeleben.",
    marsRetro: "♂℞ Mars ist rückläufig — die Energie wendet sich nach innen; erzwing nichts mit dem Kopf durch die Wand.",
    planetStation: (planet) => `⏸️ ${planet} wechselt heute die Richtung — ein unruhiger Tag, während sich die Dinge verschieben.`,
    moonVoid: "🕳️ Der Mond ist „ohne Lauf“ (void of course) — was jetzt beginnt, kommt selten ans Ziel.",
    eclipseToday: (kind) => `🌘 Heute ist eine ${kind} — ein Tag zum Beobachten, nicht zum Entscheiden.`,
    eclipseApproaching: (kind) => `🌘 Eine ${kind} steht bevor — die Energie ist unruhig.`,
    eclipsePassed: (kind) => `🌘 Eine ${kind} liegt hinter uns — die Energie ist unruhig.`,
    eclipseSolar: "Sonnenfinsternis",
    eclipseLunar: "Mondfinsternis",
    newMoon: "🌑 Neumond — ein Samen, den du jetzt setzt, hat den ganzen Monat zum Wachsen.",
    fullMoon: "🌕 Vollmond — Zeit für Abschlüsse, Dankbarkeit und offene Gespräche.",
    waxing: "🌒 Der Mond nimmt zu — was du beginnst, gewinnt an Kraft.",
    waning: "🌖 Der Mond nimmt ab — gut zum Abschließen und Ausmisten.",
    balsamic: "🌘 Die letzten Tage vor Neumond — loslassen, ruhen, Platz machen.",
    moonOverNatalSun: "🌞 Der Mond zieht über deine Geburtssonne — dein persönlicher Neustart des Monats.",
    lunarReturn: "🌙 Der Mond kehrt an seinen Platz bei deiner Geburt zurück — hör auf deine Gefühle.",
  },
  month: {
    intro: {
      contracts: "Dieser Monat begünstigt Vereinbarungen: ein klares Wort und eine Unterschrift wiegen mehr als sonst.",
      beginnings: "Dieser Monat öffnet Türen für Neues: Ideen, die in der Schublade warten, haben Rückenwind.",
      avoid: "Dieser Monat bittet um Geduld: mehr Tage eignen sich zum Abschließen als zum Anfangen.",
      self: "Dieser Monat ist für die innere Arbeit: Ruhe und Nachdenken sind deine beste Strategie.",
    },
    forSign: (sign) => `Für ${sign}: `,
    mercuryRetro: "☿℞ Einen Teil des Monats ist Merkur rückläufig — Verträge zweimal lesen, Technik sichern.",
    venusRetro: "♀℞ Venus ist rückläufig — überleg dir jede größere Anschaffung und jede neue Bindung zweimal.",
    marsRetro: "♂℞ Mars ist rückläufig — lenk die Energie ins Abschließen.",
    eclipseOn: (date, kind) => `🌘 Am ${date} ist eine ${kind} — ein Tag zum Beobachten, nicht zum Entscheiden.`,
    bestContracts: "Beste Tage für Verträge",
    bestBeginnings: "Beste Tage für Anfänge",
    forMoney: "Für Geld",
    forLove: "Für die Liebe",
    forHealth: "Für die Gesundheit",
    startNothing: "Fang nichts an",
    disclaimer:
      "✨ Der Kalender ist eine Anregung zum Planen, keine Finanzberatung — das letzte Wort hast immer du.",
    titlePersonal: (month) => `${month} — dein persönliches Horoskop`,
    titleOverview: (month) => `${month} — Überblick über den Monat`,
  },
};
