import type { AstroStrings } from "./types";

export const en: AstroStrings = {
  locale: "en-GB",
  productName: "Star Business Calendar",
  typeLabel: {
    contracts: "Good for contracts",
    beginnings: "Good for beginnings",
    avoid: "Start nothing new",
    self: "Time for yourself",
  },
  typeAdvice: {
    contracts: "Signatures, negotiations, important emails and agreements.",
    beginnings: "Launches, first posts, new clients, first steps.",
    avoid: "Finish, tidy up and wait — don't start anything new.",
    self: "Rest, review, decisions made with a cool head.",
  },
  categoryLabel: {
    contracts: "Contracts",
    beginnings: "Beginnings",
    avoid: "Start nothing",
    self: "Time for yourself",
    love: "Love",
    money: "Money",
    health: "Health",
  },
  signName: {
    aries: "Aries",
    taurus: "Taurus",
    gemini: "Gemini",
    cancer: "Cancer",
    leo: "Leo",
    virgo: "Virgo",
    libra: "Libra",
    scorpio: "Scorpio",
    sagittarius: "Sagittarius",
    capricorn: "Capricorn",
    aquarius: "Aquarius",
    pisces: "Pisces",
  },
  moonInSign: {
    aries: "in Aries",
    taurus: "in Taurus",
    gemini: "in Gemini",
    cancer: "in Cancer",
    leo: "in Leo",
    virgo: "in Virgo",
    libra: "in Libra",
    scorpio: "in Scorpio",
    sagittarius: "in Sagittarius",
    capricorn: "in Capricorn",
    aquarius: "in Aquarius",
    pisces: "in Pisces",
  },
  planetName: {
    sun: "The Sun",
    moon: "The Moon",
    mercury: "Mercury",
    venus: "Venus",
    mars: "Mars",
    jupiter: "Jupiter",
    saturn: "Saturn",
  },
  planetObject: {
    sun: "the Sun",
    moon: "the Moon",
    mercury: "Mercury",
    venus: "Venus",
    mars: "Mars",
    jupiter: "Jupiter",
    saturn: "Saturn",
  },
  natalPlanet: {
    sun: "your natal Sun",
    moon: "your natal Moon",
    mercury: "your natal Mercury",
    venus: "your natal Venus",
    mars: "your natal Mars",
    jupiter: "your natal Jupiter",
    saturn: "your natal Saturn",
  },
  personalVerb: {
    conjunction: "joins",
    sextile: "supports",
    trine: "blesses",
    square: "challenges",
    opposition: "puts to the test",
  },
  aspectPhrase: {
    conjunction: "joins",
    sextile: "is in a friendly sextile to",
    trine: "is in a flowing trine to",
    square: "is in a tense square to",
    opposition: "is opposite",
  },
  moonPhaseName: [
    "new moon",
    "waxing crescent",
    "first quarter",
    "waxing gibbous",
    "full moon",
    "waning gibbous",
    "last quarter",
    "waning crescent",
  ],
  moonSignHint: {
    aries: "courage and a quick start.",
    taurus: "patience, money and pleasure.",
    gemini: "conversations, writing and networking.",
    cancer: "home, feelings and self-care.",
    leo: "confidence and presence.",
    virgo: "precision, order and detail.",
    libra: "partnerships and fair agreements.",
    scorpio: "depth, strategy and trust.",
    sagittarius: "vision, expansion and optimism.",
    capricorn: "structure, responsibility and long goals.",
    aquarius: "ideas, community and doing things differently.",
    pisces: "intuition, dreams and retreat.",
  },
  pairHintGood: {
    "mercury-jupiter": "generous deals and good news.",
    "mercury-saturn": "solid, well-considered agreements.",
    "mercury-mars": "clear words and quick decisions.",
    "sun-jupiter": "luck favours the bold.",
    "venus-jupiter": "abundance in love and money.",
    "venus-saturn": "loyalty and lasting value.",
    "venus-mars": "attraction and passion.",
    "mars-saturn": "discipline that moves mountains.",
    "mars-jupiter": "energy for big moves.",
    "moon-jupiter": "optimism and support.",
    "moon-saturn": "reliability and focus.",
    "moon-venus": "tenderness and beauty.",
    "moon-mars": "drive and determination.",
  },
  pairHintTense: {
    "mercury-jupiter": "promises may be too big.",
    "mercury-saturn": "obstacles, delays and doubts.",
    "mercury-mars": "sharp words — think before you hit send.",
    "sun-jupiter": "watch out for overdoing it.",
    "venus-jupiter": "beware of impulse buys.",
    "venus-saturn": "coolness and a sense of lack.",
    "venus-mars": "friction in relationships.",
    "mars-saturn": "frustration — don't force things.",
    "mars-jupiter": "too much at once.",
    "moon-jupiter": "a little too much optimism.",
    "moon-saturn": "heavier feelings, a need to withdraw.",
    "moon-venus": "sensitivity.",
    "moon-mars": "irritability.",
  },
  pairHintFallback: "a highlighted energy today.",
  personalHintGood: {
    mercury: "your words convince today.",
    jupiter: "a season of opportunity and growth for you.",
    saturn: "the effort you put in lasts.",
    mars: "you have the energy for a bold move.",
    venus: "you attract people and opportunities.",
    sun: "you shine — show up.",
    moon: "you feel emotionally balanced.",
  },
  personalHintHard: {
    mercury: "misunderstandings are likelier — write clearly.",
    jupiter: "don't overpromise.",
    saturn: "a testing season — slow down and strengthen foundations.",
    mars: "watch for conflict and burnout.",
    venus: "don't buy or promise on a feeling.",
    sun: "take more rest.",
    moon: "feelings are close to the surface.",
  },
  personalHintFallback: "a highlighted day for you.",
  factor: {
    mercuryRetro: "☿℞ Mercury is retrograde — contracts, tech and messages easily go astray. Read the small print twice.",
    mercuryDirect: "☿ Mercury moves forward; words and agreements flow.",
    venusRetro:
      "♀℞ Venus is retrograde — not the time for big purchases or new romantic commitments; good for reviving old bonds.",
    marsRetro: "♂℞ Mars is retrograde — energy turns inward; don't force your way through.",
    planetStation: (planet) => `⏸️ ${planet} changes direction today — an unsettled day while things shift.`,
    moonVoid: "🕳️ The Moon is void of course — what starts now rarely reaches its goal.",
    eclipseToday: (kind) => `🌘 A ${kind} eclipse today — a day to observe, not decide.`,
    eclipseApproaching: (kind) => `🌘 A ${kind} eclipse is approaching — energy is restless.`,
    eclipsePassed: (kind) => `🌘 A recent ${kind} eclipse stirs the air — energy is restless.`,
    eclipseSolar: "solar",
    eclipseLunar: "lunar",
    newMoon: "🌑 New moon — a seed planted now has the whole month to grow.",
    fullMoon: "🌕 Full moon — a time for completion, gratitude and honest talks.",
    waxing: "🌒 The Moon is waxing — what you start gathers strength.",
    waning: "🌖 The Moon is waning — good for finishing and clearing out.",
    balsamic: "🌘 The last days before the new moon — release, rest, make room.",
    moonOverNatalSun: "🌞 The Moon crosses your natal Sun — your personal monthly fresh start.",
    lunarReturn: "🌙 The Moon returns to its place at your birth — listen to your feelings.",
  },
  month: {
    intro: {
      contracts: "This month favours agreements: a clear word and a signature carry more weight than usual.",
      beginnings: "This month opens doors to the new: ideas waiting in a drawer have the wind at their back.",
      avoid: "This month asks for patience: more days suit finishing than starting.",
      self: "This month is for inner work: rest and reflection are your best strategy.",
    },
    forSign: (sign) => `For ${sign}: `,
    mercuryRetro: "☿℞ Mercury is retrograde for part of the month — read contracts twice and back up your tech.",
    venusRetro: "♀℞ Venus is retrograde — think twice about big purchases and new commitments.",
    marsRetro: "♂℞ Mars is retrograde — channel energy into finishing.",
    eclipseOn: (date, kind) => `🌘 ${date}: a ${kind} eclipse — a day to observe, not decide.`,
    bestContracts: "Best days for contracts",
    bestBeginnings: "Best days for beginnings",
    forMoney: "For money",
    forLove: "For love",
    forHealth: "For health",
    startNothing: "Start nothing",
    disclaimer: "✨ The calendar is inspiration for planning, not financial advice — the last word is always yours.",
    titlePersonal: (month) => `${month} — your personal horoscope`,
    titleOverview: (month) => `${month} — month overview`,
  },
};
