import type { AstroStrings } from "./types";

export const hr: AstroStrings = {
  locale: "hr-HR",
  productName: "Zvjezdani poslovni kalendar",
  typeLabel: {
    contracts: "Dobar za ugovore",
    beginnings: "Dobar za početke",
    avoid: "Ne počinji ništa",
    self: "Vrijeme za sebe",
  },
  typeAdvice: {
    contracts: "Potpisi, pregovori, važni mailovi i dogovori.",
    beginnings: "Pokretanje projekta, prva objava, novi klijent, prvi korak.",
    avoid: "Dovršavaj, sređuj i čekaj — novo nemoj počinjati.",
    self: "Odmor, pregled, odluke na hladno.",
  },
  categoryLabel: {
    contracts: "Ugovori",
    beginnings: "Počeci",
    avoid: "Ne počinji",
    self: "Vrijeme za sebe",
    love: "Ljubav",
    money: "Novac",
    health: "Zdravlje",
  },
  signName: {
    aries: "Ovan",
    taurus: "Bik",
    gemini: "Blizanci",
    cancer: "Rak",
    leo: "Lav",
    virgo: "Djevica",
    libra: "Vaga",
    scorpio: "Škorpion",
    sagittarius: "Strijelac",
    capricorn: "Jarac",
    aquarius: "Vodenjak",
    pisces: "Ribe",
  },
  moonInSign: {
    aries: "u Ovnu",
    taurus: "u Biku",
    gemini: "u Blizancima",
    cancer: "u Raku",
    leo: "u Lavu",
    virgo: "u Djevici",
    libra: "u Vagi",
    scorpio: "u Škorpionu",
    sagittarius: "u Strijelcu",
    capricorn: "u Jarcu",
    aquarius: "u Vodenjaku",
    pisces: "u Ribama",
  },
  planetName: {
    sun: "Sunce",
    moon: "Mjesec",
    mercury: "Merkur",
    venus: "Venera",
    mars: "Mars",
    jupiter: "Jupiter",
    saturn: "Saturn",
  },
  planetObject: {
    sun: "sa Suncem",
    moon: "s Mjesecom",
    mercury: "s Merkurom",
    venus: "s Venerom",
    mars: "s Marsom",
    jupiter: "s Jupiterom",
    saturn: "sa Saturnom",
  },
  natalPlanet: {
    sun: "tvoje rođeno Sunce",
    moon: "tvoj rođeni Mjesec",
    mercury: "tvoj rođeni Merkur",
    venus: "tvoju rođenu Veneru",
    mars: "tvoj rođeni Mars",
    jupiter: "tvoj rođeni Jupiter",
    saturn: "tvoj rođeni Saturn",
  },
  personalVerb: {
    conjunction: "prelazi preko",
    sextile: "podupire",
    trine: "blagoslivlja",
    square: "izaziva",
    opposition: "stavlja na kušnju",
  },
  aspectPhrase: {
    conjunction: "je u spoju",
    sextile: "je u prijateljskom sekstilu",
    trine: "je u skladnom trigonu",
    square: "je u napetom kvadratu",
    opposition: "je u opoziciji",
  },
  moonPhaseName: [
    "mlađak",
    "mladi srp",
    "prva četvrt",
    "rastući mjesec",
    "uštap",
    "opadajući mjesec",
    "zadnja četvrt",
    "stari srp",
  ],
  moonSignHint: {
    aries: "hrabrost i brz zalet.",
    taurus: "ustrajnost, novac i užitak.",
    gemini: "razgovori, pisanje i umrežavanje.",
    cancer: "dom, osjećaji i briga o sebi.",
    leo: "samopouzdanje i nastup.",
    virgo: "preciznost, red i detalji.",
    libra: "partnerstva i pošteni dogovori.",
    scorpio: "dubina, strategija i povjerenje.",
    sagittarius: "vizija, širenje i optimizam.",
    capricorn: "struktura, odgovornost i dugi ciljevi.",
    aquarius: "ideje, zajednica i drugačije.",
    pisces: "intuicija, snovi i povlačenje.",
  },
  pairHintGood: {
    "mercury-jupiter": "velikodušni dogovori i dobre vijesti.",
    "mercury-saturn": "čvrsti, promišljeni dogovori.",
    "mercury-mars": "jasne riječi i brze odluke.",
    "sun-jupiter": "sreća je na strani hrabrih.",
    "venus-jupiter": "obilje u ljubavi i financijama.",
    "venus-saturn": "vjernost i dugoročne vrijednosti.",
    "venus-mars": "privlačnost i strast.",
    "mars-saturn": "disciplina koja pomiče planine.",
    "mars-jupiter": "energija za velike korake.",
    "moon-jupiter": "optimizam i podrška.",
    "moon-saturn": "pouzdanost i ozbiljnost.",
    "moon-venus": "nježnost i ljepota.",
    "moon-mars": "zalet i odlučnost.",
  },
  pairHintTense: {
    "mercury-jupiter": "obećanja mogu biti prevelika.",
    "mercury-saturn": "prepreke, kašnjenja i sumnje.",
    "mercury-mars": "oštre riječi — promisli prije nego pošalješ.",
    "sun-jupiter": "pazi na pretjerivanje.",
    "venus-jupiter": "pazi na impulzivne kupnje.",
    "venus-saturn": "hladnoća i osjećaj manjka.",
    "venus-mars": "trenja u odnosima.",
    "mars-saturn": "frustracija — nemoj forsirati.",
    "mars-jupiter": "previše odjednom.",
    "moon-jupiter": "previše optimizma.",
    "moon-saturn": "teži osjećaji, potreba za povlačenjem.",
    "moon-venus": "osjetljivost.",
    "moon-mars": "razdražljivost.",
  },
  pairHintFallback: "naglašena energija dana.",
  personalHintGood: {
    mercury: "tvoje riječi danas uvjeravaju.",
    jupiter: "razdoblje prilika i rasta za tebe.",
    saturn: "trud koji uložiš ostaje.",
    mars: "imaš energiju za hrabar korak.",
    venus: "privlačiš ljude i prilike.",
    sun: "sjajiš — pokaži se.",
    moon: "emocionalno si u ravnoteži.",
  },
  personalHintHard: {
    mercury: "nesporazumi su vjerojatniji — piši jasno.",
    jupiter: "nemoj previše obećavati.",
    saturn: "razdoblje kušnje — uspori i učvrsti temelje.",
    mars: "pazi na svađe i premorenost.",
    venus: "nemoj kupovati ni obećavati iz osjećaja.",
    sun: "uzmi si više odmora.",
    moon: "osjećaji su bliže površini.",
  },
  personalHintFallback: "naglašen dan za tebe.",
  factor: {
    mercuryRetro:
      "☿℞ Merkur je retrogradan — ugovori, tehnika i poruke lako zalutaju. Dvaput pročitaj sitni tisak.",
    mercuryDirect: "☿ Merkur ide naprijed; riječi i dogovori teku glatko.",
    venusRetro:
      "♀℞ Venera je retrogradna — nije vrijeme za velike kupnje ni nove ljubavne obveze; dobro je za obnavljanje starih veza.",
    marsRetro: "♂℞ Mars je retrogradan — energija se okreće prema unutra, nemoj gurati glavom kroz zid.",
    planetStation: (planet) => `⏸️ ${planet} danas mijenja smjer — dan nesigurnosti, dok se stvari još pomiču.`,
    moonVoid: "🕳️ Mjesec je „bez smjera“ (void of course) — ono što sada počne rijetko stigne do cilja.",
    eclipseToday: (kind) => `🌘 Danas je ${kind} pomrčina — dan za promatranje, ne za odluke.`,
    eclipseApproaching: (kind) => `🌘 Bliži se ${kind} pomrčina — energija je nemirna.`,
    eclipsePassed: (kind) => `🌘 Iza nas je ${kind} pomrčina — energija je nemirna.`,
    eclipseSolar: "Sunčeva",
    eclipseLunar: "Mjesečeva",
    newMoon: "🌑 Mlađak — sjeme koje sada posadiš ima cijeli mjesec za rast.",
    fullMoon: "🌕 Uštap — vrijeme za dovršetke, zahvalnost i iskrene razgovore.",
    waxing: "🌒 Mjesec raste — ono što započneš dobiva snagu.",
    waning: "🌖 Mjesec opada — dobro za dovršavanje i čišćenje.",
    balsamic: "🌘 Zadnji dani prije mlađaka — pusti, odmori se, napravi prostor.",
    moonOverNatalSun: "🌞 Mjesec prelazi preko tvog rođenog Sunca — tvoj mjesečni osobni novi početak.",
    lunarReturn: "🌙 Mjesec se vraća na mjesto s tvog rođenja — poslušaj osjećaje.",
  },
  month: {
    intro: {
      contracts: "Ovaj je mjesec naklonjen dogovorima: jasna riječ i potpis nose više nego inače.",
      beginnings: "Ovaj mjesec otvara vrata novome: ideje koje čekaju u ladici imaju vjetar u leđa.",
      avoid: "Ovaj mjesec traži strpljenje: više je dana za dovršavanje nego za započinjanje.",
      self: "Ovo je mjesec unutarnjeg rada: odmor i promišljanje najbolja su ti strategija.",
    },
    forSign: (sign) => `Za znak ${sign}: `,
    mercuryRetro: "☿℞ Dio mjeseca Merkur je retrogradan — ugovore čitaj dvaput, tehniku sigurnosno kopiraj.",
    venusRetro: "♀℞ Venera je retrogradna — promisli o svakoj većoj kupnji i novoj obvezi.",
    marsRetro: "♂℞ Mars je retrogradan — energiju usmjeri u dovršavanje.",
    eclipseOn: (date, kind) => `🌘 ${date} je ${kind} pomrčina — dan za promatranje, ne za odluke.`,
    bestContracts: "Najbolji dani za ugovore",
    bestBeginnings: "Najbolji dani za početke",
    forMoney: "Za novac",
    forLove: "Za ljubav",
    forHealth: "Za zdravlje",
    startNothing: "Ne počinji ništa",
    disclaimer: "✨ Kalendar je nadahnuće za planiranje, a ne financijski savjet — zadnja je riječ uvijek tvoja.",
    titlePersonal: (month) => `${month} — tvoj osobni horoskop`,
    titleOverview: (month) => `${month} — pregled mjeseca`,
  },
};
