import type { AstroStrings } from "./types";

export const it: AstroStrings = {
  locale: "it-IT",
  productName: "Calendario stellare d'affari",
  typeLabel: {
    contracts: "Buono per i contratti",
    beginnings: "Buono per gli inizi",
    avoid: "Non iniziare nulla",
    self: "Tempo per te",
  },
  typeAdvice: {
    contracts: "Firme, trattative, email importanti e accordi.",
    beginnings: "Avvio di un progetto, primo post, nuovo cliente, primo passo.",
    avoid: "Concludi, riordina e aspetta — non cominciare niente di nuovo.",
    self: "Riposo, bilancio, decisioni a mente fredda.",
  },
  categoryLabel: {
    contracts: "Contratti",
    beginnings: "Inizi",
    avoid: "Non iniziare",
    self: "Tempo per te",
    love: "Amore",
    money: "Denaro",
    health: "Salute",
  },
  signName: {
    aries: "Ariete",
    taurus: "Toro",
    gemini: "Gemelli",
    cancer: "Cancro",
    leo: "Leone",
    virgo: "Vergine",
    libra: "Bilancia",
    scorpio: "Scorpione",
    sagittarius: "Sagittario",
    capricorn: "Capricorno",
    aquarius: "Acquario",
    pisces: "Pesci",
  },
  moonInSign: {
    aries: "in Ariete",
    taurus: "in Toro",
    gemini: "in Gemelli",
    cancer: "in Cancro",
    leo: "in Leone",
    virgo: "in Vergine",
    libra: "in Bilancia",
    scorpio: "in Scorpione",
    sagittarius: "in Sagittario",
    capricorn: "in Capricorno",
    aquarius: "in Acquario",
    pisces: "in Pesci",
  },
  planetName: {
    sun: "Il Sole",
    moon: "La Luna",
    mercury: "Mercurio",
    venus: "Venere",
    mars: "Marte",
    jupiter: "Giove",
    saturn: "Saturno",
  },
  planetObject: {
    sun: "al Sole",
    moon: "alla Luna",
    mercury: "a Mercurio",
    venus: "a Venere",
    mars: "a Marte",
    jupiter: "a Giove",
    saturn: "a Saturno",
  },
  natalPlanet: {
    sun: "il tuo Sole natale",
    moon: "la tua Luna natale",
    mercury: "il tuo Mercurio natale",
    venus: "la tua Venere natale",
    mars: "il tuo Marte natale",
    jupiter: "il tuo Giove natale",
    saturn: "il tuo Saturno natale",
  },
  personalVerb: {
    conjunction: "transita su",
    sextile: "sostiene",
    trine: "benedice",
    square: "sfida",
    opposition: "mette alla prova",
  },
  aspectPhrase: {
    conjunction: "è in congiunzione",
    sextile: "è in sestile amichevole",
    trine: "è in trigono armonioso",
    square: "è in quadratura tesa",
    opposition: "è in opposizione",
  },
  moonPhaseName: [
    "luna nuova",
    "luna crescente",
    "primo quarto",
    "gibbosa crescente",
    "luna piena",
    "gibbosa calante",
    "ultimo quarto",
    "luna calante",
  ],
  moonSignHint: {
    aries: "coraggio e partenza rapida.",
    taurus: "costanza, denaro e piacere.",
    gemini: "conversazioni, scrittura e contatti.",
    cancer: "casa, emozioni e cura di sé.",
    leo: "sicurezza e presenza.",
    virgo: "precisione, ordine e dettagli.",
    libra: "collaborazioni e accordi equi.",
    scorpio: "profondità, strategia e fiducia.",
    sagittarius: "visione, espansione e ottimismo.",
    capricorn: "struttura, responsabilità e obiettivi lunghi.",
    aquarius: "idee, comunità e fare le cose diversamente.",
    pisces: "intuizione, sogni e ritiro.",
  },
  pairHintGood: {
    "mercury-jupiter": "accordi generosi e buone notizie.",
    "mercury-saturn": "intese solide e ben ponderate.",
    "mercury-mars": "parole chiare e decisioni rapide.",
    "sun-jupiter": "la fortuna sta dalla parte degli audaci.",
    "venus-jupiter": "abbondanza in amore e nelle finanze.",
    "venus-saturn": "fedeltà e valori che durano.",
    "venus-mars": "attrazione e passione.",
    "mars-saturn": "una disciplina che sposta le montagne.",
    "mars-jupiter": "energia per grandi passi.",
    "moon-jupiter": "ottimismo e sostegno.",
    "moon-saturn": "affidabilità e serietà.",
    "moon-venus": "tenerezza e bellezza.",
    "moon-mars": "slancio e determinazione.",
  },
  pairHintTense: {
    "mercury-jupiter": "le promesse rischiano di essere troppo grandi.",
    "mercury-saturn": "ostacoli, ritardi e dubbi.",
    "mercury-mars": "parole taglienti — pensa prima di inviare.",
    "sun-jupiter": "attenzione a esagerare.",
    "venus-jupiter": "attenzione agli acquisti impulsivi.",
    "venus-saturn": "freddezza e un senso di mancanza.",
    "venus-mars": "attriti nelle relazioni.",
    "mars-saturn": "frustrazione — non forzare le cose.",
    "mars-jupiter": "troppo tutto insieme.",
    "moon-jupiter": "un po' troppo ottimismo.",
    "moon-saturn": "emozioni più pesanti, bisogno di ritirarsi.",
    "moon-venus": "sensibilità.",
    "moon-mars": "irritabilità.",
  },
  pairHintFallback: "un'energia in evidenza oggi.",
  personalHintGood: {
    mercury: "oggi le tue parole convincono.",
    jupiter: "una stagione di occasioni e crescita per te.",
    saturn: "l'impegno che ci metti resta.",
    mars: "hai l'energia per un passo coraggioso.",
    venus: "attiri persone e occasioni.",
    sun: "risplendi — fatti vedere.",
    moon: "sei in equilibrio emotivo.",
  },
  personalHintHard: {
    mercury: "i malintesi sono più probabili — scrivi chiaro.",
    jupiter: "non promettere troppo.",
    saturn: "una stagione di prova — rallenta e rinforza le fondamenta.",
    mars: "attenzione ai conflitti e alla stanchezza.",
    venus: "non comprare e non promettere di slancio.",
    sun: "prenditi più riposo.",
    moon: "le emozioni sono vicine alla superficie.",
  },
  personalHintFallback: "una giornata in evidenza per te.",
  factor: {
    mercuryRetro:
      "☿℞ Mercurio è retrogrado — contratti, tecnologia e messaggi si perdono facilmente. Leggi due volte le clausole in piccolo.",
    mercuryDirect: "☿ Mercurio va avanti; parole e accordi scorrono.",
    venusRetro:
      "♀℞ Venere è retrograda — non è il momento per grandi acquisti o nuovi impegni amorosi; è buono per far rivivere legami passati.",
    marsRetro: "♂℞ Marte è retrogrado — l'energia si volge all'interno; non forzare la testa contro il muro.",
    planetStation: (planet) => `⏸️ ${planet} cambia direzione oggi — una giornata incerta, mentre le cose si spostano.`,
    moonVoid: "🕳️ La Luna è «senza rotta» (void of course) — ciò che inizia ora raramente arriva a destinazione.",
    eclipseToday: (kind) => `🌘 Oggi c'è un'eclissi ${kind} — un giorno per osservare, non per decidere.`,
    eclipseApproaching: (kind) => `🌘 Si avvicina un'eclissi ${kind} — l'energia è inquieta.`,
    eclipsePassed: (kind) => `🌘 È appena passata un'eclissi ${kind} — l'energia è inquieta.`,
    eclipseSolar: "solare",
    eclipseLunar: "lunare",
    newMoon: "🌑 Luna nuova — un seme piantato ora ha tutto il mese per crescere.",
    fullMoon: "🌕 Luna piena — tempo di conclusioni, gratitudine e conversazioni sincere.",
    waxing: "🌒 La Luna cresce — ciò che inizi prende forza.",
    waning: "🌖 La Luna cala — buono per concludere e fare pulizia.",
    balsamic: "🌘 Gli ultimi giorni prima della luna nuova — lascia andare, riposa, fai spazio.",
    moonOverNatalSun: "🌞 La Luna transita sul tuo Sole natale — il tuo inizio personale del mese.",
    lunarReturn: "🌙 La Luna torna dov'era alla tua nascita — ascolta le emozioni.",
  },
  month: {
    intro: {
      contracts: "Questo mese favorisce gli accordi: una parola chiara e una firma pesano più del solito.",
      beginnings: "Questo mese apre le porte al nuovo: le idee ferme in un cassetto hanno il vento in poppa.",
      avoid: "Questo mese chiede pazienza: più giorni si prestano a concludere che a cominciare.",
      self: "Questo è un mese di lavoro interiore: riposo e riflessione sono la tua strategia migliore.",
    },
    forSign: (sign) => `Per il segno ${sign}: `,
    mercuryRetro: "☿℞ Per una parte del mese Mercurio è retrogrado — leggi i contratti due volte e fai il backup.",
    venusRetro: "♀℞ Venere è retrograda — pensaci due volte prima di un grande acquisto o di un nuovo impegno.",
    marsRetro: "♂℞ Marte è retrogrado — indirizza l'energia verso ciò che va concluso.",
    eclipseOn: (date, kind) => `🌘 Il ${date} c'è un'eclissi ${kind} — un giorno per osservare, non per decidere.`,
    bestContracts: "Giorni migliori per i contratti",
    bestBeginnings: "Giorni migliori per gli inizi",
    forMoney: "Per il denaro",
    forLove: "Per l'amore",
    forHealth: "Per la salute",
    startNothing: "Non iniziare nulla",
    disclaimer:
      "✨ Il calendario è un'ispirazione per pianificare, non una consulenza finanziaria — l'ultima parola è sempre tua.",
    titlePersonal: (month) => `${month} — il tuo oroscopo personale`,
    titleOverview: (month) => `${month} — panoramica del mese`,
  },
};
