import type { AstroStrings } from "./types";

export const sl: AstroStrings = {
  locale: "sl-SI",
  productName: "Zvezdni poslovni koledar",
  typeLabel: {
    contracts: "Dober za pogodbe",
    beginnings: "Dober za začetke",
    avoid: "Ne začenjaj ničesar",
    self: "Čas zase",
  },
  typeAdvice: {
    contracts: "Podpisi, pogajanja, pomembni emaili in dogovori.",
    beginnings: "Zagon projekta, prva objava, nova stranka, prvi korak.",
    avoid: "Dokončuj, urejaj in čakaj — novega ne začenjaj.",
    self: "Počitek, pregled, odločitve na hladno.",
  },
  categoryLabel: {
    contracts: "Pogodbe",
    beginnings: "Začetki",
    avoid: "Ne začenjaj",
    self: "Čas zase",
    love: "Ljubezen",
    money: "Denar",
    health: "Zdravje",
  },
  signName: {
    aries: "Oven",
    taurus: "Bik",
    gemini: "Dvojčka",
    cancer: "Rak",
    leo: "Lev",
    virgo: "Devica",
    libra: "Tehtnica",
    scorpio: "Škorpijon",
    sagittarius: "Strelec",
    capricorn: "Kozorog",
    aquarius: "Vodnar",
    pisces: "Ribi",
  },
  moonInSign: {
    aries: "v Ovnu",
    taurus: "v Biku",
    gemini: "v Dvojčkih",
    cancer: "v Raku",
    leo: "v Levu",
    virgo: "v Devici",
    libra: "v Tehtnici",
    scorpio: "v Škorpijonu",
    sagittarius: "v Strelcu",
    capricorn: "v Kozorogu",
    aquarius: "v Vodnarju",
    pisces: "v Ribah",
  },
  planetName: {
    sun: "Sonce",
    moon: "Luna",
    mercury: "Merkur",
    venus: "Venera",
    mars: "Mars",
    jupiter: "Jupiter",
    saturn: "Saturn",
  },
  planetObject: {
    sun: "s Soncem",
    moon: "z Luno",
    mercury: "z Merkurjem",
    venus: "z Venero",
    mars: "z Marsom",
    jupiter: "z Jupitrom",
    saturn: "s Saturnom",
  },
  natalPlanet: {
    sun: "tvoje rojstno Sonce",
    moon: "tvojo rojstno Luno",
    mercury: "tvoj rojstni Merkur",
    venus: "tvojo rojstno Venero",
    mars: "tvoj rojstni Mars",
    jupiter: "tvoj rojstni Jupiter",
    saturn: "tvoj rojstni Saturn",
  },
  personalVerb: {
    conjunction: "prehaja",
    sextile: "podpira",
    trine: "blagoslavlja",
    square: "izziva",
    opposition: "postavlja na preizkušnjo",
  },
  aspectPhrase: {
    conjunction: "je v stiku",
    sextile: "je v prijaznem sekstilu",
    trine: "je v harmoničnem trigonu",
    square: "je v napetem kvadratu",
    opposition: "je v opoziciji",
  },
  moonPhaseName: [
    "mlaj",
    "rastoči srp",
    "prvi krajec",
    "rastoča luna",
    "ščip",
    "pojemajoča luna",
    "zadnji krajec",
    "pojemajoči srp",
  ],
  moonSignHint: {
    aries: "pogum in hiter zagon.",
    taurus: "vztrajnost, denar in užitek.",
    gemini: "pogovori, pisanje in mreženje.",
    cancer: "dom, čustva in skrb zase.",
    leo: "samozavest in nastop.",
    virgo: "natančnost, red in podrobnosti.",
    libra: "partnerstva in pošteni dogovori.",
    scorpio: "globina, strategija in zaupanje.",
    sagittarius: "vizija, širjenje in optimizem.",
    capricorn: "struktura, odgovornost in dolgi cilji.",
    aquarius: "ideje, skupnost in drugačnost.",
    pisces: "intuicija, sanje in umik.",
  },
  pairHintGood: {
    "mercury-jupiter": "velikodušni dogovori in dobre novice.",
    "mercury-saturn": "trdni, premišljeni dogovori.",
    "mercury-mars": "jasne besede in hitre odločitve.",
    "sun-jupiter": "sreča je na strani drznih.",
    "venus-jupiter": "obilje v ljubezni in financah.",
    "venus-saturn": "zvestoba in dolgoročne vrednosti.",
    "venus-mars": "privlačnost in strast.",
    "mars-saturn": "disciplina, ki premika gore.",
    "mars-jupiter": "energija za velike korake.",
    "moon-jupiter": "optimizem in podpora.",
    "moon-saturn": "zanesljivost in resnost.",
    "moon-venus": "nežnost in lepota.",
    "moon-mars": "zagon in odločnost.",
  },
  pairHintTense: {
    "mercury-jupiter": "obljube so lahko prevelike.",
    "mercury-saturn": "ovire, zamude in dvomi.",
    "mercury-mars": "ostre besede — premisli, preden pošlješ.",
    "sun-jupiter": "pazi na pretiravanje.",
    "venus-jupiter": "pazi na impulzivne nakupe.",
    "venus-saturn": "hladnost in občutek pomanjkanja.",
    "venus-mars": "trenja v odnosih.",
    "mars-saturn": "frustracija — ne sili stvari.",
    "mars-jupiter": "preveč naenkrat.",
    "moon-jupiter": "preveč optimizma.",
    "moon-saturn": "težja čustva, potreba po umiku.",
    "moon-venus": "občutljivost.",
    "moon-mars": "razdražljivost.",
  },
  pairHintFallback: "poudarjena energija dneva.",
  personalHintGood: {
    mercury: "tvoje besede danes prepričajo.",
    jupiter: "obdobje priložnosti in rasti zate.",
    saturn: "trud, ki ga vložiš, ostane.",
    mars: "imaš energijo za pogumen korak.",
    venus: "privlačiš ljudi in priložnosti.",
    sun: "sijaš — pokaži se.",
    moon: "čustveno si v ravnovesju.",
  },
  personalHintHard: {
    mercury: "nesporazumi so bolj verjetni — piši jasno.",
    jupiter: "ne obljubljaj preveč.",
    saturn: "obdobje preizkušenj — upočasni in utrdi temelje.",
    mars: "pazi na prepire in preutrujenost.",
    venus: "ne kupuj in ne obljubljaj iz občutka.",
    sun: "vzemi si več počitka.",
    moon: "čustva so bližje površju.",
  },
  personalHintFallback: "poudarjen dan zate.",
  factor: {
    mercuryRetro: "☿℞ Merkur je retrogradno — pogodbe, tehnika in sporočila radi zaidejo. Dvakrat preveri drobni tisk.",
    mercuryDirect: "☿ Merkur teče naprej, besede in dogovori gredo gladko.",
    venusRetro:
      "♀℞ Venera je retrogradno — ni čas za velike nakupe ali nove ljubezenske zaveze; dober čas za obujanje starih vezi.",
    marsRetro: "♂℞ Mars je retrogradno — energija se obrača navznoter, ne sili z glavo skozi zid.",
    planetStation: (planet) => `⏸️ ${planet} danes obrača smer — dan negotovosti, ko se stvari še premikajo.`,
    moonVoid: "🕳️ Luna je „brez smeri“ (void of course) — kar se začne zdaj, redko pride do cilja.",
    eclipseToday: (kind) => `🌘 Danes je ${kind} mrk — dan za opazovanje, ne za odločitve.`,
    eclipseApproaching: (kind) => `🌘 Bliža se ${kind} mrk — energija je nemirna.`,
    eclipsePassed: (kind) => `🌘 Za nami je ${kind} mrk — energija je nemirna.`,
    eclipseSolar: "sončev",
    eclipseLunar: "lunin",
    newMoon: "🌑 Mlaj — seme, ki ga posadiš zdaj, ima ves mesec za rast.",
    fullMoon: "🌕 Ščip — čas za zaključke, hvaležnost in odkrite pogovore.",
    waxing: "🌒 Luna raste — kar začneš, dobiva moč.",
    waning: "🌖 Luna pojema — dobro za dokončevanje in čiščenje.",
    balsamic: "🌘 Zadnji dnevi pred mlajem — spusti, počivaj, pripravi prostor.",
    moonOverNatalSun: "🌞 Luna prehaja tvoje rojstno Sonce — tvoj mesečni osebni nov začetek.",
    lunarReturn: "🌙 Luna se vrača na mesto ob tvojem rojstvu — prisluhni čustvom.",
  },
  month: {
    intro: {
      contracts: "Ta mesec je naklonjen dogovorom: jasna beseda in podpisi prinašajo več kot običajno.",
      beginnings: "Ta mesec odpira vrata novemu: ideje, ki čakajo v predalu, imajo veter v hrbet.",
      avoid: "Ta mesec prosi za potrpežljivost: več dni je primernih za dokončevanje kot za začenjanje.",
      self: "Ta mesec je mesec notranjega dela: počitek in premislek sta tvoja najboljša strategija.",
    },
    forSign: (sign) => `Za znamenje ${sign}: `,
    mercuryRetro: "☿℞ Del meseca je Merkur retrogradno — pogodbe beri dvakrat, tehniko varnostno kopiraj.",
    venusRetro: "♀℞ Venera je retrogradno — premisli vsak večji nakup in novo zavezo.",
    marsRetro: "♂℞ Mars je retrogradno — energijo usmeri v dokončevanje.",
    eclipseOn: (date, kind) => `🌘 ${date} je ${kind} mrk — dan za opazovanje, ne za odločitve.`,
    bestContracts: "Najboljši dnevi za pogodbe",
    bestBeginnings: "Najboljši dnevi za začetke",
    forMoney: "Za denar",
    forLove: "Za ljubezen",
    forHealth: "Za zdravje",
    startNothing: "Ne začenjaj ničesar",
    disclaimer: "✨ Koledar je navdih za načrtovanje, ne finančni nasvet — zadnja beseda je vedno tvoja.",
    titlePersonal: (month) => `${month} — tvoj osebni horoskop`,
    titleOverview: (month) => `${month} — pregled meseca`,
  },
};
